/* =====================================================
   Marathi corner data: proverbs (म्हणी) and words for the day.
   The homepage picks one of each based on the day of the year,
   so the more entries here, the longer before they repeat.

   To add a proverb: copy a line in LM_MHANI and change the
   Marathi proverb (m) and the short English meaning (a).
   To add a word: copy a line in LM_SHABDA and change the word (s),
   how to say it (r), the meaning (e) and a short example (ex).
   Keep the commas and quotes exactly as they are.
   ===================================================== */
window.LM_MHANI = [
  { m: 'थेंबे थेंबे तळे साचे', a: 'Drop by drop, a pond fills up. Small things add up.' },
  { m: 'नाचता येईना अंगण वाकडे', a: 'The one who cannot dance blames the uneven floor.' },
  { m: 'अति तेथे माती', a: 'Too much of anything spoils it.' },
  { m: 'पी हळद हो गोरी', a: 'Drink turmeric today, be fair tomorrow. Wanting results instantly.' },
  { m: 'आधी पोटोबा मग विठोबा', a: 'Food first, prayers after.' },
  { m: 'उथळ पाण्याला खळखळाट फार', a: 'Shallow water makes the most noise.' },
  { m: 'गाढवाला गुळाची चव काय', a: 'What does a donkey know of the taste of jaggery?' },
  { m: 'हातच्या काकणाला आरसा कशाला', a: 'Why a mirror to see the bangle on your own wrist? Some things are obvious.' },
  { m: 'ज्याची खावी पोळी त्याची वाजवावी टाळी', a: 'Praise the one whose bread you eat.' },
  { m: 'दुरून डोंगर साजरे', a: 'Mountains look lovely from far away.' },
  { m: 'नावडतीचं मीठ अळणी', a: 'Even the salt of someone you dislike tastes bland.' },
  { m: 'पालथ्या घड्यावर पाणी', a: 'Water poured on an upturned pot. Advice that goes nowhere.' },
  { m: 'शितावरून भाताची परीक्षा', a: 'One grain tells you how the whole pot of rice has cooked.' },
  { m: 'एका हाताने टाळी वाजत नाही', a: 'It takes two hands to clap.' },
  { m: 'कर नाही त्याला डर कशाला', a: 'Nothing to hide, nothing to fear.' },
  { m: 'चार दिवस सासूचे चार दिवस सुनेचे', a: 'Four days for the mother in law, four for the daughter in law. Everyone gets a turn.' },
  { m: 'मुलाचे पाय पाळण्यात दिसतात', a: 'You can see the child’s future in the cradle.' },
  { m: 'वासरात लंगडी गाय शहाणी', a: 'Among calves, even the lame cow is the wise one.' },
  { m: 'आयत्या बिळावर नागोबा', a: 'The cobra moves into a ready made hole. Taking over someone else’s work.' },
  { m: 'अंथरूण पाहून पाय पसरावे', a: 'Stretch your legs only as far as your blanket.' },
  { m: 'बोलाचाच भात बोलाचीच कढी', a: 'Rice made of words, curry made of words. All talk, no action.' },
  { m: 'रात्र थोडी सोंगं फार', a: 'A short night and many acts to play. Too much to do, too little time.' },
  { m: 'गरज सरो वैद्य मरो', a: 'Once the need is over, forget the doctor.' },
  { m: 'कामापुरता मामा', a: 'An uncle only when there is work to be done.' },
  { m: 'टाकीचे घाव सोसल्याशिवाय देवपण येत नाही', a: 'Without the chisel’s blows, the stone never becomes a god.' },
  { m: 'ऐकावे जनाचे करावे मनाचे', a: 'Listen to everyone, then do what your own mind says.' },
  { m: 'देश तसा वेश', a: 'Dress the way the country dresses. When in Rome.' },
  { m: 'इकडे आड तिकडे विहीर', a: 'A well on this side, a well on that side. No easy way out.' },
  { m: 'खाईन तर तुपाशी नाहीतर उपाशी', a: 'Either with ghee or not at all.' },
  { m: 'घरोघरी मातीच्या चुली', a: 'Every house has the same clay stove. Everyone has the same troubles.' },
  { m: 'दगडापेक्षा वीट मऊ', a: 'A brick is softer than a stone. The lesser of two evils.' },
  { m: 'हसतील त्यांचे दात दिसतील', a: 'Let them laugh, we will see their teeth.' },
  { m: 'जित्याची खोड मेल्याशिवाय जात नाही', a: 'Old habits die hard.' },
  { m: 'उंटावरून शेळ्या हाकणे', a: 'Herding goats from the top of a camel. Doing a job without care.' },
  { m: 'आपला हात जगन्नाथ', a: 'Your own hand is your god. Help yourself.' },
  { m: 'वरातीमागून घोडे', a: 'Horses arriving after the wedding procession. Too late.' },
  { m: 'लहान तोंडी मोठा घास', a: 'A big bite for a small mouth. Taking on more than you should.' },
  { m: 'मऊ सापडले म्हणून कोपराने खणू नये', a: 'Soft ground is no reason to dig with your elbow. Do not take advantage of kindness.' },
  { m: 'एक ना धड भाराभर चिंध्या', a: 'Not one whole cloth, just a bundle of rags. Jack of all trades.' },
  { m: 'साखरेचे खाणार त्याला देव देणार', a: 'God provides for the one who eats sugar. Good things come to the cheerful.' },
];

window.LM_SHABDA = [
  { s: 'आकाश', r: 'aakaash', e: 'sky', ex: 'आज आकाश निळं आहे.' },
  { s: 'पाऊस', r: 'paaus', e: 'rain', ex: 'बाहेर पाऊस पडतोय.' },
  { s: 'फुलपाखरू', r: 'phulpaakharu', e: 'butterfly', ex: 'बागेत फुलपाखरू उडतंय.' },
  { s: 'आजी', r: 'aaji', e: 'grandmother', ex: 'आजी गोष्ट सांगते.' },
  { s: 'आजोबा', r: 'aajoba', e: 'grandfather', ex: 'आजोबा फिरायला जातात.' },
  { s: 'चांदणी', r: 'chaandani', e: 'star', ex: 'रात्री चांदण्या चमकतात.' },
  { s: 'मित्र', r: 'mitra', e: 'friend', ex: 'तो माझा मित्र आहे.' },
  { s: 'शाळा', r: 'shaala', e: 'school', ex: 'मी शाळेत जातो.' },
  { s: 'पुस्तक', r: 'pustak', e: 'book', ex: 'हे पुस्तक छान आहे.' },
  { s: 'खिडकी', r: 'khidki', e: 'window', ex: 'खिडकी उघड.' },
  { s: 'दार', r: 'daar', e: 'door', ex: 'दार बंद कर.' },
  { s: 'भात', r: 'bhaat', e: 'cooked rice', ex: 'आज जेवायला भात आहे.' },
  { s: 'गोड', r: 'god', e: 'sweet', ex: 'लाडू गोड आहे.' },
  { s: 'मोठा', r: 'motha', e: 'big', ex: 'हा हत्ती मोठा आहे.' },
  { s: 'छोटा', r: 'chhota', e: 'small', ex: 'ते पिल्लू छोटं आहे.' },
  { s: 'लाल', r: 'laal', e: 'red', ex: 'टोमॅटो लाल आहे.' },
  { s: 'हिरवा', r: 'hirwa', e: 'green', ex: 'पोपट हिरवा आहे.' },
  { s: 'पाणी', r: 'paani', e: 'water', ex: 'मला पाणी दे.' },
  { s: 'झाड', r: 'jhaad', e: 'tree', ex: 'झाडावर पक्षी बसला आहे.' },
  { s: 'पक्षी', r: 'pakshi', e: 'bird', ex: 'पक्षी उडतो.' },
  { s: 'मांजर', r: 'maanjar', e: 'cat', ex: 'मांजर दूध पिते.' },
  { s: 'कुत्रा', r: 'kutra', e: 'dog', ex: 'कुत्रा भुंकतो.' },
  { s: 'हत्ती', r: 'hatti', e: 'elephant', ex: 'हत्ती खूप मोठा असतो.' },
  { s: 'चंद्र', r: 'chandra', e: 'moon', ex: 'रात्री चंद्र दिसतो.' },
  { s: 'सूर्य', r: 'surya', e: 'sun', ex: 'सकाळी सूर्य उगवतो.' },
  { s: 'घर', r: 'ghar', e: 'home', ex: 'मी घरी जातो.' },
  { s: 'आई', r: 'aai', e: 'mother', ex: 'आई स्वयंपाक करते.' },
  { s: 'बाबा', r: 'baaba', e: 'father', ex: 'बाबा ऑफिसला जातात.' },
  { s: 'ताई', r: 'taai', e: 'elder sister', ex: 'ताई अभ्यास करते.' },
  { s: 'दादा', r: 'daada', e: 'elder brother', ex: 'दादा क्रिकेट खेळतो.' },
  { s: 'खेळ', r: 'khel', e: 'game', ex: 'चला, खेळ खेळू.' },
  { s: 'गाणं', r: 'gaanam', e: 'song', ex: 'आई गाणं म्हणते.' },
  { s: 'नाच', r: 'naach', e: 'dance', ex: 'आम्ही लेझीम नाच केला.' },
  { s: 'रंग', r: 'rang', e: 'colour', ex: 'तुझा आवडता रंग कोणता?' },
  { s: 'फूल', r: 'phool', e: 'flower', ex: 'हे फूल सुंदर आहे.' },
  { s: 'साखर', r: 'saakhar', e: 'sugar', ex: 'चहात साखर घाल.' },
  { s: 'दूध', r: 'doodh', e: 'milk', ex: 'मी रोज दूध पितो.' },
  { s: 'आंबा', r: 'aamba', e: 'mango', ex: 'आंबा माझं आवडतं फळ आहे.' },
  { s: 'थंडी', r: 'thandi', e: 'cold weather', ex: 'आज खूप थंडी आहे.' },
  { s: 'गरम', r: 'garam', e: 'hot', ex: 'चहा गरम आहे.' },
];
