/* =====================================================
   आपला महाराष्ट्र: places shown on the map (maharashtra.html).

   Each place has: cat (kille, yugpurush, devasthan, paryatan), the Marathi
   and English name, where it is (lon, lat), the district, two or three
   plain lines in Marathi (mr) and English (en), and an optional photo:
     photo: 'images/maharashtra/raigad.jpg', credit: 'the Kulkarni family, 2023'
   Leave photo out and the card shows a "send us your photo" slot.
   dx/dy nudge a pin a few pixels when two places sit very close together.

   TODO committee and volunteers: the mr/en lines are first drafts, please
   replace them with your own words and add your names to the credits
   at the bottom of maharashtra.html.
   ===================================================== */
window.LM_PLACES = [
  // ---------- किल्ले ----------
  // Forts carry a longer history (hmr/hen, a few short paragraphs each) and a facts list
  // shown under the short lines in the detail panel.
  { cat: 'kille', mr: 'रायगड', en: 'Raigad', lon: 73.44, lat: 18.23, dist: 'रायगड',
    tmr: 'स्वराज्याची राजधानी. ६ जून १६७४ रोजी इथेच शिवराज्याभिषेक झाला. महाराजांची समाधीही इथेच आहे.',
    ten: 'The capital of Swarajya. Shivaji Maharaj was crowned here on 6 June 1674, and his samadhi is on the fort.',
    hmr: [
      'या डोंगराचं जुनं नाव रायरी. १६५६ मध्ये जावळीच्या मोऱ्यांकडून शिवाजी महाराजांनी तो घेतला. चारही बाजूंनी सरळ कडे, वर मोकळं पठार आणि पाण्याची सोय, म्हणून राजधानीसाठी हाच किल्ला निवडला. हिरोजी इंदुलकरांनी गडावरचे राजवाडे, बाजारपेठ, तळी आणि दरवाजे बांधले.',
      '६ जून १६७४ रोजी गागाभट्टांच्या हस्ते इथे राज्याभिषेक झाला आणि शिवाजी महाराज छत्रपती झाले. ३ एप्रिल १६८० रोजी याच गडावर त्यांचं निधन झालं. जगदीश्वर मंदिरासमोर त्यांची समाधी आहे. पुढे संभाजी महाराजांचा राज्याभिषेकही इथेच झाला.',
      '१६८९ मध्ये मोगलांनी गड घेतला आणि त्याचं नाव इस्लामगड ठेवलं. १८६९ मध्ये महात्मा फुल्यांनी झाडाझुडपांत हरवलेली समाधी शोधून काढली आणि लोकमान्य टिळकांनी गडावर उत्सव सुरू केला. आज महाराजांची समाधी, राजसदर, होळीचा माळ, टकमक टोक आणि हिरकणी बुरूज पाहायला लाखो लोक येतात.',
    ],
    hen: [
      'The hill was once called Rairi. Shivaji Maharaj took it from the Mores of Javli in 1656. Sheer cliffs on every side, a wide plateau on top and plenty of water made it the obvious choice for a capital. Hiroji Indulkar built the palaces, the market street, the tanks and the gates.',
      'On 6 June 1674 the coronation was performed here by Gagabhatt and Shivaji Maharaj became Chhatrapati. He died on this fort on 3 April 1680, and his samadhi stands in front of the Jagdishwar temple. Sambhaji Maharaj was crowned here too.',
      'The Mughals took the fort in 1689 and renamed it Islamgad. In 1869 Mahatma Phule found the samadhi lost in the undergrowth, and Lokmanya Tilak started an annual festival on the fort. Today lakhs of people come to see the samadhi, the royal court, Holicha Mal, Takmak Tok and the Hirkani bastion.',
    ],
    facts: [['उंची', 'सुमारे ८२० मीटर'], ['जवळचं गाव', 'महाड, २५ किमी'], ['जायचं कसं', 'पायऱ्या (सुमारे १४५०) किंवा रोपवे'], ['कधी जावं', 'ऑक्टोबर ते फेब्रुवारी']] },
  { cat: 'kille', mr: 'राजगड', en: 'Rajgad', lon: 73.68, lat: 18.25, dist: 'पुणे', dy: 8,
    tmr: 'रायगडाआधी जवळपास पंचवीस वर्षं स्वराज्याची राजधानी. पुण्याजवळचा ट्रेकर्सचा आवडता किल्ला.',
    ten: 'The capital of Swarajya for about 25 years before Raigad. A favourite trek near Pune.',
    hmr: [
      'या डोंगराचं जुनं नाव मुरुंबदेव. १६४७ च्या सुमारास शिवाजी महाराजांनी तो घेतला आणि तोरण्यावर सापडलेल्या धनातून गड बांधला, अशी गोष्ट सांगतात. १६४८ ते १६७० अशी सुमारे पंचवीस वर्षं ही स्वराज्याची पहिली राजधानी होती. महाराजांच्या आयुष्यातला सर्वात मोठा काळ इथे गेला.',
      'गडाला तीन माच्या आहेत: पद्मावती, सुवेळा आणि संजीवनी, आणि मधोमध उंच बालेकिल्ला. संजीवनी माचीची दुहेरी तटबंदी आणि चिलखती बुरूज हा बांधकामाचा नमुना मानला जातो. राजाराम महाराजांचा जन्म इथे झाला आणि सईबाईंचं निधनही इथेच झालं.',
      'राजधानी रायगडाला गेल्यावरही राजगडाचं महत्त्व राहिलं. आज गुंजवणे किंवा पाली गावातून चढणारे ट्रेकर्स पद्मावती माचीवर मुक्काम करतात आणि पहाटे बालेकिल्ल्यावरून सह्याद्री पाहतात.',
    ],
    hen: [
      'The hill was called Murumbdev. Shivaji Maharaj took it around 1647 and, the story goes, built the fort with treasure found on Torna. From about 1648 to 1670 it was the first capital of Swarajya, and the longest stretch of his life was spent here.',
      'The fort has three machis, Padmavati, Suvela and Sanjivani, with the tall Balekilla in the middle. The double walls and armoured bastions of Sanjivani machi are considered a masterpiece of fort building. Rajaram Maharaj was born here, and Saibai died here.',
      'Rajgad stayed important even after the capital moved to Raigad. Today trekkers climb from Gunjavane or Pali, sleep on Padmavati machi and watch the Sahyadris from the Balekilla at dawn.',
    ],
    facts: [['उंची', 'सुमारे १३७६ मीटर'], ['जवळचं गाव', 'वेल्हे / गुंजवणे, पुण्यापासून ६० किमी'], ['जायचं कसं', 'पायी, ३ ते ४ तासांचा ट्रेक'], ['कधी जावं', 'पावसाळ्यानंतर, सप्टेंबर ते फेब्रुवारी']] },
  { cat: 'kille', mr: 'सिंहगड', en: 'Sinhagad', lon: 73.75, lat: 18.37, dist: 'पुणे',
    tmr: '१६७० मध्ये तानाजी मालुसरेंनी हा किल्ला जिंकला. "गड आला पण सिंह गेला." पुण्यापासून तासाभरावर.',
    ten: 'Won by Tanaji Malusare in 1670. "The fort is won, but the lion is lost." An hour from Pune.',
    hmr: [
      'जुनं नाव कोंढाणा. पुरंदरच्या तहात (१६६५) हा किल्ला मोगलांना द्यावा लागला होता. तो परत मिळवण्यासाठी ४ फेब्रुवारी १६७० च्या रात्री तानाजी मालुसरे मावळ्यांसह डोणागिरीच्या कड्यावरून चढले. उदयभान राठोडशी झालेल्या लढाईत तानाजी पडले, पण गड जिंकला.',
      '"गड आला पण सिंह गेला" हे महाराजांचे शब्द. त्या दिवसापासून कोंढाण्याचं नाव सिंहगड झालं. गडावर तानाजींचं स्मारक आहे. १७०० मध्ये छत्रपती राजाराम महाराजांचं निधन याच गडावर झालं.',
      'पुण्यापासून जवळ असल्याने पुणेकरांचा हा रविवारचा किल्ला आहे. पुणे दरवाजा, कल्याण दरवाजा, देवटाके, टिळकांचा बंगला आणि गडावरची पिठलं भाकरी आणि दही कांदा, हे सगळं सिंहगडाचा भाग आहे.',
    ],
    hen: [
      'The old name was Kondhana. Under the treaty of Purandar (1665) the fort had to be handed to the Mughals. To win it back, on the night of 4 February 1670 Tanaji Malusare and his men climbed the Donagiri cliff. Tanaji fell in the fight with Udaybhan Rathod, but the fort was won.',
      '"The fort is won, but the lion is lost," said Shivaji Maharaj, and Kondhana became Sinhagad. Tanaji’s memorial stands on the fort. Chhatrapati Rajaram Maharaj died here in 1700.',
      'Being so close to Pune, it is the city’s Sunday fort. The Pune and Kalyan gates, the Dev take tank, Tilak’s bungalow, and pithla bhakri with dahi kanda at the top are all part of a Sinhagad visit.',
    ],
    facts: [['उंची', 'सुमारे १३१२ मीटर'], ['जवळचं शहर', 'पुणे, ३० किमी'], ['जायचं कसं', 'गाडी वरपर्यंत जाते; किंवा पायी दीड तास'], ['कधी जावं', 'वर्षभर; पावसाळ्यात सर्वात सुंदर']] },
  { cat: 'kille', mr: 'प्रतापगड', en: 'Pratapgad', lon: 73.58, lat: 17.94, dist: 'सातारा',
    tmr: '१६५९ मध्ये अफझलखानाचा वध इथे झाला. गडावर भवानी मातेचं मंदिर आहे. महाबळेश्वरजवळ.',
    ten: 'The fort of the Afzal Khan encounter in 1659. The Bhavani temple is on the fort. Near Mahabaleshwar.',
    hmr: [
      'जावळीचं खोरं ताब्यात आल्यावर १६५६ मध्ये शिवाजी महाराजांनी मोरोपंत पिंगळ्यांकडून हा नवा किल्ला बांधून घेतला. पार घाटावर नजर ठेवणं हा त्याचा हेतू होता.',
      '१० नोव्हेंबर १६५९ रोजी गडाच्या पायथ्याशी अफझलखानाची भेट झाली. खानाने दगा केला आणि महाराजांनी वाघनखांनी त्याचा वध केला. त्यानंतर जिवा महालाने सय्यद बंडाचा वार अडवला, म्हणून "होता जिवा म्हणून वाचला शिवा" ही म्हण आली. लगेच मावळ्यांनी खानाच्या फौजेचा पराभव केला.',
      'गडावरची भवानी माता महाराजांची आराध्य देवता. नेपाळमधून आणलेल्या गंडकी शिळेतून ही मूर्ती घडवली आहे असं सांगतात. १९५७ मध्ये पंडित नेहरूंच्या हस्ते गडावर महाराजांचा अश्वारूढ पुतळा बसवला. पायथ्याशी अफझलखानाची कबर आहे.',
    ],
    hen: [
      'Once the Javli valley was in his hands, Shivaji Maharaj had this new fort built in 1656 by Moropant Pingle, to watch over the Par ghat.',
      'On 10 November 1659 Afzal Khan met Shivaji Maharaj at the foot of the fort. The Khan struck treacherously and Maharaj killed him with the waghnakh, the tiger claws. Jiva Mahala then blocked a blow from Sayyid Banda, which gave Marathi the saying "hota Jiva mhanun vachla Shiva". The Khan’s army was routed straight after.',
      'The Bhavani on the fort was the goddess Maharaj worshipped; the idol is said to be carved from Gandaki stone brought from Nepal. In 1957 Pandit Nehru unveiled the statue of Maharaj on horseback here. Afzal Khan’s tomb is at the foot of the fort.',
    ],
    facts: [['उंची', 'सुमारे १०८० मीटर'], ['जवळचं शहर', 'महाबळेश्वर, २४ किमी'], ['जायचं कसं', 'गाडी वरपर्यंत जाते'], ['कधी जावं', 'वर्षभर; पावसाळ्यात धुकं']] },
  { cat: 'kille', mr: 'शिवनेरी', en: 'Shivneri', lon: 73.86, lat: 19.20, dist: 'पुणे (जुन्नर)',
    tmr: 'शिवाजी महाराजांचं जन्मस्थान. १९ फेब्रुवारी १६३० रोजी इथे त्यांचा जन्म झाला.',
    ten: 'The birthplace of Shivaji Maharaj, born here on 19 February 1630.',
    hmr: [
      'जुन्नर हे प्राचीन व्यापारी शहर आणि शिवनेरी त्याचा किल्ला. सातवाहन काळापासून इथे लेणी आहेत. पुढे यादव, बहामनी आणि निजामशाही अशा राजवटी इथे होत्या. १५९५ मध्ये मालोजी भोसल्यांना, म्हणजे शिवाजी महाराजांच्या आजोबांना, शिवनेरी आणि चाकण जहागिरीत मिळाले.',
      'शहाजीराजे लढाईत गुंतलेले असताना जिजाऊंनी या सुरक्षित किल्ल्यावर आसरा घेतला. १९ फेब्रुवारी १६३० रोजी इथे शिवाजी महाराजांचा जन्म झाला. गडावरच्या शिवाई देवीवरून त्यांचं नाव शिवाजी ठेवलं.',
      'गडाला सात दरवाजे आहेत. वर शिवजन्मस्थानाची इमारत, बदामी तलाव, गंगा जमुना टाकी आणि जिजाऊंसह बाल शिवाजीचा पुतळा आहे. जवळच लेण्याद्रीचा गिरिजात्मज गणपती आहे. दरवर्षी शिवजयंतीला इथे मोठा उत्सव होतो.',
    ],
    hen: [
      'Junnar was an ancient trading town and Shivneri was its fort. There are rock cut caves here from the Satavahana age, and later the Yadavas, the Bahmanis and the Nizamshahi ruled it. In 1595 Maloji Bhosale, Shivaji Maharaj’s grandfather, was given Shivneri and Chakan as his jagir.',
      'While Shahaji Raje was away at war, Jijau took shelter on this safe fort, and on 19 February 1630 Shivaji Maharaj was born here. He was named after Shivai Devi, whose temple is on the fort.',
      'The fort has seven gates. On top are the birthplace building, the Badami tank, the Ganga Jamuna cisterns and a statue of young Shivaji with Jijau. The Girijatmaj Ganpati of Lenyadri is close by. A big festival is held here every Shiv Jayanti.',
    ],
    facts: [['उंची', 'सुमारे १०७० मीटर'], ['जवळचं शहर', 'जुन्नर, २ किमी; पुण्यापासून ९५ किमी'], ['जायचं कसं', 'पायऱ्या, सुमारे एक तास'], ['कधी जावं', 'सप्टेंबर ते मार्च; १९ फेब्रुवारीला उत्सव']] },
  { cat: 'kille', mr: 'तोरणा', en: 'Torna', lon: 73.62, lat: 18.28, dist: 'पुणे', dx: -8,
    tmr: 'महाराजांनी वयाच्या सोळाव्या वर्षी जिंकलेला पहिला किल्ला. पुणे जिल्ह्यातला सर्वात उंच किल्ला.',
    ten: 'The first fort Shivaji Maharaj won, at sixteen. The highest fort in Pune district.',
    hmr: [
      '१६४६ मध्ये, वयाच्या सोळाव्या वर्षी, शिवाजी महाराजांनी आदिलशाहीकडून हा किल्ला घेतला. स्वराज्याचा हा पहिला किल्ला, म्हणून त्याला स्वराज्याचं तोरण म्हणतात. गडाची डागडुजी करताना सापडलेल्या धनातून राजगड बांधला, अशी गोष्ट आहे.',
      'गडाच्या विस्तारामुळे त्याला प्रचंडगड असंही म्हणतात. झुंजार माची आणि बुधला माची या दोन माच्या, बिनी दरवाजा, कोठी दरवाजा आणि वर मेंघाई देवीचं मंदिर आहे. पावसाळ्यानंतर गडावर रानफुलं फुलतात.',
      'संभाजी महाराजांच्या मृत्यूनंतर १७०४ मध्ये औरंगजेबाने हा किल्ला घेतला आणि फुतुहुल्गैब असं नाव दिलं. पुढच्याच वर्षी शंकराजी नारायण यांनी तो परत जिंकला. पुणे जिल्ह्यातला हा सर्वात उंच किल्ला आहे.',
    ],
    hen: [
      'In 1646, at sixteen, Shivaji Maharaj took this fort from the Adilshahi. It was the first fort of Swarajya, so it is called the torana, the welcome arch, of Swarajya. The story goes that treasure found while repairing it paid for building Rajgad.',
      'Its sheer size earned it the name Prachandagad. It has two machis, Zunjar and Budhla, the Bini and Kothi gates, and the Menghai Devi temple on top. After the monsoon the fort is covered in wild flowers.',
      'After Sambhaji Maharaj’s death Aurangzeb took the fort in 1704 and named it Futuhulgaib. Shankaraji Narayan won it back the very next year. It is the highest fort in Pune district.',
    ],
    facts: [['उंची', 'सुमारे १४०३ मीटर'], ['जवळचं गाव', 'वेल्हे, पुण्यापासून ६० किमी'], ['जायचं कसं', 'पायी, ३ तासांचा खडा ट्रेक'], ['कधी जावं', 'ऑक्टोबर ते फेब्रुवारी']] },
  { cat: 'kille', mr: 'पन्हाळा', en: 'Panhala', lon: 74.11, lat: 16.81, dist: 'कोल्हापूर',
    tmr: '१६६० मध्ये सिद्दी जौहरच्या वेढ्यातून महाराज इथूनच निसटले. बाजीप्रभूंची पावनखिंड जवळच आहे.',
    ten: 'Shivaji Maharaj escaped the siege of 1660 from here. Baji Prabhu’s Pavan Khind is close by.',
    hmr: [
      'महाराष्ट्रातल्या सर्वात जुन्या आणि मोठ्या किल्ल्यांपैकी एक. शिलाहार राजा भोज दुसरा याने ११७८ ते १२०९ या काळात हा किल्ला बांधला. पुढे यादव, बहामनी आणि आदिलशाही राजवटी इथे होत्या. अफझलखानाच्या वधानंतर १६५९ मध्ये शिवाजी महाराजांनी तो घेतला.',
      '१६६० मध्ये सिद्दी जौहरने चार महिने गडाला वेढा घातला. १३ जुलैच्या पावसाळी रात्री महाराज सहाशे मावळ्यांसह विशाळगडाकडे निसटले. शिवा काशीद हा न्हावी महाराजांसारखा वेश करून पालखीत बसला आणि शत्रूला फसवलं. घोडखिंडीत बाजीप्रभू देशपांड्यांनी शत्रूला अडवून धरलं आणि महाराज सुरक्षित पोहोचल्याच्या तोफा ऐकूनच प्राण सोडले. तेव्हापासून ती पावनखिंड.',
      '१६७३ मध्ये कोंडाजी फर्जंदाने फक्त साठ मावळ्यांसह गड परत जिंकला. पुढे महाराणी ताराबाईंनी इथून कोल्हापूरचं राज्य चालवलं. आज सज्जा कोठी, तीन दरवाजा, अंधार बाव आणि अंबरखान्याची धान्य कोठारं पाहायला मिळतात. पन्हाळा हे थंड हवेचं ठिकाणही आहे.',
    ],
    hen: [
      'One of the oldest and largest forts in Maharashtra, built between 1178 and 1209 by the Shilahara king Bhoja II. The Yadavas, the Bahmanis and the Adilshahi held it after him. Shivaji Maharaj took it in 1659, soon after the Afzal Khan episode.',
      'In 1660 Siddi Johar laid siege for four months. On the rainy night of 13 July, Maharaj slipped out with six hundred men towards Vishalgad. Shiva Kashid, a barber who looked like him, rode in the palanquin to fool the pursuers. At Ghodkhind, Baji Prabhu Deshpande held the pass and died only after hearing the cannon that meant Maharaj was safe. The pass has been Pavan Khind, the sacred pass, ever since.',
      'In 1673 Kondaji Farzand won the fort back with just sixty men. Later Maharani Tarabai ruled the Kolhapur state from here. Today you can see Sajja Kothi, the Teen Darwaza, the Andhar Bav well and the great Ambarkhana granaries. Panhala is a hill station too.',
    ],
    facts: [['उंची', 'सुमारे ८४५ मीटर'], ['जवळचं शहर', 'कोल्हापूर, २० किमी'], ['जायचं कसं', 'गाडी वरपर्यंत जाते'], ['कधी जावं', 'वर्षभर; १३ जुलैला पावनखिंड पदयात्रा']] },
  { cat: 'kille', mr: 'सिंधुदुर्ग', en: 'Sindhudurg', lon: 73.46, lat: 16.04, dist: 'सिंधुदुर्ग (मालवण)',
    tmr: 'मालवणच्या समुद्रात महाराजांनी बांधलेला जलदुर्ग. इथे शिवाजी महाराजांचं मंदिर आहे.',
    ten: 'A sea fort built by Shivaji Maharaj off Malvan. It has a temple of Shivaji Maharaj himself.',
    hmr: [
      'समुद्रावर ज्याचं राज्य त्याचं किनाऱ्यावर, हे ओळखून शिवाजी महाराजांनी आरमार उभं केलं. मालवणजवळच्या कुरटे बेटावर १६६४ मध्ये या किल्ल्याचा पाया घातला आणि १६६७ मध्ये तो पूर्ण झाला. हिरोजी इंदुलकरांनी काम पाहिलं. पायात शिसं ओतलं, अशी नोंद आहे.',
      'सुमारे अठ्ठेचाळीस एकरांचा किल्ला, तीन किलोमीटर लांब आणि नऊ मीटर उंच तटबंदी, बेचाळीस बुरूज. समुद्राच्या मधोमध असूनही गडावर गोड्या पाण्याच्या विहिरी आहेत. चुन्यात उमटलेले महाराजांचे हाताचे आणि पायाचे ठसे इथे जपले आहेत.',
      '१६९५ मध्ये राजाराम महाराजांनी गडावर शिवराजेश्वर मंदिर बांधलं. शिवाजी महाराजांची मूर्ती असलेलं हे एकमेव मंदिर. पुढे कान्होजी आंग्र्यांचं आरमार याच किनाऱ्यावर गाजलं. मालवणच्या धक्क्यावरून होडीने दहा मिनिटांत गडावर जाता येतं.',
    ],
    hen: [
      'Whoever rules the sea rules the coast: knowing this, Shivaji Maharaj built a navy. The foundation of this fort on Kurte island near Malvan was laid in 1664 and it was finished in 1667, with Hiroji Indulkar in charge. Records say lead was poured into the foundations.',
      'The fort covers about 48 acres, with three kilometres of walls nine metres high and 42 bastions. Though it stands in the sea, it has wells of sweet water. Impressions of Maharaj’s hand and foot in lime are preserved here.',
      'In 1695 Rajaram Maharaj built the Shivrajeshwar temple on the fort, the only temple with an idol of Shivaji Maharaj. Later Kanhoji Angre’s navy made this coast famous. A ten minute boat ride from the Malvan jetty takes you to the fort.',
    ],
    facts: [['उंची', 'समुद्रसपाटीवर, बेटावर'], ['जवळचं शहर', 'मालवण, होडीने १० मिनिटं'], ['जायचं कसं', 'मालवण धक्क्यावरून होडी'], ['कधी जावं', 'ऑक्टोबर ते मे; पावसाळ्यात होड्या बंद']] },

  // ---------- संत आणि युगपुरुष ----------
  { cat: 'yugpurush', mr: 'संत ज्ञानेश्वर', en: 'Sant Dnyaneshwar', lon: 73.90, lat: 18.68, dist: 'आळंदी, पुणे',
    tmr: 'वयाच्या सोळाव्या वर्षी ज्ञानेश्वरी लिहिली (१२९०). आळंदीला संजीवन समाधी. आषाढी वारीची पालखी इथून निघते.',
    ten: 'Wrote the Dnyaneshwari in Marathi at sixteen (1290). His samadhi is at Alandi, where the Ashadhi wari begins.' },
  { cat: 'yugpurush', mr: 'संत तुकाराम', en: 'Sant Tukaram', lon: 73.77, lat: 18.72, dist: 'देहू, पुणे', dx: -8,
    tmr: 'इंद्रायणीकाठी देहूचे संत. त्यांचे अभंग आजही घराघरात म्हटले जातात.',
    ten: 'The saint of Dehu on the Indrayani. His abhangs are still sung in Marathi homes every day.' },
  { cat: 'yugpurush', mr: 'राजमाता जिजाऊ', en: 'Rajmata Jijau', lon: 76.11, lat: 19.95, dist: 'सिंदखेड राजा, बुलढाणा',
    tmr: 'शिवाजी महाराजांच्या आई. १५९८ मध्ये सिंदखेड राजा इथे जन्म. स्वराज्याचं स्वप्न त्यांनीच दिलं.',
    ten: 'Mother of Shivaji Maharaj, born at Sindkhed Raja in 1598. The dream of Swarajya began with her.' },
  { cat: 'yugpurush', mr: 'छत्रपती शिवाजी महाराज', en: 'Chhatrapati Shivaji Maharaj', lon: 73.86, lat: 19.20, dist: 'शिवनेरी, पुणे',
    tmr: 'स्वराज्याचे संस्थापक. १६३० मध्ये शिवनेरीवर जन्म, १६७४ मध्ये रायगडावर राज्याभिषेक.',
    ten: 'Founder of Swarajya. Born on Shivneri in 1630, crowned at Raigad in 1674.' },
  { cat: 'yugpurush', mr: 'अहिल्याबाई होळकर', en: 'Ahilyabai Holkar', lon: 75.30, lat: 18.73, dist: 'चौंडी, अहिल्यानगर',
    tmr: 'चौंडी गावात १७२५ मध्ये जन्म. माळव्याच्या राणी. काशी विश्वनाथासह देशभर मंदिरं आणि घाट बांधले.',
    ten: 'Born in Chondi in 1725. Queen of Malwa. Rebuilt temples and ghats across India, including Kashi Vishwanath.' },
  { cat: 'yugpurush', mr: 'महात्मा फुले आणि सावित्रीबाई फुले', en: 'Jyotiba and Savitribai Phule', lon: 73.86, lat: 18.52, dist: 'पुणे',
    tmr: '१८४८ मध्ये पुण्यात मुलींची पहिली शाळा सुरू केली. सावित्रीबाई पहिल्या महिला शिक्षिका.',
    ten: 'Started the first school for girls in Pune in 1848. Savitribai was India’s first woman teacher.' },
  { cat: 'yugpurush', mr: 'लोकमान्य टिळक', en: 'Lokmanya Tilak', lon: 73.31, lat: 16.99, dist: 'रत्नागिरी',
    tmr: 'रत्नागिरीत १८५६ मध्ये जन्म. "स्वराज्य हा माझा जन्मसिद्ध हक्क आहे." सार्वजनिक गणेशोत्सव त्यांनी सुरू केला.',
    ten: 'Born in Ratnagiri in 1856. "Swarajya is my birthright." He started the public Ganeshotsav.' },
  { cat: 'yugpurush', mr: 'राजर्षी शाहू महाराज', en: 'Rajarshi Shahu Maharaj', lon: 74.24, lat: 16.70, dist: 'कोल्हापूर',
    tmr: 'कोल्हापूरचे राजे. १९०२ मध्ये मागास वर्गांसाठी आरक्षण दिलं. शिक्षणासाठी वसतिगृहं बांधली.',
    ten: 'King of Kolhapur. Gave reservation to backward classes in 1902 and built hostels so everyone could study.' },
  { cat: 'yugpurush', mr: 'डॉ. बाबासाहेब आंबेडकर', en: 'Dr Babasaheb Ambedkar', lon: 79.07, lat: 21.13, dist: 'दीक्षाभूमी, नागपूर',
    tmr: 'भारतीय संविधानाचे शिल्पकार. १९५६ मध्ये नागपूरच्या दीक्षाभूमीवर लाखो लोकांसह बौद्ध धर्म स्वीकारला.',
    ten: 'Architect of India’s Constitution. Embraced Buddhism with lakhs of followers at Dikshabhoomi, Nagpur, in 1956.' },

  // ---------- देवस्थाने ----------
  { cat: 'devasthan', mr: 'अष्टविनायक', en: 'Ashtavinayak', lon: 74.32, lat: 18.28, dist: 'पुणे आणि रायगड',
    tmr: 'पुण्याभोवतीची आठ गणपती मंदिरं: मोरगाव, सिद्धटेक, पाली, महड, थेऊर, लेण्याद्री, ओझर, रांजणगाव.',
    ten: 'Eight Ganpati temples around Pune: Morgaon, Siddhatek, Pali, Mahad, Theur, Lenyadri, Ozar and Ranjangaon.' },
  { cat: 'devasthan', mr: 'पंढरपूर विठोबा', en: 'Pandharpur', lon: 75.33, lat: 17.68, dist: 'सोलापूर',
    tmr: 'चंद्रभागेकाठचा विठोबा. आषाढी आणि कार्तिकी वारीला लाखो वारकरी पायी येतात.',
    ten: 'Vithoba on the Chandrabhaga. Lakhs of warkaris walk here for the Ashadhi and Kartiki wari.' },
  { cat: 'devasthan', mr: 'तुळजापूर भवानी', en: 'Tuljapur Bhavani', lon: 76.07, lat: 18.01, dist: 'धाराशिव',
    tmr: 'अनेक मराठी घरांची कुलदेवी. शिवाजी महाराजांची आराध्य देवता.',
    ten: 'The family goddess of many Marathi homes, and the goddess Shivaji Maharaj worshipped.' },
  { cat: 'devasthan', mr: 'कोल्हापूर महालक्ष्मी', en: 'Kolhapur Mahalakshmi', lon: 74.24, lat: 16.70, dist: 'कोल्हापूर',
    tmr: 'अंबाबाईचं मंदिर, साडेतीन शक्तिपीठांपैकी एक. वर्षातून दोनदा सूर्यकिरण थेट मूर्तीवर पडतात (किरणोत्सव).',
    ten: 'The Ambabai temple, one of the Shakti Peeths. Twice a year the sun’s rays fall directly on the idol.' },
  { cat: 'devasthan', mr: 'शिर्डी साईबाबा', en: 'Shirdi', lon: 74.48, lat: 19.77, dist: 'अहिल्यानगर',
    tmr: 'साईबाबांचं समाधी मंदिर. "सबका मालिक एक." देशभरातून भक्त येतात.',
    ten: 'The samadhi temple of Sai Baba. Devotees come from all over India.' },
  { cat: 'devasthan', mr: 'जेजुरी खंडोबा', en: 'Jejuri', lon: 74.16, lat: 18.28, dist: 'पुणे', dy: -8,
    tmr: 'येळकोट येळकोट जय मल्हार! भंडाऱ्याने पिवळा झालेला डोंगर. सोमवती अमावास्येला मोठी यात्रा.',
    ten: 'Yelkot yelkot jai Malhar! The hill turns yellow with turmeric. A big fair on Somvati Amavasya.' },
  { cat: 'devasthan', mr: 'शेगाव गजानन महाराज', en: 'Shegaon', lon: 76.69, lat: 20.79, dist: 'बुलढाणा',
    tmr: 'गजानन महाराजांचं समाधी मंदिर (१९१०). स्वच्छता आणि शिस्तीसाठी देशभर ओळखलं जातं.',
    ten: 'The samadhi temple of Gajanan Maharaj (1910), known across India for its cleanliness and order.' },
  { cat: 'devasthan', mr: 'त्र्यंबकेश्वर', en: 'Trimbakeshwar', lon: 73.53, lat: 19.93, dist: 'नाशिक',
    tmr: 'बारा ज्योतिर्लिंगांपैकी एक. इथल्या ब्रह्मगिरी डोंगरात गोदावरी उगम पावते. कुंभमेळ्याचं स्थान.',
    ten: 'One of the twelve Jyotirlingas. The Godavari rises on the Brahmagiri hill here. A Kumbh Mela town.' },
  { cat: 'devasthan', mr: 'भीमाशंकर', en: 'Bhimashankar', lon: 73.53, lat: 19.07, dist: 'पुणे',
    tmr: 'ज्योतिर्लिंग आणि भीमा नदीचा उगम. आजूबाजूचं जंगल शेकरू या राज्यप्राण्यासाठी प्रसिद्ध.',
    ten: 'A Jyotirlinga and the source of the Bhima river. The forest around it is home to the shekru, the state animal.' },
  { cat: 'devasthan', mr: 'घृष्णेश्वर', en: 'Grishneshwar', lon: 75.17, lat: 20.03, dist: 'छत्रपती संभाजीनगर', dy: 8,
    tmr: 'वेरूळ लेण्यांजवळचं ज्योतिर्लिंग. अहिल्याबाई होळकरांनी हे मंदिर पुन्हा बांधलं.',
    ten: 'The Jyotirlinga next to the Ellora caves. Rebuilt by Ahilyabai Holkar.' },
  { cat: 'devasthan', mr: 'औंढा नागनाथ', en: 'Aundha Nagnath', lon: 77.04, lat: 19.54, dist: 'हिंगोली',
    tmr: 'ज्योतिर्लिंग. हेमाडपंती बांधणीचं सुंदर कोरीव मंदिर.',
    ten: 'A Jyotirlinga with a beautifully carved Hemadpanti temple.' },
  { cat: 'devasthan', mr: 'परळी वैजनाथ', en: 'Parli Vaijnath', lon: 76.53, lat: 18.85, dist: 'बीड',
    tmr: 'मराठवाड्यातलं ज्योतिर्लिंग. महाशिवरात्रीला मोठी यात्रा भरते.',
    ten: 'The Jyotirlinga of Marathwada. A large fair gathers here on Mahashivratri.' },

  // ---------- पर्यटन ----------
  { cat: 'paryatan', mr: 'अजिंठा लेणी', en: 'Ajanta Caves', lon: 75.70, lat: 20.55, dist: 'छत्रपती संभाजीनगर',
    tmr: 'दोन हजार वर्षांपूर्वीची बौद्ध लेणी आणि त्यांतली जगप्रसिद्ध चित्रं. युनेस्को जागतिक वारसा.',
    ten: 'Buddhist caves up to two thousand years old, famous for their paintings. A UNESCO World Heritage site.' },
  { cat: 'paryatan', mr: 'वेरूळ लेणी', en: 'Ellora Caves', lon: 75.18, lat: 20.03, dist: 'छत्रपती संभाजीनगर',
    tmr: 'बौद्ध, हिंदू आणि जैन अशी ३४ लेणी. एकाच खडकातून कोरलेलं कैलास मंदिर हे इथलं आश्चर्य.',
    ten: '34 Buddhist, Hindu and Jain caves. The Kailasa temple, carved from a single rock, is the wonder here.' },
  { cat: 'paryatan', mr: 'घारापुरी (एलिफंटा)', en: 'Elephanta Caves', lon: 72.93, lat: 18.96, dist: 'मुंबई',
    tmr: 'मुंबईजवळच्या बेटावरची शिवलेणी. त्रिमूर्तीची भव्य मूर्ती. गेटवेवरून बोटीने जाता येतं.',
    ten: 'Shiva caves on an island near Mumbai with the great Trimurti. A boat ride from the Gateway of India.' },
  { cat: 'paryatan', mr: 'कास पठार', en: 'Kaas Plateau', lon: 73.82, lat: 17.72, dist: 'सातारा',
    tmr: 'सप्टेंबर ऑक्टोबरमध्ये रानफुलांनी भरून जाणारं पठार. पश्चिम घाटाचा युनेस्को वारसा.',
    ten: 'A plateau that fills with wild flowers in September and October. Part of the Western Ghats World Heritage.' },
  { cat: 'paryatan', mr: 'लोणार सरोवर', en: 'Lonar Lake', lon: 76.51, lat: 19.98, dist: 'बुलढाणा',
    tmr: 'उल्का पडून तयार झालेलं खाऱ्या पाण्याचं सरोवर. जगातल्या मोजक्या अशा सरोवरांपैकी एक.',
    ten: 'A salt water lake formed by a meteorite. One of very few such lakes in the world.' },
  { cat: 'paryatan', mr: 'महाबळेश्वर', en: 'Mahabaleshwar', lon: 73.66, lat: 17.92, dist: 'सातारा', dx: 8,
    tmr: 'सह्याद्रीतलं थंड हवेचं ठिकाण. स्ट्रॉबेरी आणि कृष्णा नदीचा उगम. प्रतापगड जवळच.',
    ten: 'A cool hill station in the Sahyadris. Strawberries, and the source of the Krishna. Pratapgad is close by.' },
  { cat: 'paryatan', mr: 'ताडोबा', en: 'Tadoba', lon: 79.33, lat: 20.24, dist: 'चंद्रपूर',
    tmr: 'महाराष्ट्रातलं सर्वात जुनं आणि मोठं राष्ट्रीय उद्यान. वाघ दिसण्यासाठी प्रसिद्ध.',
    ten: 'The oldest and largest national park in Maharashtra, famous for tiger sightings.' },
  { cat: 'paryatan', mr: 'गणपतीपुळे', en: 'Ganpatipule', lon: 73.27, lat: 17.15, dist: 'रत्नागिरी',
    tmr: 'समुद्रकिनाऱ्यावरचं स्वयंभू गणपती मंदिर. कोकणातला शांत किनारा आणि हापूस आंब्याचा प्रदेश.',
    ten: 'A Ganpati temple right on the beach. A quiet Konkan coast, and the land of the hapus mango.' },
  { cat: 'paryatan', mr: 'तारकर्ली', en: 'Tarkarli', lon: 73.49, lat: 16.03, dist: 'सिंधुदुर्ग', dx: 8, dy: 6,
    tmr: 'नितळ पाण्याचा किनारा. स्कूबा डायव्हिंग आणि मालवणी जेवण. सिंधुदुर्ग किल्ला समोरच.',
    ten: 'A beach with clear water, scuba diving and Malvani food. Sindhudurg fort is just across the water.' },
  { cat: 'paryatan', mr: 'नाशिक', en: 'Nashik', lon: 73.79, lat: 19.99, dist: 'नाशिक',
    tmr: 'गोदावरीकाठचं पंचवटी. दर बारा वर्षांनी कुंभमेळा. आता द्राक्षं आणि वाईनसाठीही प्रसिद्ध.',
    ten: 'Panchavati on the Godavari, and the Kumbh Mela every twelve years. Now known for grapes and wine too.' },
];

// Simplified outline of Maharashtra as lon/lat points, clockwise from Dahanu.
// Good enough to recognise the state; swap for a district map when one is available.
window.LM_OUTLINE = [
  [72.72, 20.12], [72.95, 20.55], [73.35, 20.95], [73.85, 21.35], [74.05, 21.95], [74.55, 21.75],
  [75.10, 21.45], [75.65, 21.40], [76.05, 21.55], [76.60, 21.35], [77.10, 21.75], [77.70, 21.65],
  [78.30, 21.55], [78.95, 21.70], [79.50, 21.75], [80.10, 21.65], [80.55, 21.35], [80.90, 21.05],
  [80.60, 20.55], [80.40, 20.00], [80.85, 19.45], [80.40, 18.85], [79.95, 18.95], [79.55, 19.45],
  [79.00, 19.55], [78.35, 19.60], [78.05, 19.20], [77.85, 18.75], [77.55, 18.45], [77.10, 18.20],
  [76.85, 17.95], [76.45, 17.45], [76.05, 17.35], [75.65, 17.20], [75.35, 16.95], [75.05, 16.85],
  [74.65, 16.75], [74.55, 16.35], [74.30, 15.95], [74.05, 15.75], [73.70, 15.72], [73.63, 15.86],
  [73.47, 16.06], [73.30, 16.99], [73.19, 17.48], [73.18, 17.76], [73.02, 18.04], [72.96, 18.33],
  [72.87, 18.64], [72.83, 18.95], [72.80, 19.37],
];

// ---------- Journeys: routes the map animates stop by stop ----------
// Each stop: Marathi and English name, position, a short 'when' label and
// two plain lines. Order matters; the marker travels in this order.
window.LM_ROUTES = {
  shivaji: {
    mr: 'शिवरायांचा प्रवास', en: 'Shivaji Maharaj’s journey', icon: '🚩', color: '#a81607',
    imr: 'जन्मापासून राज्याभिषेकापर्यंत, सात किल्ल्यांची गोष्ट.',
    ien: 'From his birth to his coronation, told through seven forts.',
    stops: [
      { mr: 'शिवनेरी', en: 'Shivneri', lon: 73.86, lat: 19.20, when: '१६३०',
        tmr: 'इथे शिवाजी महाराजांचा जन्म झाला. जिजाऊंनी इथेच त्यांना रामायण, महाभारताच्या गोष्टी सांगितल्या.',
        ten: 'Shivaji Maharaj was born here. Jijau told him the stories of the Ramayana and Mahabharata on this fort.' },
      { mr: 'तोरणा', en: 'Torna', lon: 73.62, lat: 18.28, when: '१६४६',
        tmr: 'वयाच्या सोळाव्या वर्षी जिंकलेला पहिला किल्ला. स्वराज्याचं तोरण इथे बांधलं गेलं.',
        ten: 'The first fort he won, at sixteen. This is where Swarajya began.' },
      { mr: 'राजगड', en: 'Rajgad', lon: 73.68, lat: 18.25, when: '१६४८ ते १६७०',
        tmr: 'जवळपास पंचवीस वर्षं स्वराज्याची राजधानी. महाराजांचं बरंचसं आयुष्य इथे गेलं.',
        ten: 'The capital for about 25 years. Much of his life was lived on this fort.' },
      { mr: 'प्रतापगड', en: 'Pratapgad', lon: 73.58, lat: 17.94, when: '१६५९',
        tmr: 'अफझलखानाची भेट आणि त्याचा वध. स्वराज्यावरचं मोठं संकट इथे टळलं.',
        ten: 'The meeting with Afzal Khan and his end. A great danger to Swarajya passed here.' },
      { mr: 'पन्हाळा', en: 'Panhala', lon: 74.11, lat: 16.81, when: '१६६०',
        tmr: 'सिद्दी जौहरचा वेढा. पावसाळी रात्री महाराज इथून निसटले आणि बाजीप्रभूंनी पावनखिंड लढवली.',
        ten: 'The siege of Siddi Johar. He slipped out on a rainy night while Baji Prabhu held the pass at Pavan Khind.' },
      { mr: 'सिंधुदुर्ग', en: 'Sindhudurg', lon: 73.46, lat: 16.04, when: '१६६४ ते १६६७',
        tmr: 'समुद्रात बांधलेला किल्ला. स्वराज्याचं आरमार इथून उभं राहिलं.',
        ten: 'A fort built in the sea. The navy of Swarajya grew from here.' },
      { mr: 'रायगड', en: 'Raigad', lon: 73.44, lat: 18.23, when: '६ जून १६७४',
        tmr: 'राज्याभिषेक. शिवाजी महाराज छत्रपती झाले. १६८० मध्ये इथेच त्यांचं निधन झालं.',
        ten: 'The coronation. Shivaji Maharaj became Chhatrapati. He died on this fort in 1680.' },
    ],
  },
  ashtavinayak: {
    mr: 'अष्टविनायक यात्रा', en: 'The Ashtavinayak circuit', icon: '🙏', color: '#a86a00',
    imr: 'पुण्याभोवतीच्या आठ गणपतींची पारंपरिक फेरी, मोरगावपासून सुरू होऊन मोरगावलाच संपणारी.',
    ien: 'The traditional round of eight Ganpati temples around Pune, starting and ending at Morgaon.',
    stops: [
      { mr: 'मोरगाव, मयूरेश्वर', en: 'Morgaon', lon: 74.32, lat: 18.28, when: 'पहिला',
        tmr: 'यात्रेची सुरुवात आणि शेवट इथेच. कऱ्हा नदीकाठचं मोरया गोसावींचं गाव.',
        ten: 'The circuit starts and ends here, on the Karha river, the village of Morya Gosavi.' },
      { mr: 'सिद्धटेक, सिद्धिविनायक', en: 'Siddhatek', lon: 74.85, lat: 18.48, when: 'दुसरा',
        tmr: 'भीमा नदीकाठचा, उजव्या सोंडेचा गणपती. अहिल्याबाईंनी बांधलेलं मंदिर.',
        ten: 'On the Bhima river, the Ganpati with the trunk to the right. The temple was built by Ahilyabai.' },
      { mr: 'पाली, बल्लाळेश्वर', en: 'Pali', lon: 73.28, lat: 18.55, when: 'तिसरा',
        tmr: 'भक्त बल्लाळाच्या नावाने ओळखला जाणारा एकमेव गणपती. सरसगड किल्ल्याच्या पायथ्याशी.',
        ten: 'The only Ganpati known by a devotee’s name, Ballal. At the foot of Sarasgad fort.' },
      { mr: 'महड, वरदविनायक', en: 'Mahad', lon: 73.30, lat: 18.80, when: 'चौथा',
        tmr: 'इथला नंदादीप १८९२ पासून अखंड तेवत आहे असं सांगतात.',
        ten: 'The lamp here is said to have burned without a break since 1892.' },
      { mr: 'थेऊर, चिंतामणी', en: 'Theur', lon: 74.02, lat: 18.52, when: 'पाचवा',
        tmr: 'मुळा मुठा नदीकाठी. थोरले माधवराव पेशवे यांचं आवडतं देवस्थान.',
        ten: 'On the Mula Mutha river. The favourite temple of Peshwa Madhavrao.' },
      { mr: 'लेण्याद्री, गिरिजात्मज', en: 'Lenyadri', lon: 73.88, lat: 19.24, when: 'सहावा',
        tmr: 'डोंगरातल्या बौद्ध लेण्यांमध्ये वसलेला गणपती. साडेतीनशे पायऱ्या चढून जावं लागतं.',
        ten: 'A Ganpati inside ancient rock cut caves on a hill. About 350 steps up.' },
      { mr: 'ओझर, विघ्नहर', en: 'Ozar', lon: 73.95, lat: 19.30, when: 'सातवा',
        tmr: 'कुकडी नदीकाठचा विघ्नहर्ता. सोन्याचा कळस असलेलं मंदिर.',
        ten: 'The remover of obstacles, on the Kukadi river. The temple has a golden spire.' },
      { mr: 'रांजणगाव, महागणपती', en: 'Ranjangaon', lon: 74.23, lat: 18.75, when: 'आठवा',
        tmr: 'पुणे नगर रस्त्यावरचा महागणपती. इथून पुन्हा मोरगावला जाऊन यात्रा पूर्ण होते.',
        ten: 'Mahaganpati on the Pune to Nagar road. From here the circuit returns to Morgaon.' },
      { mr: 'मोरगाव', en: 'Back to Morgaon', lon: 74.32, lat: 18.28, when: 'समाप्ती',
        tmr: 'अष्टविनायक यात्रा पूर्ण. गणपती बाप्पा मोरया!',
        ten: 'The Ashtavinayak circuit is complete. Ganpati Bappa Morya!' },
    ],
  },
  wari: {
    mr: 'आषाढी वारी', en: 'The Ashadhi wari to Pandharpur', icon: '🎶', color: '#c2470a', marker: 'procession',
    imr: 'देहू आणि आळंदीहून पंढरपूरपर्यंत, सुमारे अठरा दिवसांची पायी वारी.',
    ien: 'From Dehu and Alandi to Pandharpur, about eighteen days on foot. Day numbers are approximate.',
    stops: [
      { mr: 'देहू', en: 'Dehu', lon: 73.77, lat: 18.72, when: 'दिवस १',
        tmr: 'तुकाराम महाराजांची पालखी इथून निघते. गावभर टाळ मृदंगाचा गजर.',
        ten: 'Tukaram Maharaj\u2019s palkhi sets out from here, to the sound of taal and mridang.' },
      { mr: 'आळंदी', en: 'Alandi', lon: 73.90, lat: 18.68, when: 'दिवस २',
        tmr: 'दुसऱ्या दिवशी ज्ञानेश्वर माउलींची पालखी निघते. लाखो वारकरी, एकच गजर: ज्ञानोबा माउली तुकाराम!',
        ten: 'The next day Dnyaneshwar Mauli\u2019s palkhi leaves Alandi. Lakhs of warkaris, one chant: Dnyanoba Mauli Tukaram.' },
      { mr: 'पुणे', en: 'Pune', lon: 73.86, lat: 18.52, when: 'दिवस २ ते ४',
        tmr: 'दोन्ही पालख्या पुण्यात मुक्काम करतात. शहर वारकऱ्यांचं स्वागत करतं आणि जेवण घालतं.',
        ten: 'Both palkhis rest in Pune. The city welcomes the warkaris and feeds them.' },
      { mr: 'सासवड', en: 'Saswad', lon: 74.03, lat: 18.35, when: 'दिवस ५',
        tmr: 'दिवे घाट चढून सासवड. संत सोपानदेवांची समाधी इथे आहे.',
        ten: 'Up the Dive ghat to Saswad, where Sant Sopandev\u2019s samadhi is.' },
      { mr: 'जेजुरी', en: 'Jejuri', lon: 74.16, lat: 18.28, when: 'दिवस ७',
        tmr: 'खंडोबाच्या जेजुरीत मुक्काम. भंडाऱ्याने पिवळा झालेला डोंगर.',
        ten: 'A halt at Khandoba\u2019s Jejuri, the hill yellow with turmeric.' },
      { mr: 'लोणंद', en: 'Lonand', lon: 74.19, lat: 18.04, when: 'दिवस ९',
        tmr: 'इथून पुढे चांदोबाच्या लिंबाजवळ पहिलं उभं रिंगण. माउलींचा अश्व वारकऱ्यांच्या रांगांमधून धावतो.',
        ten: 'Just beyond, near Chandobacha Limb, the first standing ringan: Mauli\u2019s horse runs between the lines of warkaris.' },
      { mr: 'फलटण', en: 'Phaltan', lon: 74.43, lat: 17.99, when: 'दिवस १२',
        tmr: 'फलटणचा मुक्काम. दिंड्या, पखवाज, फुगड्या आणि संध्याकाळी कीर्तन.',
        ten: 'The halt at Phaltan. Dindis, pakhwaj and phugadi, and kirtan in the evening.' },
      { mr: 'माळशिरस', en: 'Malshiras', lon: 74.90, lat: 17.86, when: 'दिवस १५',
        tmr: 'सोलापूर जिल्ह्यात प्रवेश. सदाशिवनगरजवळ गोल रिंगण.',
        ten: 'Into Solapur district. The round ringan near Sadashivnagar.' },
      { mr: 'वाखरी', en: 'Wakhari', lon: 75.28, lat: 17.70, when: 'दिवस १८',
        tmr: 'पंढरपूरच्या वेशीवर सगळ्या पालख्या एकत्र येतात. शेवटचं रिंगण.',
        ten: 'At the gates of Pandharpur all the palkhis come together for the last ringan.' },
      { mr: 'पंढरपूर', en: 'Pandharpur', lon: 75.33, lat: 17.68, when: 'आषाढी एकादशी',
        tmr: 'चंद्रभागेत स्नान आणि विठोबाचं दर्शन. वारी पूर्ण. विठ्ठल विठ्ठल!',
        ten: 'A dip in the Chandrabhaga and darshan of Vithoba. The wari is complete. Vitthal Vitthal!' },
    ],
  },
};

// ---------- Quiz: five questions are picked at random from this list ----------
// answer is the position of the right option, counting from 0.
window.LM_QUIZ = [
  { qmr: 'शिवाजी महाराजांचा जन्म कोणत्या किल्ल्यावर झाला?', qen: 'On which fort was Shivaji Maharaj born?',
    options: [['शिवनेरी', 'Shivneri'], ['रायगड', 'Raigad'], ['तोरणा', 'Torna']], answer: 0,
    wmr: '१९ फेब्रुवारी १६३० रोजी शिवनेरीवर.', wen: 'On Shivneri, on 19 February 1630.' },
  { qmr: '१६७४ मध्ये शिवाजी महाराजांचा राज्याभिषेक कुठे झाला?', qen: 'Where was Shivaji Maharaj crowned in 1674?',
    options: [['प्रतापगड', 'Pratapgad'], ['रायगड', 'Raigad'], ['राजगड', 'Rajgad']], answer: 1,
    wmr: 'रायगडावर, ६ जून १६७४ रोजी.', wen: 'At Raigad, on 6 June 1674.' },
  { qmr: 'ज्ञानेश्वरी कोणी लिहिली?', qen: 'Who wrote the Dnyaneshwari?',
    options: [['संत तुकाराम', 'Sant Tukaram'], ['संत एकनाथ', 'Sant Eknath'], ['संत ज्ञानेश्वर', 'Sant Dnyaneshwar']], answer: 2,
    wmr: 'संत ज्ञानेश्वरांनी, वयाच्या सोळाव्या वर्षी.', wen: 'Sant Dnyaneshwar, when he was sixteen.' },
  { qmr: 'महाराष्ट्र दिन कधी असतो?', qen: 'When is Maharashtra Din?',
    options: [['१ मे', '1 May'], ['१५ ऑगस्ट', '15 August'], ['२६ जानेवारी', '26 January']], answer: 0,
    wmr: '१ मे १९६० रोजी महाराष्ट्र राज्य स्थापन झालं.', wen: 'The state was formed on 1 May 1960.' },
  { qmr: 'पंढरपूरचा देव कोणता?', qen: 'Which god is worshipped at Pandharpur?',
    options: [['खंडोबा', 'Khandoba'], ['विठोबा', 'Vithoba'], ['गणपती', 'Ganpati']], answer: 1,
    wmr: 'विठोबा. वारकरी दरवर्षी पायी पंढरपूरला जातात.', wen: 'Vithoba. Warkaris walk to Pandharpur every year.' },
  { qmr: 'अष्टविनायक म्हणजे किती गणपती?', qen: 'How many Ganpati temples make the Ashtavinayak?',
    options: [['पाच', 'Five'], ['बारा', 'Twelve'], ['आठ', 'Eight']], answer: 2,
    wmr: 'आठ. अष्ट म्हणजे आठ.', wen: 'Eight. Ashta means eight.' },
  { qmr: 'महाराष्ट्राचा राज्यप्राणी कोणता?', qen: 'What is the state animal of Maharashtra?',
    options: [['शेकरू', 'Shekru, the giant squirrel'], ['वाघ', 'Tiger'], ['हत्ती', 'Elephant']], answer: 0,
    wmr: 'शेकरू. भीमाशंकरच्या जंगलात दिसतं.', wen: 'The shekru, the Indian giant squirrel. You can see it in the Bhimashankar forest.' },
  { qmr: 'एकाच खडकातून कोरलेलं कैलास मंदिर कुठे आहे?', qen: 'Where is the Kailasa temple, carved from a single rock?',
    options: [['अजिंठा', 'Ajanta'], ['वेरूळ', 'Ellora'], ['घारापुरी', 'Elephanta']], answer: 1,
    wmr: 'वेरूळ लेण्यांमध्ये.', wen: 'In the Ellora caves.' },
  { qmr: 'मुलींसाठी पहिली शाळा कोणी सुरू केली?', qen: 'Who started the first school for girls?',
    options: [['लोकमान्य टिळक', 'Lokmanya Tilak'], ['महात्मा आणि सावित्रीबाई फुले', 'Jyotiba and Savitribai Phule'], ['शाहू महाराज', 'Shahu Maharaj']], answer: 1,
    wmr: 'फुले दांपत्याने, १८४८ मध्ये पुण्यात.', wen: 'The Phules, in Pune in 1848.' },
  { qmr: '"गड आला पण सिंह गेला" हे वाक्य कोणत्या किल्ल्याबद्दल आहे?', qen: '"The fort is won, but the lion is lost" is said about which fort?',
    options: [['सिंहगड', 'Sinhagad'], ['पन्हाळा', 'Panhala'], ['सिंधुदुर्ग', 'Sindhudurg']], answer: 0,
    wmr: 'सिंहगड. तानाजी मालुसरे तिथे धारातीर्थी पडले.', wen: 'Sinhagad, where Tanaji Malusare fell.' },
  { qmr: 'महाराष्ट्राची राजधानी कोणती?', qen: 'What is the capital of Maharashtra?',
    options: [['पुणे', 'Pune'], ['नागपूर', 'Nagpur'], ['मुंबई', 'Mumbai']], answer: 2,
    wmr: 'मुंबई. नागपूर ही उपराजधानी आहे.', wen: 'Mumbai. Nagpur is the second capital.' },
  { qmr: 'महाराष्ट्राचं राज्यफूल कोणतं?', qen: 'What is the state flower of Maharashtra?',
    options: [['गुलाब', 'Rose'], ['जारूळ', 'Jarul'], ['कमळ', 'Lotus']], answer: 1,
    wmr: 'जारूळ, जांभळ्या फुलांचं झाड.', wen: 'Jarul, the tree with purple flowers.' },
];
