#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# BrainSpark — one-click start for macOS.
#
# Double-click this file in Finder. It sets the machine up on first run and
# boots straight to the app on every run after that.
#
# The house rule applies to this script too: it says what it cannot do rather
# than failing quietly. If Node is missing, if the CAD engine is not installed,
# if no Anthropic key is configured — it tells you, in those words, instead of
# starting something half-working and letting you find out later.
#
# Stop the app with Ctrl-C, or just close the Terminal window.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# Finder starts scripts in your home directory, not the script's folder.
cd "${0%/*}" 2>/dev/null || cd "$(dirname "$0")"

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
YELLOW=$'\033[33m'; GOLD=$'\033[38;5;178m'; OFF=$'\033[0m'
say()  { printf '%s\n' "$*"; }
step() { printf '\n%s▸ %s%s\n' "$BOLD" "$*" "$OFF"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$OFF" "$*"; }
note() { printf '  %s•%s %s\n' "$YELLOW" "$OFF" "$*"; }
die()  { printf '\n  %s✗ %s%s\n\n' "$RED" "$*" "$OFF"; printf '%s' "$DIM"; read -r -p '  Press Return to close. ' _ || true; printf '%s' "$OFF"; exit 1; }

clear 2>/dev/null || true
printf '%s' "$GOLD"
cat <<'BANNER'
   ___          _      ___                   _
  | _ ) _ _ __ _(_)_ _ / __| _ __  __ _ _ _ | |__
  | _ \| '_/ _` | | ' \\__ \| '_ \/ _` | '_|| / /
  |___/|_| \__,_|_|_||_|___/| .__/\__,_|_|  |_\_\
                            |_|
BANNER
printf '%s' "$OFF"
say "  ${DIM}AI-assisted cost engineering — starting on this Mac${OFF}"

# ── 1. Node ──────────────────────────────────────────────────────────────────
step "Checking Node.js"
# Finder gives a login shell without Homebrew on PATH on some setups.
for p in /opt/homebrew/bin /usr/local/bin; do
  [ -d "$p" ] && case ":$PATH:" in *":$p:"*) ;; *) PATH="$p:$PATH" ;; esac
done
export PATH

if ! command -v node >/dev/null 2>&1; then
  die "Node.js is not installed.

  Install it, then double-click this file again:
    ${BOLD}Homebrew:${OFF}  brew install node
    ${BOLD}Or:${OFF}        https://nodejs.org  (download the LTS installer)"
fi
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
if [ "$NODE_MAJOR" -lt 20 ]; then
  die "Node $(node -v) is too old — this app needs 20 or newer (22 is what CI uses).

  Upgrade with:  brew upgrade node"
fi
ok "Node $(node -v)"

# ── 2. Secrets, generated once and kept out of git ───────────────────────────
step "Local configuration"
ENV_FILE=".brainspark-local.env"
if [ ! -f "$ENV_FILE" ]; then
  umask 077
  {
    echo "# Generated by start-macos.command on $(date '+%Y-%m-%d %H:%M'). Machine-local — never commit."
    echo "JWT_SECRET=$(node -e 'console.log(require("crypto").randomBytes(48).toString("base64url"))')"
    echo "CREDENTIALS_SECRET=$(node -e 'console.log(require("crypto").randomBytes(48).toString("base64url"))')"
    echo "# Optional. Leave blank and paste your key into Settings in the app instead."
    echo "ANTHROPIC_API_KEY="
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  ok "Created $ENV_FILE with fresh secrets (readable only by you)"
else
  ok "Using existing $ENV_FILE"
fi
set -a; . "./$ENV_FILE"; set +a
export DATA_DIR="${DATA_DIR:-$PWD/data}"

if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  note "No Anthropic API key set — the engines, benchmarks and every page that"
  note "  does not call the model still work. Idea generation needs a key: add"
  note "  one in the app under Settings, or put it in $ENV_FILE."
fi

# ── 3. Dependencies ──────────────────────────────────────────────────────────
step "Dependencies"
ABI_STAMP="node_modules/.brainspark-node-major"
NEED_INSTALL=""
if   [ ! -d node_modules ];                       then NEED_INSTALL="first run"
elif [ package-lock.json -nt node_modules ];      then NEED_INSTALL="package-lock.json changed"
elif [ ! -f "$ABI_STAMP" ];                       then NEED_INSTALL="unknown Node version on the existing install"
elif [ "$(cat "$ABI_STAMP")" != "$NODE_MAJOR" ];  then NEED_INSTALL="Node changed from v$(cat "$ABI_STAMP") to v$NODE_MAJOR"
fi
if [ -n "$NEED_INSTALL" ]; then
  say "  ${DIM}Installing ($NEED_INSTALL) — this takes a few minutes; better-sqlite3 compiles.${OFF}"
  if ! npm ci; then
    die "npm ci failed.

  The usual cause on a new Mac is missing compiler tools for better-sqlite3:
    ${BOLD}xcode-select --install${OFF}
  Then double-click this file again."
  fi
  # better-sqlite3 is compiled against one Node ABI. Remember which, so a later
  # `brew upgrade node` reinstalls instead of crashing on a C++ loader error.
  printf '%s' "$NODE_MAJOR" > "$ABI_STAMP"
  touch node_modules
  ok "Installed for Node $NODE_MAJOR"
else
  ok "Already installed (built for Node $NODE_MAJOR)"
fi

# ── 4. Front end ─────────────────────────────────────────────────────────────
step "Front end"
NEWEST_SRC=$(find src index.html vite.config.ts tailwind.config.js -type f -newer dist/index.html 2>/dev/null | head -1 || true)
if [ ! -f dist/index.html ] || [ -n "$NEWEST_SRC" ]; then
  say "  ${DIM}Building…${OFF}"
  npm run build >/dev/null || die "The front-end build failed. Run 'npm run build' in Terminal to see why."
  ok "Built"
else
  ok "Up to date"
fi

# ── 5. What this machine can and cannot do ───────────────────────────────────
step "Optional CAD engine"
if command -v python3 >/dev/null 2>&1 && python3 -c 'import OCP' >/dev/null 2>&1; then
  ok "OpenCascade present — DFM Studio, CAD→Cost and Prism geometry will work"
else
  note "Not installed. Everything else runs; the pages that read a STEP file"
  note "  (DFM Studio, DFA, CAD→Cost, Prism geometry, assembly decomposition)"
  note "  will say they cannot measure rather than guessing. To enable them:"
  note "    ${BOLD}pip3 install cadquery-ocp${OFF}   ${DIM}(~275 MB)${OFF}"
fi

# ── 6. Boot ──────────────────────────────────────────────────────────────────
step "Starting the server"
PORT="${PORT:-3001}"
while node -e "const n=require('net').createServer();n.once('error',()=>process.exit(1));n.once('listening',()=>{n.close();process.exit(0)});n.listen($PORT,'127.0.0.1')" 2>/dev/null; [ $? -ne 0 ]; do
  note "Port $PORT is in use — trying $((PORT + 1))"
  PORT=$((PORT + 1))
  [ "$PORT" -gt 3020 ] && die "No free port between 3001 and 3020."
done
export PORT

# Development mode on purpose: production mode demands SMTP credentials, and
# without them one-time passcodes would be a hole rather than a convenience.
# Here they print to THIS WINDOW, which on your own Mac is the right trade.
unset NODE_ENV
node server.mjs &
SERVER_PID=$!
cleanup() { printf '\n%s  Stopping…%s\n' "$DIM" "$OFF"; kill "$SERVER_PID" 2>/dev/null || true; wait "$SERVER_PID" 2>/dev/null || true; }
trap cleanup EXIT INT TERM

URL="http://localhost:$PORT"
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "$URL/api/health" 2>/dev/null; then READY=1; break; fi
  kill -0 "$SERVER_PID" 2>/dev/null || die "The server stopped while starting. The error is above."
  sleep 1
done
[ "${READY:-}" = 1 ] || die "The server did not answer on $URL within 60 seconds."

ok "Running at $URL"
[ "${BRAINSPARK_OPEN:-1}" = 1 ] && command -v open >/dev/null 2>&1 && open "$URL"

printf '\n  %sBrainSpark is running.%s  %sSign-in codes appear in this window.%s\n' "$BOLD" "$OFF" "$DIM" "$OFF"
printf '  %sPress Ctrl-C, or close this window, to stop.%s\n\n' "$DIM" "$OFF"
wait "$SERVER_PID"
