/**
 * Aluminium extrusion — market, alloy, press and process data (built Oct 2026).
 *
 * Everything the aluminium-extrusion should-cost reads that is not measured from
 * the CAD lives here, as DATA, each figure carrying its basis. Two kinds:
 *
 *   SOURCED   — read from a published assessment on the date stated (LME, the
 *               regional premiums, the billet premiums, FX).
 *   ESTIMATE  — engineering-typical, anchored to the published ranges quoted in
 *               the note, and printed as an estimate wherever it reaches a cost.
 *
 * The market block moves with the market. It is the one place to update when
 * LME or a premium moves; nothing else in the chain holds a metal price.
 */
import type { ManufacturingRegion } from './regional-rates.js';

// ─── Market ───────────────────────────────────────────────────────────────────

export const AL_MARKET = {
  asOf: '2026-09-30',
  /** LME aluminium, US$/t. Cash $3,253 (25 Sep), 3-month $3,213.5 (29 Sep): mid-point. */
  lmeUsdPerT: 3_240,
  /** Bank of England spot, 30 Sep 2026: $1.3285 per £. */
  usdPerGbp: 1.3285,
  sources: [
    'LME cash $3,253/t 25 Sep 2026 (alcircle.com); LME 3M $3,213.5/t 29 Sep 2026 (discoveryalert.com)',
    'Bank of England USD/GBP 1.3285, 30 Sep 2026 (poundsterlinglive.com BoE reference rates)',
  ],
} as const;

/**
 * All-in billet premium over LME, US$/t, for 6063 delivered to an extruder in
 * each manufacturing region — the regional duty-paid ingot premium AND the
 * casthouse billet conversion, as the market quotes billet ("6063 extrusion
 * billet premium, DDP …" is an all-in premium over LME).
 */
export interface BilletPremium {
  usdPerT: number;
  sourced: boolean;
  basis: string;
}

const EU_BILLET = 1_100;   // DE Ruhr $1,070–1,135 and IT Brescia $1,075–1,150, 28 Aug 2026
export const BILLET_PREMIUM_USD_PER_T: Record<ManufacturingRegion, BilletPremium> = {
  DE: { usdPerT: 1_100, sourced: true, basis: 'Fastmarkets 6063 billet premium DDP North Germany (Ruhr) $1,070–1,135/t, 28 Aug 2026 — mid-point' },
  IT: { usdPerT: 1_110, sourced: true, basis: 'Fastmarkets 6063 billet premium DDP Italy (Brescia) $1,075–1,150/t, 28 Aug 2026 — mid-point' },
  FR: { usdPerT: EU_BILLET, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026 (no French assessment)' },
  NL: { usdPerT: EU_BILLET, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026' },
  ES: { usdPerT: EU_BILLET, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026 (DDP Spain assessed fortnightly)' },
  SE: { usdPerT: EU_BILLET, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026' },
  PL: { usdPerT: 1_080, sourced: false, basis: 'EU duty-paid billet less ~$20/t for Central European casthouse supply — estimate' },
  CZ: { usdPerT: 1_080, sourced: false, basis: 'EU duty-paid billet less ~$20/t — estimate' },
  HU: { usdPerT: 1_080, sourced: false, basis: 'EU duty-paid billet less ~$20/t — estimate' },
  RO: { usdPerT: 1_060, sourced: false, basis: 'EU duty-paid billet less ~$40/t (Alro domestic casthouse) — estimate' },
  UK: { usdPerT: 1_100, sourced: false, basis: 'UK imports billet from the EU and Norway at EU duty-paid levels (Ruhr / Brescia, 28 Aug 2026) — estimate' },
  TR: { usdPerT: 675, sourced: true, basis: 'Fastmarkets 6063 billet premium CIF Turkey (Marmara) $650–700/t — mid-point' },
  US: { usdPerT: 2_960, sourced: false, basis: 'US Midwest duty-paid premium $2,410/t (30 Sep 2026, cbonds Midwest index; Section 232 tariff) + billet upcharge ~$550/t (20–30 c/lb) — premium sourced, upcharge estimate' },
  MX: { usdPerT: 395, sourced: true, basis: 'Fastmarkets 6063 billet premium CIF Mexico $370–420/t, 9 Sep 2026 — mid-point' },
  BR: { usdPerT: 725, sourced: true, basis: 'Fastmarkets 6063/6060 billet premium CIF Brazilian main ports $700–750/t — mid-point' },
  CN: { usdPerT: -186, sourced: false, basis: 'SHFE ~RMB 23,800/t incl. 13% VAT → RMB 21,060 ex-VAT ≈ $2,966/t at RMB 7.10 ($274 under LME) + 6063 bar processing fee ~RMB 625 ≈ $88 (Mysteel, Jul 2026) — derived' },
  IN: { usdPerT: 710, sourced: true, basis: 'Hindalco AA6063 billet (P1020 + ₹17,600/t, Aug 2026) over LME 3M, Oct 2026 derived; May measured $803–842/t — the book held $550 (India rate book 2026-10-10)' },
  TH: { usdPerT: 420, sourced: false, basis: 'Asian P1020 premium ~$200–395/t + Thai 6063 billet processing fee $100–250 (alcircle, 2026) — estimate' },
  VN: { usdPerT: 450, sourced: false, basis: 'Asian P1020 premium + Vietnamese 6063 billet fee ~$200/t mid-June 2026 (alcircle) — estimate' },
  KR: { usdPerT: 420, sourced: false, basis: 'P1020A premium CIF South Korea $155–165/t + billet conversion ~$260 — estimate' },
  // ⟪region-expand 2026-10 — generated by scripts/region-expand.ts; edit the config, not these lines⟫
  AT: { usdPerT: 1100, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026' },
  BE: { usdPerT: 1100, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026' },
  PT: { usdPerT: 1100, sourced: false, basis: 'EU duty-paid billet: Ruhr / Brescia assessments, 28 Aug 2026' },
  SK: { usdPerT: 1080, sourced: false, basis: 'EU duty-paid billet less ~$20/t (Central Europe, as CZ / PL) — estimate' },
  SI: { usdPerT: 1080, sourced: false, basis: 'EU duty-paid billet less ~$20/t (Talum domestic casthouse) — estimate' },
  LT: { usdPerT: 1080, sourced: false, basis: 'EU duty-paid billet less ~$20/t — estimate' },
  BG: { usdPerT: 1060, sourced: false, basis: 'EU duty-paid billet less ~$40/t (as Romania) — estimate' },
  RS: { usdPerT: 1080, sourced: false, basis: 'EU duty-paid billet less ~$20/t (EU supply, duty-free under the Stabilisation and Association Agreement) — estimate' },
  MA: { usdPerT: 675, sourced: false, basis: 'Mediterranean CIF: Fastmarkets 6063 billet premium CIF Turkey (Marmara) $650–700/t as the nearest assessment — estimate' },
  TN: { usdPerT: 675, sourced: false, basis: 'Mediterranean CIF: Fastmarkets CIF Turkey (Marmara) as the nearest assessment — estimate' },
  EG: { usdPerT: 600, sourced: false, basis: 'Egyptalum domestic supply, below the Mediterranean CIF level — estimate' },
  ZA: { usdPerT: 600, sourced: false, basis: 'Hillside (Richards Bay) domestic metal + local billet conversion — estimate' },
  JP: { usdPerT: 430, sourced: false, basis: 'Japan quarterly (MJP) primary premium + billet conversion ~$260 (as Korea) — estimate' },
  TW: { usdPerT: 420, sourced: false, basis: 'Asian P1020 premium + billet conversion (as Korea) — estimate' },
  MY: { usdPerT: 400, sourced: false, basis: 'Asian P1020 premium + 6063 billet fee; Press Metal domestic smelting — estimate' },
  ID: { usdPerT: 450, sourced: false, basis: 'Asian P1020 premium + billet fee (as Vietnam); Inalum domestic smelting — estimate' },
  PH: { usdPerT: 450, sourced: false, basis: 'Asian P1020 premium + billet fee (as Vietnam) — estimate' },
  SG: { usdPerT: 430, sourced: false, basis: 'Asian P1020 premium + billet conversion — estimate' },
  CA: { usdPerT: 1050, sourced: false, basis: 'Canadian domestic metal: P1020 premium ~$500/t (no Section 232 tariff inside Canada) + billet upcharge ~$550/t (as US) — estimate' },
  // ⟪/region-expand⟫
};

// ─── Alloys ───────────────────────────────────────────────────────────────────

/**
 * Every wrought alloy extruded in volume — 30, by series (aluminium-extrusion review,
 * Oct 2026: the build carried 14; the review adds the rest of the EN 573 /
 * Aluminum Association extrusion range — EC conductor, 3103, 5754 / 5086, the
 * architectural and automotive 6xxx (6063A, 6106, 6008, 6351), free-machining
 * 6026 / 2011, 2014 / 2017A and the transport 7xxx 7005 / 7046).
 */
export type AlAlloy =
  | '1050' | '1070A' | '1100' | '1350'
  | '3003' | '3103'
  | '5754' | '5083' | '5086'
  | '6060' | '6063' | '6063A' | '6106' | '6101' | '6005A' | '6008' | '6061' | '6351' | '6082' | '6026'
  | '2011' | '2014' | '2017A' | '2024'
  | '7003' | '7005' | '7046' | '7108' | '7020' | '7075';

/** Every temper an extrusion is supplied in (EN 515). */
export type AlTemper =
  | 'F' | 'O' | 'H112'
  | 'T3' | 'T3510' | 'T3511' | 'T4' | 'T5' | 'T6' | 'T64' | 'T66' | 'T7' | 'T73' | 'T76' | 'T8';

export type QuenchKind = 'none' | 'air' | 'mist' | 'water' | 'offline-sht';
export type AlSeries = '1xxx' | '2xxx' | '3xxx' | '5xxx' | '6xxx' | '7xxx';

export interface AlloyData {
  label: string;
  series: AlSeries;
  densityKgPerM3: number;
  /** Billet premium over 6063, US$/t — alloying additions, casthouse yield, homogenising. ESTIMATE. */
  billetAdderUsdPerT: number;
  /**
   * Mean flow stress at the alloy's billet temperature and an extrusion strain
   * rate of a few s⁻¹, MPa. 6063 is the anchor: Sellars–Tegart with Sheppard &
   * Jackson's constants (α 0.04 MPa⁻¹, n 5.385, ln A 22.5, Q 141.5 kJ/mol) at
   * 480 °C and ε̇ ≈ 3 s⁻¹ gives 26 MPa. The others are scaled from it by relative
   * hot strength — ESTIMATE. The press-quenchable 7xxx (7003, 7108) sit with 6082:
   * they are chosen for bumper beams because they extrude like a hard 6xxx.
   */
  flowStressMPa: number;
  /**
   * Exit speed on a plain solid section, m/min. Soft and medium alloys: 6063 at
   * 50 m/min (ESTIMATE, inside the published "economic to 100 m/min") times the
   * published relative extrudability where it exists (6063 = 100: 1350 160,
   * 1100 135, 3003 120, 6061 60, 2011 35, 5086 25, 2014 20, 5083 20, 2024 15,
   * 7075 9). Hard alloys take the middle of the published exit-speed band
   * instead (2014–2024 1.5–3.5, 5083 / 5086 / 5456 2–6, 7075 0.8–2 m/min).
   */
  baseExitSpeedMPerMin: number;
  speedBasis: string;
  /** Largest practical extrusion ratio (6063 ~100, 7075 6–30, published). */
  maxRatio: number;
  /** Butt discard left in the container, mm (soft alloys 20–35 mm, published). */
  buttMm: number;
  quench: QuenchKind;
  heatTreatable: boolean;
  defaultTemper: AlTemper;
  /** The tempers the alloy is supplied in. */
  tempers: AlTemper[];
  /** Artificial ageing at the oven, hours incl. ramp (6xxx T5/T6 6–10 h, published; 7xxx two-step). */
  ageHours: number;
  /**
   * Process scrap value: LME + this differential, US$/t. 6xxx is SOURCED:
   * Fastmarkets "clean production extrusions (6063), delivered consumer Europe"
   * averaged LME + €48/t in 2026 (MB-AL-0404) = +$56/t at $1.165/€. Other series
   * carry a discount for segregation and alloy (Cu, Zn, Mg, Pb/Bi) — ESTIMATE.
   */
  scrapDiffUsdPerT: number;
  /** Hollow high-strength sections are extruded seamless on an indirect press, not porthole-welded. */
  prefersIndirect: boolean;
  uses: string;
}

const T_NONHT: AlTemper[] = ['H112', 'O', 'F'];
const T_6XXX: AlTemper[] = ['T4', 'T5', 'T6', 'T64', 'T66', 'T7', 'O', 'F'];
const T_2XXX: AlTemper[] = ['T3', 'T3510', 'T3511', 'T4', 'T6', 'T8', 'O', 'F'];
const T_7XXX: AlTemper[] = ['T5', 'T6', 'T7', 'T73', 'T76', 'O', 'F'];
/** Clean 6063 production scrap, LME + €48/t (Fastmarkets MB-AL-0404, 2026 average) at $1.165/€. */
export const SCRAP_DIFF_6XXX_USD = 56;

const idx = (n: number, i: string) => `${n} m/min — 6063's 50 × the published relative extrudability ${i}`;
const est = (n: number, why: string) => `${n} m/min — ESTIMATE: ${why}`;
const band = (n: number, b: string) => `${n} m/min — middle of the published ${b} m/min band`;

export const AL_ALLOYS: Record<AlAlloy, AlloyData> = {
  // ── 1xxx: commercially pure ──
  '1050': { label: 'EN AW-1050A (99.5% Al)', series: '1xxx', densityKgPerM3: 2705, billetAdderUsdPerT: -40, flowStressMPa: 18, baseExitSpeedMPerMin: 67, speedBasis: idx(67, '135 (1060 / 1100)'), maxRatio: 300, buttMm: 20, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'busbar, heat-exchanger tube, electrical' },
  '1070A': { label: 'EN AW-1070A (99.7% Al)', series: '1xxx', densityKgPerM3: 2700, billetAdderUsdPerT: -30, flowStressMPa: 17, baseExitSpeedMPerMin: 67, speedBasis: idx(67, '135 (1060 / 1100)'), maxRatio: 300, buttMm: 20, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'conductor, reflector, heat exchanger' },
  '1100': { label: 'AA 1100 (99.0% Al)', series: '1xxx', densityKgPerM3: 2710, billetAdderUsdPerT: -20, flowStressMPa: 20, baseExitSpeedMPerMin: 67, speedBasis: idx(67, '135'), maxRatio: 250, buttMm: 20, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'general pure-aluminium tube and shapes (US)' },
  '1350': { label: 'EN AW-1350 (EC, electrical conductor)', series: '1xxx', densityKgPerM3: 2705, billetAdderUsdPerT: 20, flowStressMPa: 16, baseExitSpeedMPerMin: 80, speedBasis: idx(80, '160'), maxRatio: 300, buttMm: 20, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'busbar, conductor, EV power distribution' },
  // ── 3xxx: Al-Mn ──
  '3003': { label: 'EN AW-3003 (Al-Mn1Cu)', series: '3xxx', densityKgPerM3: 2730, billetAdderUsdPerT: 40, flowStressMPa: 24, baseExitSpeedMPerMin: 60, speedBasis: idx(60, '120'), maxRatio: 150, buttMm: 25, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: -150, prefersIndirect: false, uses: 'HVAC / radiator tube, multi-port tube' },
  '3103': { label: 'EN AW-3103 (Al-Mn1)', series: '3xxx', densityKgPerM3: 2730, billetAdderUsdPerT: 40, flowStressMPa: 24, baseExitSpeedMPerMin: 60, speedBasis: idx(60, '120 (as 3003)'), maxRatio: 150, buttMm: 25, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: -150, prefersIndirect: false, uses: 'heat-exchanger and condenser tube (EU)' },
  // ── 5xxx: Al-Mg, non-heat-treatable, hard to extrude ──
  '5754': { label: 'EN AW-5754 (Al-Mg3)', series: '5xxx', densityKgPerM3: 2670, billetAdderUsdPerT: 200, flowStressMPa: 42, baseExitSpeedMPerMin: 8, speedBasis: est(8, 'Mg 3% — between 5052 and the 5083 / 5086 band'), maxRatio: 50, buttMm: 35, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: -150, prefersIndirect: false, uses: 'marine, tanks, welded structures' },
  '5083': { label: 'EN AW-5083 (Al-Mg4.5Mn)', series: '5xxx', densityKgPerM3: 2660, billetAdderUsdPerT: 300, flowStressMPa: 52, baseExitSpeedMPerMin: 4, speedBasis: band(4, '5083 / 5086 / 5456 2–6'), maxRatio: 40, buttMm: 40, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: -200, prefersIndirect: false, uses: 'marine, rail, cryogenic' },
  '5086': { label: 'EN AW-5086 (Al-Mg4)', series: '5xxx', densityKgPerM3: 2660, billetAdderUsdPerT: 280, flowStressMPa: 50, baseExitSpeedMPerMin: 5, speedBasis: band(5, '5083 / 5086 / 5456 2–6 (5086 relative extrudability 25 > 5083 20)'), maxRatio: 40, buttMm: 40, quench: 'none', heatTreatable: false, defaultTemper: 'H112', tempers: T_NONHT, ageHours: 0, scrapDiffUsdPerT: -200, prefersIndirect: false, uses: 'marine, vehicle bodies' },
  // ── 6xxx: Al-Mg-Si, the extrusion family ──
  '6060': { label: 'EN AW-6060 (Al-MgSi)', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: -20, flowStressMPa: 24, baseExitSpeedMPerMin: 55, speedBasis: est(55, 'leaner than 6063, extrudes a little faster'), maxRatio: 120, buttMm: 25, quench: 'air', heatTreatable: true, defaultTemper: 'T66', tempers: T_6XXX, ageHours: 6, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'architectural, trim, low-load profiles' },
  '6063': { label: 'EN AW-6063 (Al-Mg0.7Si)', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: 0, flowStressMPa: 26, baseExitSpeedMPerMin: 50, speedBasis: '50 m/min — the reference (ESTIMATE inside the published "economic up to 100 m/min")', maxRatio: 100, buttMm: 25, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 6, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'general profiles, trim, heat sinks' },
  '6063A': { label: 'EN AW-6063A (Al-Mg0.7Si(A))', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: 20, flowStressMPa: 28, baseExitSpeedMPerMin: 45, speedBasis: est(45, 'higher Mg/Si than 6063'), maxRatio: 90, buttMm: 25, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 6, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'architectural and structural profiles' },
  '6106': { label: 'EN AW-6106 (Al-MgSiMn)', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: 10, flowStressMPa: 26, baseExitSpeedMPerMin: 50, speedBasis: est(50, 'extrudes as 6063'), maxRatio: 100, buttMm: 25, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 6, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'thin structural profiles, frames' },
  '6101': { label: 'EN AW-6101B (electrical)', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: 60, flowStressMPa: 26, baseExitSpeedMPerMin: 45, speedBasis: est(45, 'conductivity-controlled chemistry, close to 6063'), maxRatio: 100, buttMm: 25, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 6, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'busbar, EV conductor' },
  '6005A': { label: 'EN AW-6005A (Al-SiMg(A))', series: '6xxx', densityKgPerM3: 2710, billetAdderUsdPerT: 80, flowStressMPa: 30, baseExitSpeedMPerMin: 35, speedBasis: est(35, 'between 6063 and 6061 (60)'), maxRatio: 80, buttMm: 30, quench: 'mist', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 8, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'rail, battery tray, structural hollows' },
  '6008': { label: 'EN AW-6008 (Al-SiMgV)', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: 120, flowStressMPa: 30, baseExitSpeedMPerMin: 35, speedBasis: est(35, 'as 6005A'), maxRatio: 80, buttMm: 30, quench: 'mist', heatTreatable: true, defaultTemper: 'T7', tempers: T_6XXX, ageHours: 8, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'automotive crash management, sills (over-aged T7)' },
  '6061': { label: 'EN AW-6061 (Al-Mg1SiCu)', series: '6xxx', densityKgPerM3: 2700, billetAdderUsdPerT: 150, flowStressMPa: 34, baseExitSpeedMPerMin: 30, speedBasis: idx(30, '60 (published 20–80 m/min)'), maxRatio: 60, buttMm: 35, quench: 'water', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 8, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'structural, machined parts' },
  '6351': { label: 'EN AW-6351 (Al-Si1Mg0.5Mn)', series: '6xxx', densityKgPerM3: 2710, billetAdderUsdPerT: 150, flowStressMPa: 35, baseExitSpeedMPerMin: 25, speedBasis: est(25, 'Mn-bearing, between 6061 and 6082'), maxRatio: 60, buttMm: 35, quench: 'water', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 8, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'structural, truck and trailer' },
  '6082': { label: 'EN AW-6082 (Al-Si1MgMn)', series: '6xxx', densityKgPerM3: 2710, billetAdderUsdPerT: 150, flowStressMPa: 36, baseExitSpeedMPerMin: 20, speedBasis: est(20, 'Mn dispersoids — below 6061 (60)'), maxRatio: 60, buttMm: 35, quench: 'water', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 8, scrapDiffUsdPerT: SCRAP_DIFF_6XXX_USD, prefersIndirect: false, uses: 'structural, crash, chassis' },
  '6026': { label: 'EN AW-6026 (free-machining, lead-free)', series: '6xxx', densityKgPerM3: 2720, billetAdderUsdPerT: 400, flowStressMPa: 36, baseExitSpeedMPerMin: 15, speedBasis: est(15, 'Bi/Sn free-machining — hot-short, run slow'), maxRatio: 50, buttMm: 40, quench: 'water', heatTreatable: true, defaultTemper: 'T6', tempers: T_6XXX, ageHours: 8, scrapDiffUsdPerT: -450, prefersIndirect: false, uses: 'screw-machine bar, hydraulic fittings' },
  // ── 2xxx: Al-Cu, extruded slowly, solution-treated off the press ──
  '2011': { label: 'EN AW-2011 (Al-Cu6BiPb, free-machining)', series: '2xxx', densityKgPerM3: 2830, billetAdderUsdPerT: 1_000, flowStressMPa: 50, baseExitSpeedMPerMin: 6, speedBasis: est(6, 'relative extrudability 35, but hot-short Bi/Pb — run well under 6063 × 0.35'), maxRatio: 40, buttMm: 45, quench: 'offline-sht', heatTreatable: true, defaultTemper: 'T3', tempers: T_2XXX, ageHours: 0, scrapDiffUsdPerT: -450, prefersIndirect: true, uses: 'screw-machine parts' },
  '2014': { label: 'EN AW-2014 (Al-Cu4SiMg)', series: '2xxx', densityKgPerM3: 2800, billetAdderUsdPerT: 1_200, flowStressMPa: 60, baseExitSpeedMPerMin: 2.5, speedBasis: band(2.5, '2014–2024 1.5–3.5'), maxRatio: 30, buttMm: 50, quench: 'offline-sht', heatTreatable: true, defaultTemper: 'T6', tempers: T_2XXX, ageHours: 18, scrapDiffUsdPerT: -400, prefersIndirect: true, uses: 'aerospace, high-stressed fittings' },
  '2017A': { label: 'EN AW-2017A (Al-Cu4MgSi)', series: '2xxx', densityKgPerM3: 2790, billetAdderUsdPerT: 1_200, flowStressMPa: 58, baseExitSpeedMPerMin: 2.5, speedBasis: band(2.5, '2014–2024 1.5–3.5'), maxRatio: 30, buttMm: 50, quench: 'offline-sht', heatTreatable: true, defaultTemper: 'T4', tempers: T_2XXX, ageHours: 0, scrapDiffUsdPerT: -400, prefersIndirect: true, uses: 'machined fittings, rivets' },
  '2024': { label: 'EN AW-2024 (Al-Cu4Mg1)', series: '2xxx', densityKgPerM3: 2780, billetAdderUsdPerT: 1_400, flowStressMPa: 62, baseExitSpeedMPerMin: 2.5, speedBasis: band(2.5, '2014–2024 1.5–3.5'), maxRatio: 30, buttMm: 50, quench: 'offline-sht', heatTreatable: true, defaultTemper: 'T3511', tempers: T_2XXX, ageHours: 0, scrapDiffUsdPerT: -400, prefersIndirect: true, uses: 'aerospace, fasteners' },
  // ── 7xxx: Al-Zn-Mg; the medium-strength weldable ones press-quench ──
  '7003': { label: 'EN AW-7003 (Al-Zn6Mg0.8Zr)', series: '7xxx', densityKgPerM3: 2780, billetAdderUsdPerT: 350, flowStressMPa: 40, baseExitSpeedMPerMin: 10, speedBasis: est(10, 'press-quenchable medium-strength 7xxx'), maxRatio: 50, buttMm: 40, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_7XXX, ageHours: 20, scrapDiffUsdPerT: -300, prefersIndirect: false, uses: 'bumper beams, crash management' },
  '7005': { label: 'EN AW-7005 (Al-Zn4.5Mg1.5Mn)', series: '7xxx', densityKgPerM3: 2780, billetAdderUsdPerT: 380, flowStressMPa: 44, baseExitSpeedMPerMin: 8, speedBasis: est(8, 'as 7020'), maxRatio: 45, buttMm: 40, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_7XXX, ageHours: 22, scrapDiffUsdPerT: -300, prefersIndirect: false, uses: 'bicycle frames, transport structures' },
  '7046': { label: 'EN AW-7046 (Al-Zn7Mg1.2)', series: '7xxx', densityKgPerM3: 2790, billetAdderUsdPerT: 420, flowStressMPa: 44, baseExitSpeedMPerMin: 8, speedBasis: est(8, 'as 7020'), maxRatio: 45, buttMm: 40, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_7XXX, ageHours: 22, scrapDiffUsdPerT: -300, prefersIndirect: false, uses: 'automotive bumper and crash beams' },
  '7108': { label: 'EN AW-7108 (Al-Zn5Mg1Zr)', series: '7xxx', densityKgPerM3: 2770, billetAdderUsdPerT: 350, flowStressMPa: 40, baseExitSpeedMPerMin: 10, speedBasis: est(10, 'as 7003'), maxRatio: 50, buttMm: 40, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_7XXX, ageHours: 20, scrapDiffUsdPerT: -300, prefersIndirect: false, uses: 'bumper beams, side-impact' },
  '7020': { label: 'EN AW-7020 (Al-Zn4.5Mg1)', series: '7xxx', densityKgPerM3: 2780, billetAdderUsdPerT: 380, flowStressMPa: 44, baseExitSpeedMPerMin: 8, speedBasis: est(8, 'medium-strength 7xxx, slower than 7003'), maxRatio: 45, buttMm: 40, quench: 'air', heatTreatable: true, defaultTemper: 'T6', tempers: T_7XXX, ageHours: 22, scrapDiffUsdPerT: -300, prefersIndirect: false, uses: 'rail, defence, structural' },
  '7075': { label: 'EN AW-7075 (Al-Zn5.5MgCu)', series: '7xxx', densityKgPerM3: 2810, billetAdderUsdPerT: 1_200, flowStressMPa: 65, baseExitSpeedMPerMin: 1.4, speedBasis: band(1.4, '7075 / 7079 0.8–2'), maxRatio: 30, buttMm: 50, quench: 'offline-sht', heatTreatable: true, defaultTemper: 'T6', tempers: T_7XXX, ageHours: 24, scrapDiffUsdPerT: -400, prefersIndirect: true, uses: 'aerospace, high-strength' },
};

/** Billet price for an alloy in a region, £/kg: (LME + all-in premium + alloy adder) ÷ FX ÷ 1000. */
export function billetPriceGbpPerKg(alloy: AlAlloy, region: ManufacturingRegion): number {
  const usd = AL_MARKET.lmeUsdPerT + BILLET_PREMIUM_USD_PER_T[region].usdPerT + AL_ALLOYS[alloy].billetAdderUsdPerT;
  return Math.round(usd / AL_MARKET.usdPerGbp / 1000 * 10_000) / 10_000;
}

/**
 * Process-scrap value, £/kg: LME + the alloy's differential. Scrap is sold on
 * LME terms, not at the regional billet premium, so it is the same in every region.
 */
export function alScrapGbpPerKg(alloy: AlAlloy): number {
  return Math.round((AL_MARKET.lmeUsdPerT + AL_ALLOYS[alloy].scrapDiffUsdPerT) / AL_MARKET.usdPerGbp / 1000 * 10_000) / 10_000;
}

/** The library material id for an alloy's billet. */
export const alBilletId = (alloy: AlAlloy): string => `mat-al-billet-${alloy.toLowerCase()}`;
export const AL_ALLOY_LIST = Object.keys(AL_ALLOYS) as AlAlloy[];

// ─── Presses ──────────────────────────────────────────────────────────────────

export type AlExtrusionRoute = 'direct' | 'indirect' | 'hydrostatic' | 'conform' | 'impact';

export interface AlPress {
  id: string;
  route: AlExtrusionRoute;
  label: string;
  forceT: number;
  /** Container bore, mm (≈ billet Ø + 6). 1,800 t ↔ 178 mm and 2,500 t ↔ 230–254 mm billet, published. */
  containerMm: number;
  /** Largest circumscribing circle a die on this press takes: solid / hollow. */
  maxCcdSolidMm: number;
  maxCcdHollowMm: number;
  /** Dead cycle: billet load, upset, butt shear, s. */
  deadCycleSec: number;
  maxBilletMm: number;
  /** Run-out table: the longest strand the puller and cooling table take, m. */
  runoutM: number;
  /** Ram speed ceiling, mm/s. */
  maxRamMmPerSec: number;
  /** Line capex (press + log heater + puller + cooling table + stretcher + saw), £. ESTIMATE. */
  capexGbp: number;
  /** Line crew. */
  crew: number;
}

/**
 * Press classes, smallest first. Capex: bare Chinese press $0.8–1.8 M (1,450–1,800 t)
 * and $1.5–3 M (2,000–2,500 t), full line +40–70% (slxextrusionpress.com 2026); a
 * European-built line is costed here, so the figures sit above those — ESTIMATE.
 */
export const AL_PRESSES: AlPress[] = [
  { id: 'al-ext-press-800t', route: 'direct', label: '800 t direct press, 4" container', forceT: 800, containerMm: 107, maxCcdSolidMm: 85, maxCcdHollowMm: 70, deadCycleSec: 16, maxBilletMm: 500, runoutM: 36, maxRamMmPerSec: 18, capexGbp: 1_800_000, crew: 2 },
  { id: 'al-ext-press-1450t', route: 'direct', label: '1,450 t direct press, 6" container', forceT: 1450, containerMm: 158, maxCcdSolidMm: 130, maxCcdHollowMm: 110, deadCycleSec: 18, maxBilletMm: 650, runoutM: 42, maxRamMmPerSec: 18, capexGbp: 3_200_000, crew: 3 },
  { id: 'al-ext-press-1800t', route: 'direct', label: '1,800 t direct press, 7" container', forceT: 1800, containerMm: 184, maxCcdSolidMm: 155, maxCcdHollowMm: 130, deadCycleSec: 20, maxBilletMm: 750, runoutM: 45, maxRamMmPerSec: 17, capexGbp: 4_000_000, crew: 3 },
  { id: 'al-ext-press-2500t', route: 'direct', label: '2,500 t direct press, 9" container', forceT: 2500, containerMm: 236, maxCcdSolidMm: 200, maxCcdHollowMm: 170, deadCycleSec: 24, maxBilletMm: 1000, runoutM: 50, maxRamMmPerSec: 16, capexGbp: 6_000_000, crew: 4 },
  { id: 'al-ext-press-3600t', route: 'direct', label: '3,600 t direct press, 10" container', forceT: 3600, containerMm: 260, maxCcdSolidMm: 230, maxCcdHollowMm: 200, deadCycleSec: 28, maxBilletMm: 1100, runoutM: 55, maxRamMmPerSec: 15, capexGbp: 9_000_000, crew: 4 },
  { id: 'al-ext-press-5500t', route: 'direct', label: '5,500 t direct press, 12" container', forceT: 5500, containerMm: 318, maxCcdSolidMm: 290, maxCcdHollowMm: 250, deadCycleSec: 32, maxBilletMm: 1300, runoutM: 60, maxRamMmPerSec: 14, capexGbp: 15_000_000, crew: 5 },
  { id: 'al-ext-press-8000t', route: 'direct', label: '8,000 t direct press, 14" round / flat container (wide panels)', forceT: 8000, containerMm: 365, maxCcdSolidMm: 600, maxCcdHollowMm: 500, deadCycleSec: 40, maxBilletMm: 1500, runoutM: 65, maxRamMmPerSec: 12, capexGbp: 26_000_000, crew: 6 },
  { id: 'al-ext-indirect-2800t', route: 'indirect', label: '2,800 t indirect press, 9" container (2xxx / 7xxx, seamless tube)', forceT: 2800, containerMm: 236, maxCcdSolidMm: 180, maxCcdHollowMm: 160, deadCycleSec: 32, maxBilletMm: 1100, runoutM: 50, maxRamMmPerSec: 14, capexGbp: 8_500_000, crew: 4 },
  { id: 'al-ext-hydrostatic-1600t', route: 'hydrostatic', label: '1,600 t hydrostatic press (high ratio, clad wire / fine sections)', forceT: 1600, containerMm: 150, maxCcdSolidMm: 60, maxCcdHollowMm: 50, deadCycleSec: 90, maxBilletMm: 900, runoutM: 40, maxRamMmPerSec: 20, capexGbp: 9_500_000, crew: 4 },
];

/** Continuous rotary (Conform) extrusion from rod — small sections, busbar, MPE tube. ESTIMATE. */
export const AL_CONFORM = {
  id: 'al-conform-c400', label: 'Conform C400 continuous extrusion line (9.5–25 mm rod feed)',
  maxCcdMm: 100, outputKgPerHr: 900, capexGbp: 2_600_000, crew: 2,
  /** Rod premium over billet, US$/t (redraw rod). */
  rodAdderUsdPerT: 250,
  alloys: ['1050', '1070A', '1100', '1350', '3003', '3103', '6060', '6063', '6101'] as AlAlloy[],
};

/** Cold impact extrusion — cups, cans, housings from a slug. ESTIMATE. */
export const AL_IMPACT = {
  id: 'al-impact-press-800t', label: '800 t mechanical impact-extrusion press', strokesPerMin: 30,
  capexGbp: 3_200_000, crew: 1,
  /** Slug prep: sawn / punched slug + anneal + lubricate (phosphate / zinc stearate), £/kg. */
  slugPrepGbpPerKg: 0.42,
  /** Trim allowance on the cup mouth. */
  trimAllowance: 0.08,
  /** Tool set (punch + die + ejector) cost by part Ø, £: base + per mm. */
  toolBaseGbp: 6_000, toolPerMmGbp: 120, toolLifeHits: 150_000,
};

// ─── Downstream ───────────────────────────────────────────────────────────────

export const AL_DOWNSTREAM = {
  ageOven: { id: 'al-age-oven-batch', label: 'Batch ageing oven (T5 / T6)', loadKg: 8_000, handlingHr: 0.75, capexGbp: 650_000, gasKwhPerKg: 0.10 },
  sht: { id: 'al-sht-drop-furnace', label: 'Vertical drop-quench solution heat-treatment furnace', loadKg: 3_000, cycleHr: 2.5, capexGbp: 2_400_000, gasKwhPerKg: 0.25 },
  cnc: { id: 'al-cnc-profile-centre', label: '5-axis long-bed profile machining centre (7 m)', capexGbp: 650_000 },
  /**
   * Bender and its tooling. A stretch-bend form block is made for the part: £15k
   * for the first sweep and £5k for each further bend form — ESTIMATE (review, Oct
   * 2026: the build charged no bending tool at all).
   */
  bender: { id: 'al-stretch-bender', label: 'CNC stretch-bending machine (3D, sweep)', capexGbp: 1_100_000, secPerBend: 45, loadSec: 30, toolFirstGbp: 15_000, toolPerExtraBendGbp: 5_000 },
  /**
   * Precision cut-to-length (review, Oct 2026). The press saw cuts the strand into
   * MILL LENGTHS that go through ageing; the part is cut to length cold, with a
   * trim at each end of each mill length, on an automatic saw that cuts a bundle
   * of profiles at once. Capex, cut time and bundle are ESTIMATES.
   */
  ctlSaw: { id: 'al-ctl-saw', label: 'Automatic precision cut-to-length saw (bundle cutting, deburr)', capexGbp: 220_000, secPerCutBase: 6, secPerCutPerMmCcd: 0.04, bundleMaxPieces: 6, bundleWidthMm: 250, handlingSecPerPart: 2 },
  /**
   * Finishing lines. Coating consumables are per m² — ESTIMATES, stated:
   *   anodise  £0.35/m²: acid, etch, seal and rack loss (rectifier power is in the line's running load);
   *   powder   £0.72/m²: 0.12 kg/m² (60–80 µm at 1.5 g/cm³ + overspray) × £6/kg polyester powder;
   *   e-coat   £0.28/m²: 0.035 kg/m² × £8/kg.
   * Powder coats the OUTSIDE only (outer outline × length); anodise and e-coat are
   * immersion processes and coat every surface, chambers included.
   */
  anodise: { id: 'al-anodise-line', label: 'Anodising line (sulphuric, 10–25 µm, seal)', capexGbp: 4_200_000, m2PerHr: 70, crew: 4, consumablesGbpPerM2: 0.35, outsideOnly: false },
  powder: { id: 'al-powder-line', label: 'Vertical powder-coating line (pretreat + cure)', capexGbp: 2_800_000, m2PerHr: 140, crew: 4, consumablesGbpPerM2: 0.72, outsideOnly: true },
  ecoat: { id: 'al-ecoat-line', label: 'E-coat / conversion-coat line (chrome-free, for bonding)', capexGbp: 3_500_000, m2PerHr: 160, crew: 3, consumablesGbpPerM2: 0.28, outsideOnly: false },
  /** Billet log heater, gas: cp·ΔT ≈ 0.115 kWh/kg to 480 °C at ~40% efficiency. DERIVED. */
  billetHeatGasKwhPerKg: 0.29,
  /** Induction heating, electricity: ~0.18 kWh/kg at ~65% efficiency. DERIVED. */
  billetHeatInductionKwhPerKg: 0.18,
};

export type AlFinish = 'mill' | 'anodise' | 'powder' | 'ecoat';

// ─── Dies ─────────────────────────────────────────────────────────────────────

export type AlDieType = 'solid' | 'semi-hollow' | 'hollow-porthole' | 'hollow-bridge' | 'seamless-mandrel' | 'multi-port';

/**
 * UK die-maker prices, £: base + per mm of circumscribing circle. Published
 * anchors are Asian prices — solid $300–3,000, porthole $3,000–10,000+, porthole
 * 3–5× a solid, CCD > 10" pushes $2,000–5,000 (2026 supplier guides). A European
 * die costs more; these are ESTIMATES above the Asian anchors.
 * Life in tonnes extruded: H13 30–80 t, H13 ESR 60–150 t (published).
 */
export const AL_DIES: Record<AlDieType, { baseGbp: number; perMmGbp: number; lifeT: number; label: string }> = {
  solid: { baseGbp: 700, perMmGbp: 9, lifeT: 70, label: 'solid (flat) die' },
  'semi-hollow': { baseGbp: 1_300, perMmGbp: 18, lifeT: 50, label: 'semi-hollow die (tongue)' },
  'hollow-porthole': { baseGbp: 2_200, perMmGbp: 34, lifeT: 40, label: 'porthole (spider) hollow die' },
  'hollow-bridge': { baseGbp: 3_500, perMmGbp: 40, lifeT: 50, label: 'bridge hollow die (large sections)' },
  'seamless-mandrel': { baseGbp: 3_000, perMmGbp: 30, lifeT: 60, label: 'die + piercing mandrel (seamless tube)' },
  'multi-port': { baseGbp: 4_500, perMmGbp: 60, lifeT: 25, label: 'micro multi-port (MPE) die' },
};
/** Die nitriding every 30–50 t (published), £ a treatment incl. correction. ESTIMATE. */
export const AL_DIE_NITRIDE = { everyT: 40, gbp: 180 };

// ─── Line constants (ESTIMATES unless stated) ─────────────────────────────────

export const AL_LINE = {
  /** Front (puller grip) + back (stretcher grip) end scrap per strand, m. */
  endScrapM: 1.2,
  /** Longest mill length the press saw cuts for the ageing baskets, mm. ESTIMATE (6–7.5 m baskets). */
  millLengthMaxMm: 7_000,
  /** Shortest mill length worth stacking and ageing, mm — shorter only for a part longer than it. ESTIMATE. */
  millLengthMinMm: 2_500,
  /** Cold-saw trim at each end of a mill length before cutting parts, mm. ESTIMATE. */
  millEndTrimMm: 25,
  /** Finish-saw kerf, mm. */
  sawKerfMm: 4,
  /** Die change + heat-up per run, hr. */
  dieChangeHr: 0.5,
  /** Runs a year per part number (monthly), and the shortest run worth a die change. */
  runsPerYear: 12,
  minRunHr: 4,
  /** Press electricity: hydraulics, puller, stretcher, saw — kWh per kg extruded (whole-plant 1,200–1,350 kWh/t, published, incl. heating and ageing). */
  pressKwhPerKg: 0.20,
  /** Extrusion ratio below which the section is not worked enough (properties, surface). */
  minRatio: 10,
  /**
   * Container friction on a DIRECT press (review, Oct 2026). Hot aluminium sticks
   * to the container, so the billet is sheared along its length: friction
   * pressure = 4 · m · (σ/√3) · L / D, with m = 1 (sticking). It is what limits
   * the billet length on a hard alloy, and it is zero on indirect and hydrostatic
   * presses. It used to be a flat ×1.35 that never let force bind on a 6xxx part.
   */
  containerFrictionM: 1.0,
  /** A billet shorter than this many container diameters is uneconomic (dead cycle per kg). */
  minBilletDiameters: 2.0,
  /** Hollow dies: the extra pressure to split and re-weld the metal in the chambers. */
  weldChamberFactor: 1.15,
  /** Semi-hollow when the tongue ratio (space ÷ gap²) reaches this — AA practice puts the solid-die limit at 2–4:1. ESTIMATE. */
  semiHollowTongueRatio: 3.0,
  /** Johnson: p / σ = a + b·ln R. */
  johnsonA: 0.8, johnsonB: 1.5,
  /** A press runs to this share of its rated force. */
  forceUse: 0.90,
  oee: 0.78,
  rejectRate: 0.02,
  hoursPerYear: 6000,
};
