"""The FastAPI application.

CLAUDE.md 1: "FastAPI (Python 3.12) - **ORCHESTRATION ONLY**. validates input ->
calls engine -> assembles ChartFacts JSON."

Every route here does exactly those three things. There is no Jyotish arithmetic in
this module or anywhere else under ``api/``; a test asserts that ``core/`` imports
nothing from here, and the reverse dependency is the only one that exists.

Route groups:

===================================  ==========================================
``/health``                          version and configuration, no input
``/v1/panchang``                     a day's panchang for a date and place
``/v1/chart``                        the full schema-valid ChartFacts document
``/v1/chart/svg`` ``/v1/chart/pdf``  rendered kundali (CLAUDE.md 8)
``/v1/milan``                        Ashtakoot from two births
``/v1/narrative``                    validated prose (CLAUDE.md 6)
``/v1/places``                       offline geocoder (CLAUDE.md 2.2)
``/v1/privacy/*``                    consent, export, delete (CLAUDE.md 10)
===================================  ==========================================
"""

from __future__ import annotations

import datetime as dt
from typing import Annotated, Any

from fastapi import Body, Depends, FastAPI, HTTPException, Query, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from api.deps import Settings, get_narrative_service, get_settings, utc_now
from api.locale import SUPPORTED_LOCALES, disclaimer, load_glossary
from api.routers import geocode, privacy
from api.schemas import (
    BirthInput,
    ChartFactsResponse,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    MilanInput,
    NarrativeRequest,
    NarrativeResponse,
    NarrativeSectionOut,
)
from core.dasha.vimshottari import DashaPeriod, subperiods
from core.enums import Graha, YearLength
from core.ephemeris.adapter import CircumpolarError
from core.ephemeris.registry import build_ephemeris
from core.facts.builder import build_chart_facts, compute_full_reading
from core.facts.validate import ChartFactsError, validate_chart_facts
from core.milan.ashtakoot import compute_milan
from core.timeutil import iso_utc
from core.types import InputError
from core.version import CHARTFACTS_SCHEMA_VERSION, ENGINE_VERSION
from narrative.prompt import SECTIONS, PromptError
from narrative.service import NarrativeService
from render.adapter import chart_style_from_string, rashi_chart, varga_chart
from render.chart_svg import render, render_table
from render.pdf import PdfError, render_pdf

DESCRIPTION = """\
A deterministic Jyotish computation engine with a separately-validated narrative
layer.

**No number in any response is generated by a language model.** Every degree,
tithi, timestamp, dasha date, koot score and bala value comes from the
deterministic engine; the `/v1/narrative` endpoint receives computed facts and may
only phrase them, and a post-generation validator rejects prose containing any
figure absent from the facts.

Astronomical output is regression-tested against **दाते पंचांग (Date Panchang)**.
See `docs/GOLDEN_FILES.md` for the current verification status - at the time of
writing, agreement with the authority is scaffolded but not yet transcribed.

This is a traditional Jyotish interpretation tool. It is not a forecast of the
future, and it is not a substitute for medical, legal, financial or psychological
advice.
"""

app = FastAPI(
    title="jyotish-core",
    version=ENGINE_VERSION,
    description=DESCRIPTION,
    openapi_url="/openapi.json",
    docs_url="/docs",
    contact={"name": "jyotish-core"},
    license_info={"name": "AGPL-3.0-or-later"},
)

app.include_router(privacy.router)
app.include_router(geocode.router)

_settings = get_settings()
if _settings.cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(_settings.cors_origins),
        allow_methods=["GET", "POST", "DELETE"],
        allow_headers=["*"],
    )


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def _error(status_code: int, key: str, message: str, field: str | None = None) -> JSONResponse:
    return JSONResponse(
        status_code=status_code,
        content=ErrorResponse(
            errors=[ErrorDetail(key=key, message=message, field=field)]
        ).model_dump(),
    )


@app.exception_handler(InputError)
async def _input_error(_request: Any, exc: InputError) -> JSONResponse:
    """CLAUDE.md 3.1: reject silently-wrong input loudly."""
    return _error(status.HTTP_422_UNPROCESSABLE_ENTITY, "invalid_input", str(exc))


@app.exception_handler(CircumpolarError)
async def _circumpolar(_request: Any, exc: CircumpolarError) -> JSONResponse:
    """Sunrise is genuinely undefined, so the response says so.

    A 422 rather than a 500: the request is well-formed and the answer is that the
    quantity does not exist at that latitude on that date (CLAUDE.md 3.1).
    """
    return _error(
        status.HTTP_422_UNPROCESSABLE_ENTITY,
        "sunrise_undefined_at_this_latitude",
        f"{exc} The Hindu day begins at sunrise, so vara, the headline tithi and "
        "Ishtakaal are undefined here. This is not an error in the computation.",
    )


@app.exception_handler(ChartFactsError)
async def _facts_invalid(_request: Any, exc: ChartFactsError) -> JSONResponse:  # pragma: no cover
    """A document that fails its own schema is a server bug, not a client one."""
    return _error(status.HTTP_500_INTERNAL_SERVER_ERROR, "chartfacts_contract_violation", str(exc))


@app.exception_handler(PromptError)
async def _prompt_error(_request: Any, exc: PromptError) -> JSONResponse:
    return _error(status.HTTP_400_BAD_REQUEST, "unknown_section_or_locale", str(exc))


@app.exception_handler(PdfError)
async def _pdf_error(_request: Any, exc: PdfError) -> JSONResponse:  # pragma: no cover
    return _error(status.HTTP_500_INTERNAL_SERVER_ERROR, "pdf_render_failed", str(exc))


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------


@app.get("/health", response_model=HealthResponse, tags=["meta"])
def health(settings: Annotated[Settings, Depends(get_settings)]) -> HealthResponse:
    """Version and configuration. Includes the pinned ayanamsa constant.

    The constant, not just the name: CLAUDE.md 4.5 treats an ayanamsa redefinition
    as a breaking change, and an operator needs to be able to see which one is live
    without computing a chart.
    """
    info = build_ephemeris().info
    return HealthResponse(
        status="ok",
        engine_version=ENGINE_VERSION,
        chartfacts_schema_version=CHARTFACTS_SCHEMA_VERSION,
        ephemeris_provider=info.provider,
        ayanamsa_constant=info.ayanamsa_constant,
        authority="date_panchang",
        narrative_generation_enabled=settings.narrative_enabled,
        locales=list(SUPPORTED_LOCALES),
    )


# ---------------------------------------------------------------------------
# Panchang
# ---------------------------------------------------------------------------


@app.post("/v1/panchang", tags=["panchang"])
def panchang(
    birth: Annotated[BirthInput, Body()],
) -> dict[str, Any]:
    """The panchang of a day at a place.

    Needs no birth time: a day's panchang is a property of the date and place. When
    a time is supplied the response also carries the limbs *at that instant*,
    because the two differ and CLAUDE.md 4.3 requires both.
    """
    facts = _facts(birth)
    return {
        "panchang": facts["panchang"],
        "ephemeris": facts["ephemeris"],
        "confidence": facts["confidence"],
        "glossary": {
            ns: load_glossary(birth.locale)[ns]
            for ns in ("panchang", "tithi", "nakshatra", "yoga", "karana", "vara", "month")
        },
        "disclaimer": disclaimer(birth.locale),
    }


# ---------------------------------------------------------------------------
# Chart
# ---------------------------------------------------------------------------


@app.post("/v1/chart", response_model=ChartFactsResponse, tags=["chart"])
def chart(birth: Annotated[BirthInput, Body()]) -> ChartFactsResponse:
    """The full ChartFacts document, schema-validated before it leaves.

    The glossary rides alongside rather than merged in, so the document itself stays
    free of Devanagari (CLAUDE.md 5) while a client still renders in one round trip.
    """
    return ChartFactsResponse(
        facts=_facts(birth),
        glossary=load_glossary(birth.locale),
        disclaimer=disclaimer(birth.locale),
    )


@app.post("/v1/chart/svg", tags=["chart"], response_class=Response)
def chart_svg(
    birth: Annotated[BirthInput, Body()],
    style: Annotated[str | None, Query(description="north_indian | south_indian")] = None,
    varga: Annotated[str, Query(description="D1 or any emitted varga, e.g. D9")] = "D1",
    degrees: Annotated[bool, Query(description="print degrees in each cell")] = False,
    table: Annotated[bool, Query(description="return the accessible table instead")] = False,
) -> Response:
    """A rendered kundali. North Indian diamond by default (CLAUDE.md 8).

    ``table=true`` returns the semantic HTML table alternative that CLAUDE.md 8
    requires for screen readers - the same data, not a summary of it.
    """
    facts = _facts(birth)
    if "chart" not in facts:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "no chart without a birth time: the ascendant and houses are "
                "undefined, and CLAUDE.md 4.6 forbids defaulting to noon"
            ),
        )
    try:
        chart_style = chart_style_from_string(style)
    except ValueError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc

    data = (
        rashi_chart(facts, birth.locale)
        if varga.upper() == "D1"
        else varga_chart(facts, varga.upper(), birth.locale)
    )
    if table:
        glossary = load_glossary(birth.locale)["chart"]
        body = render_table(
            data, headers=(glossary["house"], glossary["rashi_chart"], glossary["kundali"])
        )
        return Response(content=body, media_type="text/html; charset=utf-8")
    body = render(data, chart_style, show_degrees=degrees, show_sav=varga.upper() == "D1")
    return Response(content=body, media_type="image/svg+xml")


@app.post("/v1/chart/pdf", tags=["chart"], response_class=Response)
def chart_pdf(
    birth: Annotated[BirthInput, Body()],
    style: Annotated[str | None, Query()] = None,
) -> Response:
    """A print-clean kundali sheet at A4, locale-aware (CLAUDE.md 8).

    Font glyph coverage for the locale is verified before rendering, because a
    missing Devanagari glyph produces a blank rather than an error
    (CLAUDE.md 2.2).
    """
    facts = _facts(birth)
    try:
        chart_style = chart_style_from_string(style)
    except ValueError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    pdf = render_pdf(facts, birth.locale, style=chart_style)
    safe_name = "".join(c for c in birth.name if c.isalnum() or c in " -_") or "kundali"
    return Response(
        content=pdf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}.pdf"'},
    )


# ---------------------------------------------------------------------------
# Milan
# ---------------------------------------------------------------------------


@app.post("/v1/milan", tags=["milan"])
def milan(request: Annotated[MilanInput, Body()]) -> dict[str, Any]:
    """Ashtakoot Guna Milan from two births.

    Returns per-koot scores with their reasons and any exception that applies -
    never a bare total, and never a verdict (CLAUDE.md 3.5, 6.7). Both Moon
    positions are computed here from full birth input rather than accepted as
    parameters, because accepting them would be accepting computed values.
    """
    bride_facts = _facts(request.bride)
    groom_facts = _facts(request.groom)
    for label, facts in (("bride", bride_facts), ("groom", groom_facts)):
        if "chart" not in facts:
            raise HTTPException(
                status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"{label}: Guna Milan needs the Moon's nakshatra, which needs a birth time",
            )

    result = compute_milan(
        bride_moon_rashi=_moon(bride_facts)["rashi"],
        bride_moon_nakshatra=_moon(bride_facts)["nakshatra"],
        groom_moon_rashi=_moon(groom_facts)["rashi"],
        groom_moon_nakshatra=_moon(groom_facts)["nakshatra"],
    )
    return {
        "koots": [
            {
                "koot": k.koot,
                "points": k.points,
                "max_points": k.max_points,
                "evidence": list(k.evidence),
            }
            for k in result.koots
        ],
        "total": result.total,
        "max_total": result.max_total,
        "exceptions": [
            {"koot": e.koot, "key": e.key, "evidence": list(e.evidence)} for e in result.exceptions
        ],
        # CLAUDE.md 6.7: information, never a verdict. Stated in the payload so a
        # client cannot present the total as a recommendation without ignoring it.
        "presentation_rule": "koot_scores_are_information_not_a_verdict",
        "glossary": load_glossary(request.locale)["milan"],
        "disclaimer": disclaimer(request.locale),
    }


def _moon(facts: dict[str, Any]) -> dict[str, Any]:
    return next(g for g in facts["chart"]["grahas"] if g["key"] == Graha.MOON.value)


# ---------------------------------------------------------------------------
# Dasha sub-periods
# ---------------------------------------------------------------------------


@app.get("/v1/dasha/subperiods", tags=["dasha"])
def dasha_subperiods(
    lord: Annotated[str, Query(description="the parent period's lord")],
    start_utc: Annotated[str, Query()],
    end_utc: Annotated[str, Query()],
    level: Annotated[int, Query(ge=1, le=3, description="the parent's level")],
) -> list[dict[str, Any]]:
    """The nine children of one dasha period.

    Exists so the UI's four-level tree (CLAUDE.md 8) can expand a level on demand.
    A full four-level tree is 7380 nodes, too many to ship with every chart and far
    too many to let a browser compute - CLAUDE.md N1 keeps every dasha date in the
    engine.

    The parent is reconstructed from its lord and bounds rather than from a birth
    input, because sub-period division is *proportional*: the children of a period
    depend only on its span and its lord, so nothing about the birth is needed and
    nothing about it need be sent.
    """
    try:
        parent_lord = Graha(lord)
    except ValueError as exc:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST, detail=f"unknown dasha lord {lord!r}"
        ) from exc
    try:
        start = dt.datetime.fromisoformat(start_utc.replace("Z", "+00:00"))
        end = dt.datetime.fromisoformat(end_utc.replace("Z", "+00:00"))
    except ValueError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    if end <= start:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="end_utc must follow start_utc")

    parent = DashaPeriod(level=level, lord=parent_lord, start_utc=start, end_utc=end)
    return [
        {
            "level": child.level,
            "lord": child.lord.value,
            "start_utc": iso_utc(child.start_utc),
            "end_utc": iso_utc(child.end_utc),
        }
        for child in subperiods(parent, YearLength.SOLAR_365_2425)
    ]


# ---------------------------------------------------------------------------
# Narrative
# ---------------------------------------------------------------------------


@app.post("/v1/narrative", response_model=NarrativeResponse, tags=["narrative"])
def narrative(
    request: Annotated[NarrativeRequest, Body()],
    service: Annotated[NarrativeService, Depends(get_narrative_service)],
    settings: Annotated[Settings, Depends(get_settings)],
) -> NarrativeResponse:
    """Validated prose for one or more sections.

    The facts are **recomputed here** from the birth input; a caller cannot supply
    them. Accepting facts would let a client feed the model arbitrary numbers,
    which is the exact hole CLAUDE.md N1 exists to close.

    Every returned section has passed the post-generation validator: the
    CLAUDE.md 6.6/6.7 blocklist for its locale, and a numeric-provenance check that
    rejects any figure absent from the facts.
    """
    locale = request.locale or request.birth.locale
    facts = _facts(request.birth)
    requested = tuple(request.sections) if request.sections else SECTIONS
    unknown = set(requested) - set(SECTIONS)
    if unknown:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            detail=f"unknown section(s) {sorted(unknown)}; known: {list(SECTIONS)}",
        )

    sections = service.generate_all(facts, locale, sections=requested)
    return NarrativeResponse(
        sections=[
            NarrativeSectionOut(
                section=s.section,
                locale=s.locale,
                text=s.text,
                is_refusal=s.is_refusal,
                cached=s.cached,
                model=s.model,
                prompt_version=s.prompt_version,
                warnings=list(s.warnings),
            )
            for s in sections
        ],
        disclaimer=disclaimer(locale),
        generation_enabled=settings.narrative_enabled,
    )


# ---------------------------------------------------------------------------
# Shared
# ---------------------------------------------------------------------------


def _facts(birth: BirthInput, *, now: dt.datetime | None = None) -> dict[str, Any]:
    """Compute and validate ChartFacts for a request.

    Validation runs on every response, not only in tests: a document that fails its
    own schema is a contract violation and must not reach a client
    (CLAUDE.md 5).
    """
    facts = build_chart_facts(compute_full_reading(birth.to_engine(), now=now or utc_now()))
    validate_chart_facts(facts)
    return facts
