/**
 * China rate book — GENERATED by `scripts/country-book.ts` from `scripts/rate-refresh/2026-10-china.json`.
 * Do not edit by hand: change the config (every figure carries its source there) and re-run the script.
 * Register of every rate (current v new, decision, basis): scripts/rate-refresh/china-2026-10/register.csv.
 */
import type { CountryBook } from '../country-books.js';

export const CHINA_BOOK: CountryBook = {
 "region": "CN",
 "asOf": "2026-10-10",
 "fxToGBP": 8.88,
 "currencySymbol": "¥",
 "labourGrades": {
  "forge": {
   "gbpPerHr": 3.57,
   "basis": "2×12 h model: (annual pay incl. OT & bonus 80,667 + employer SI & HPF at floor 17,932) ÷ 3,113 h. Included: pay incl. overtime (150% weekday, 200% rest day) and a 13th month; employer pension 16%, medical, unemployment, injury and housing fund at the city contribution floor; two 12-h shifts = 3,113 productive h/yr (24 days/month × 11 h worked, less 5 days leave). NOT included: meal / dorm allowances, training, absenteeism, severance accrual; social insurance on actual pay (≈ +¥1.3/h) — not sourced",
   "source": "https://www.stats.gov.cn/zs/tjwh/tjkw/tjqk/zgxxb/202605/P020260519307748967261.pdf",
   "confidence": "Medium"
  },
  "furnace": {
   "gbpPerHr": 3.57,
   "basis": "2×12 h model: (annual pay incl. OT & bonus 80,667 + employer SI & HPF at floor 17,932) ÷ 3,113 h. Included: pay incl. overtime (150% weekday, 200% rest day) and a 13th month; employer pension 16%, medical, unemployment, injury and housing fund at the city contribution floor; two 12-h shifts = 3,113 productive h/yr (24 days/month × 11 h worked, less 5 days leave). NOT included: meal / dorm allowances, training, absenteeism, severance accrual; social insurance on actual pay (≈ +¥1.3/h) — not sourced",
   "source": "https://www.stats.gov.cn/zs/tjwh/tjkw/tjqk/zgxxb/202605/P020260519307748967261.pdf",
   "confidence": "Medium"
  },
  "blow": {
   "gbpPerHr": 3.57,
   "basis": "2×12 h model: (annual pay incl. OT & bonus 80,667 + employer SI & HPF at floor 17,932) ÷ 3,113 h. Included: pay incl. overtime (150% weekday, 200% rest day) and a 13th month; employer pension 16%, medical, unemployment, injury and housing fund at the city contribution floor; two 12-h shifts = 3,113 productive h/yr (24 days/month × 11 h worked, less 5 days leave). NOT included: meal / dorm allowances, training, absenteeism, severance accrual; social insurance on actual pay (≈ +¥1.3/h) — not sourced",
   "source": "https://www.stats.gov.cn/zs/tjwh/tjkw/tjqk/zgxxb/202605/P020260519307748967261.pdf",
   "confidence": "Medium"
  },
  "roto": {
   "gbpPerHr": 3.57,
   "basis": "2×12 h model: (annual pay incl. OT & bonus 80,667 + employer SI & HPF at floor 17,932) ÷ 3,113 h. Included: pay incl. overtime (150% weekday, 200% rest day) and a 13th month; employer pension 16%, medical, unemployment, injury and housing fund at the city contribution floor; two 12-h shifts = 3,113 productive h/yr (24 days/month × 11 h worked, less 5 days leave). NOT included: meal / dorm allowances, training, absenteeism, severance accrual; social insurance on actual pay (≈ +¥1.3/h) — not sourced",
   "source": "https://www.stats.gov.cn/zs/tjwh/tjkw/tjqk/zgxxb/202605/P020260519307748967261.pdf",
   "confidence": "Medium"
  },
  "thermoform": {
   "gbpPerHr": 3.57,
   "basis": "2×12 h model: (annual pay incl. OT & bonus 80,667 + employer SI & HPF at floor 17,932) ÷ 3,113 h. Included: pay incl. overtime (150% weekday, 200% rest day) and a 13th month; employer pension 16%, medical, unemployment, injury and housing fund at the city contribution floor; two 12-h shifts = 3,113 productive h/yr (24 days/month × 11 h worked, less 5 days leave). NOT included: meal / dorm allowances, training, absenteeism, severance accrual; social insurance on actual pay (≈ +¥1.3/h) — not sourced",
   "source": "https://www.stats.gov.cn/zs/tjwh/tjkw/tjqk/zgxxb/202605/P020260519307748967261.pdf",
   "confidence": "Medium"
  },
  "trim-router": {
   "gbpPerHr": 3.73,
   "basis": "2×12 h model: (annual pay incl. OT & bonus 85,059 + employer SI & HPF at floor 17,932) ÷ 3,113 h. Included: pay incl. overtime (150% weekday, 200% rest day) and a 13th month; employer pension 16%, medical, unemployment, injury and housing fund at the city contribution floor; two 12-h shifts = 3,113 productive h/yr (24 days/month × 11 h worked, less 5 days leave). NOT included: meal / dorm allowances, training, absenteeism, severance accrual; social insurance on actual pay (≈ +¥1.3/h) — not sourced",
   "source": "labour.skilled.monthlyGross.clusterAvg",
   "confidence": "Medium"
  }
 },
 "materials": {
  "mat-dc01": {
   "gbpPerKg": 0.3648,
   "basis": "CR coil (DC01 / DC04): Shanghai 1.0 mm SPCC cold-rolled spot ¥3,239/t ex-VAT (Mysteel, 9 Oct 2026); direct",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09)",
   "confidence": "Medium"
  },
  "mat-dc04": {
   "gbpPerKg": 0.3648,
   "basis": "CR coil (DC01 / DC04): Shanghai 1.0 mm SPCC cold-rolled spot ¥3,239/t ex-VAT (Mysteel, 9 Oct 2026); direct",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09)",
   "confidence": "Medium"
  },
  "mat-dc05": {
   "gbpPerKg": 0.3648,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.000 (book £0.8 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-dc06": {
   "gbpPerKg": 0.3691,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.012 (book £0.85 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-if-dx56": {
   "gbpPerKg": 0.4342,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.190 (book £1 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-if-hs260": {
   "gbpPerKg": 0.4907,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.345 (book £1.13 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-bh260": {
   "gbpPerKg": 0.4777,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.310 (book £1.1 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-greensteel-dc01": {
   "gbpPerKg": 0.4777,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.310 (book £1.1 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-hsla340": {
   "gbpPerKg": 0.5167,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.417 (book £1.19 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-hsla420": {
   "gbpPerKg": 0.5602,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.536 (book £1.29 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-hsla550": {
   "gbpPerKg": 0.6036,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.655 (book £1.39 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-dp600": {
   "gbpPerKg": 0.5645,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.548 (book £1.3 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-dp780": {
   "gbpPerKg": 0.5949,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.631 (book £1.37 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-dp980": {
   "gbpPerKg": 0.6513,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.786 (book £1.5 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-dp1000": {
   "gbpPerKg": 0.6817,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.869 (book £1.57 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-trip780": {
   "gbpPerKg": 0.6296,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.726 (book £1.45 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-cp800": {
   "gbpPerKg": 0.6209,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.702 (book £1.43 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-ms1200": {
   "gbpPerKg": 0.6948,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.905 (book £1.6 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-ms1300": {
   "gbpPerKg": 0.7252,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.988 (book £1.67 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-ms1500": {
   "gbpPerKg": 0.7686,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×2.107 (book £1.77 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-qp980": {
   "gbpPerKg": 0.7512,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×2.060 (book £1.73 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-medmn1180": {
   "gbpPerKg": 0.7816,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×2.143 (book £1.8 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-22mnb5": {
   "gbpPerKg": 0.7773,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×2.131 (book £1.79 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-usibor1500": {
   "gbpPerKg": 0.8685,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×2.381 (book £2 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-usibor2000": {
   "gbpPerKg": 1.0421,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×2.857 (book £2.4 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-c67s-spring": {
   "gbpPerKg": 0.6948,
   "basis": "CR automotive grades: CR spot ¥3.24 × the book's grade premium over its DC01/DC04 mean (£0.84); Baosteel automotive extras (DP, 22MnB5, GA, ZnMg) not found; ladder ×1.905 (book £1.6 ÷ base £0.84)",
   "source": "https://www.mysteel.com/hot/563511.html (2026-10-09) ; https://m.mysteel.com/hot/426801.html (2026-10-10)",
   "confidence": "Low"
  },
  "mat-hrpo": {
   "gbpPerKg": 0.3538,
   "basis": "HR pickled & oiled: SPHC pickled spot ¥3,142/t ex-VAT (Mysteel, Sep 2026); direct",
   "source": "https://m.mysteel.com/hot/1478441.html (2026-09-18)",
   "confidence": "Medium"
  },
  "mat-s355mc": {
   "gbpPerKg": 0.3375,
   "basis": "HR structural: Shanghai 4.75 mm Q235 HRC ¥2,885/t ex-VAT (9 Oct 2026) × the book's premium over HRPO; S355MC / S420MC extras not found; ladder ×1.039 (book £0.8 ÷ base £0.77)",
   "source": "https://m.mysteel.com/hot/11675.html (2026-10-09)",
   "confidence": "Low"
  },
  "mat-s420mc": {
   "gbpPerKg": 0.346,
   "basis": "HR structural: Shanghai 4.75 mm Q235 HRC ¥2,885/t ex-VAT (9 Oct 2026) × the book's premium over HRPO; S355MC / S420MC extras not found; ladder ×1.065 (book £0.82 ÷ base £0.77)",
   "source": "https://m.mysteel.com/hot/11675.html (2026-10-09)",
   "confidence": "Low"
  },
  "mat-dc01-gi": {
   "gbpPerKg": 0.3937,
   "basis": "Coated sheet: Shanghai 1.0 mm DX51D+Z galvanised spot ¥3,496/t ex-VAT (29 Sep 2026) × the book's premium over DC01 GI; ladder ×1.000 (book £1.11 ÷ base £1.11)",
   "source": "https://m.mysteel.com/hot/39907.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-dc03-ga": {
   "gbpPerKg": 0.4079,
   "basis": "Coated sheet: Shanghai 1.0 mm DX51D+Z galvanised spot ¥3,496/t ex-VAT (29 Sep 2026) × the book's premium over DC01 GI; ladder ×1.036 (book £1.15 ÷ base £1.11)",
   "source": "https://m.mysteel.com/hot/39907.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-dc01-ze": {
   "gbpPerKg": 0.3937,
   "basis": "Coated sheet: Shanghai 1.0 mm DX51D+Z galvanised spot ¥3,496/t ex-VAT (29 Sep 2026) × the book's premium over DC01 GI; ladder ×1.000 (book £0.98 ÷ base £1.11)",
   "source": "https://m.mysteel.com/hot/39907.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-znni-eg": {
   "gbpPerKg": 0.4363,
   "basis": "Coated sheet: Shanghai 1.0 mm DX51D+Z galvanised spot ¥3,496/t ex-VAT (29 Sep 2026) × the book's premium over DC01 GI; ladder ×1.108 (book £1.23 ÷ base £1.11)",
   "source": "https://m.mysteel.com/hot/39907.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-zm-coated": {
   "gbpPerKg": 0.4256,
   "basis": "Coated sheet: Shanghai 1.0 mm DX51D+Z galvanised spot ¥3,496/t ex-VAT (29 Sep 2026) × the book's premium over DC01 GI; ladder ×1.081 (book £1.2 ÷ base £1.11)",
   "source": "https://m.mysteel.com/hot/39907.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-tinplate-etp": {
   "gbpPerKg": 0.4788,
   "basis": "Coated sheet: Shanghai 1.0 mm DX51D+Z galvanised spot ¥3,496/t ex-VAT (29 Sep 2026) × the book's premium over DC01 GI; ladder ×1.216 (book £1.35 ÷ base £1.11)",
   "source": "https://m.mysteel.com/hot/39907.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-steel1045": {
   "gbpPerKg": 0.3668,
   "basis": "45# medium-carbon bar: Shanghai 45# (C45) round bar ¥3,257/t ex-VAT (Mysteel, 24 Sep 2026); direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Medium"
  },
  "mat-steel-c45": {
   "gbpPerKg": 0.3668,
   "basis": "45# medium-carbon bar: Shanghai 45# (C45) round bar ¥3,257/t ex-VAT (Mysteel, 24 Sep 2026); direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Medium"
  },
  "mat-en8": {
   "gbpPerKg": 0.3668,
   "basis": "45# medium-carbon bar: Shanghai 45# (C45) round bar ¥3,257/t ex-VAT (Mysteel, 24 Sep 2026); direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Medium"
  },
  "mat-steel-c35": {
   "gbpPerKg": 0.3625,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×0.988 (book £0.85 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel1020": {
   "gbpPerKg": 0.3497,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×0.953 (book £0.82 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-a105": {
   "gbpPerKg": 0.3582,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×0.977 (book £0.84 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-c70s6": {
   "gbpPerKg": 0.3924,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×1.070 (book £0.92 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel1141": {
   "gbpPerKg": 0.4478,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×1.221 (book £1.05 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-en3-bar": {
   "gbpPerKg": 0.4009,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×1.093 (book £0.94 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-11smnpb30": {
   "gbpPerKg": 0.499,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×1.360 (book £1.17 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-30mnvs6": {
   "gbpPerKg": 0.4905,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-38mnvs6": {
   "gbpPerKg": 0.4905,
   "basis": "Carbon / micro-alloyed bar: 45# bar ¥3.26 × the book's premium over C45; 38MnVS / 1215 / A105 extras not found; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-41cr4": {
   "gbpPerKg": 0.3886,
   "basis": "40Cr: Shanghai 40Cr round bar ¥3,451/t ex-VAT (24 Sep 2026) — the GB equivalent of 41Cr4 / 5140; direct",
   "source": "https://m.mysteel.com/hot/13617.html (2026-09-24)",
   "confidence": "Medium"
  },
  "mat-steel-42crmo4": {
   "gbpPerKg": 0.4823,
   "basis": "42CrMo: Shanghai 42CrMo round bar ¥4,283/t ex-VAT (24 Sep 2026) — 42CrMo4 / 4140 (the book held the same grade at two prices); direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Medium"
  },
  "mat-steel4140": {
   "gbpPerKg": 0.4823,
   "basis": "42CrMo: Shanghai 42CrMo round bar ¥4,283/t ex-VAT (24 Sep 2026) — 42CrMo4 / 4140 (the book held the same grade at two prices); direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Medium"
  },
  "mat-steel-20mncr5": {
   "gbpPerKg": 0.4106,
   "basis": "Case-hardening bar: Shanghai 20CrMnTi round bar ¥3,646/t ex-VAT (24 Sep 2026) — the GB case-hardening workhorse, used for 20MnCr5 / 16MnCr5; direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-16mncr5": {
   "gbpPerKg": 0.4106,
   "basis": "Case-hardening bar: Shanghai 20CrMnTi round bar ¥3,646/t ex-VAT (24 Sep 2026) — the GB case-hardening workhorse, used for 20MnCr5 / 16MnCr5; direct",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-52100": {
   "gbpPerKg": 0.5929,
   "basis": "Bearing steel: GCr15 ex-mill ¥5,265/t ex-VAT (23 Sep 2026) — 52100 / 100Cr6; direct",
   "source": "https://m.mysteel.com/hot/13792.html (2026-09-23)",
   "confidence": "Low"
  },
  "mat-steel4340": {
   "gbpPerKg": 0.4344,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×0.901 (book £1.45 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel4130": {
   "gbpPerKg": 0.4793,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×0.994 (book £1.6 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel8620": {
   "gbpPerKg": 0.4494,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×0.932 (book £1.5 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-34crnimo6": {
   "gbpPerKg": 0.5422,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×1.124 (book £1.81 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-18crnimo7-6": {
   "gbpPerKg": 0.5602,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×1.161 (book £1.87 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-f22": {
   "gbpPerKg": 0.6291,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×1.304 (book £2.1 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-steel-300m": {
   "gbpPerKg": 1.1384,
   "basis": "Ni-Cr-Mo / Cr-Mo alloy bar: 42CrMo bar ¥4.28 × the book's premium over 42CrMo4 (Ni-bearing and aerospace grades: Chinese prices not found); ladder ×2.360 (book £3.8 ÷ base £1.61)",
   "source": "https://m.mysteel.com/hot/78153.html (2026-09-24)",
   "confidence": "Low"
  },
  "mat-ss304-bar": {
   "gbpPerKg": 1.3703,
   "basis": "304 stainless bar: 304 round bar ¥12,168/t ex-VAT (30 Sep 2026); direct",
   "source": "https://m.mysteel.com/hot/567231.html (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-ss304l-bar": {
   "gbpPerKg": 1.3703,
   "basis": "304 stainless bar: 304 round bar ¥12,168/t ex-VAT (30 Sep 2026); direct",
   "source": "https://m.mysteel.com/hot/567231.html (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-ss303": {
   "gbpPerKg": 1.4867,
   "basis": "303 free-machining bar: 304 bar ¥12.17 × the book's premium of 303 over 304 bar; ladder ×1.085 (book £3.83 ÷ base £3.53)",
   "source": "https://m.mysteel.com/hot/567231.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-ss316-sheet": {
   "gbpPerKg": 2.9847,
   "basis": "316L: 316L cold-rolled coil ¥26,504/t ex-VAT (Wuxi, 30 Sep 2026); bar taken at the coil price (316L bar not found); direct",
   "source": "https://list1.m.mysteel.com/zhishi/316bxglsjg.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-ss316l": {
   "gbpPerKg": 2.9847,
   "basis": "316L: 316L cold-rolled coil ¥26,504/t ex-VAT (Wuxi, 30 Sep 2026); bar taken at the coil price (316L bar not found); direct",
   "source": "https://list1.m.mysteel.com/zhishi/316bxglsjg.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-ss316l-bar": {
   "gbpPerKg": 2.9847,
   "basis": "316L: 316L cold-rolled coil ¥26,504/t ex-VAT (Wuxi, 30 Sep 2026); bar taken at the coil price (316L bar not found); direct",
   "source": "https://list1.m.mysteel.com/zhishi/316bxglsjg.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-ss304-sheet": {
   "gbpPerKg": 1.4364,
   "basis": "304 sheet: 304 CR 2B: Wuxi spot ¥12,146/t and Tisco cut-edge ¥13,363/t ex-VAT (Sep–Oct 2026) — mean; direct",
   "source": "https://list1.mysteel.com/zhishi/wx304bxgjgzxxqzs.html (2026-10-08) ; https://www.ccmn.cn/bxg/304/ (2026-09 (late; date not shown in result))",
   "confidence": "Medium"
  },
  "mat-ss301-spring": {
   "gbpPerKg": 1.8644,
   "basis": "301 spring strip: 304 sheet ¥12.75 × the book's premium of 301 over 304L sheet; ladder ×1.298 (book £4.53 ÷ base £3.49)",
   "source": "https://list1.mysteel.com/zhishi/wx304bxgjgzxxqzs.html (2026-10-08)",
   "confidence": "Low"
  },
  "mat-aisi430": {
   "gbpPerKg": 0.7574,
   "basis": "430 ferritic sheet: 430 CR coil ¥6,726/t ex-VAT (9 Oct 2026); direct",
   "source": "https://m.mysteel.com/hot/580230.html (2026-10-09)",
   "confidence": "Medium"
  },
  "mat-ss409l-sheet": {
   "gbpPerKg": 0.7524,
   "basis": "409L / 441 ferritic sheet: 409L CR ¥6,681/t ex-VAT (Jun 2026 — stale); 441 at the book's premium over 409L; ladder ×1.000 (book £2.85 ÷ base £2.85)",
   "source": "https://hq.smm.cn/h5/sus-400sus-price (2026-06)",
   "confidence": "Low"
  },
  "mat-ss441-sheet": {
   "gbpPerKg": 0.8342,
   "basis": "409L / 441 ferritic sheet: 409L CR ¥6,681/t ex-VAT (Jun 2026 — stale); 441 at the book's premium over 409L; ladder ×1.109 (book £3.16 ÷ base £2.85)",
   "source": "https://hq.smm.cn/h5/sus-400sus-price (2026-06)",
   "confidence": "Low"
  },
  "mat-ss410-bar": {
   "gbpPerKg": 0.9258,
   "basis": "Martensitic stainless bar (410 / 416 / 420 / 431): 430 CR ¥6.73 (13–17% Cr, the nearest priced chromium stainless) × the book's premium of each bar over 430 sheet — martensitic bar prices not found; ladder ×1.222 (book £3.63 ÷ base £2.97)",
   "source": "https://m.mysteel.com/hot/580230.html (2026-10-09)",
   "confidence": "Low"
  },
  "mat-ss416-bar": {
   "gbpPerKg": 1.0023,
   "basis": "Martensitic stainless bar (410 / 416 / 420 / 431): 430 CR ¥6.73 (13–17% Cr, the nearest priced chromium stainless) × the book's premium of each bar over 430 sheet — martensitic bar prices not found; ladder ×1.323 (book £3.93 ÷ base £2.97)",
   "source": "https://m.mysteel.com/hot/580230.html (2026-10-09)",
   "confidence": "Low"
  },
  "mat-ss420-bar": {
   "gbpPerKg": 0.9283,
   "basis": "Martensitic stainless bar (410 / 416 / 420 / 431): 430 CR ¥6.73 (13–17% Cr, the nearest priced chromium stainless) × the book's premium of each bar over 430 sheet — martensitic bar prices not found; ladder ×1.226 (book £3.64 ÷ base £2.97)",
   "source": "https://m.mysteel.com/hot/580230.html (2026-10-09)",
   "confidence": "Low"
  },
  "mat-ss431-bar": {
   "gbpPerKg": 1.0074,
   "basis": "Martensitic stainless bar (410 / 416 / 420 / 431): 430 CR ¥6.73 (13–17% Cr, the nearest priced chromium stainless) × the book's premium of each bar over 430 sheet — martensitic bar prices not found; ladder ×1.330 (book £3.95 ÷ base £2.97)",
   "source": "https://m.mysteel.com/hot/580230.html (2026-10-09)",
   "confidence": "Low"
  },
  "mat-nogo-m270-35a": {
   "gbpPerKg": 0.583,
   "basis": "NO electrical steel 0.35 mm: 35W300 non-oriented ¥4.89–5.18/kg ex-VAT (Sep 2026; upper end used) — for M270-35A / M330-35A; direct",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-m330-35a": {
   "gbpPerKg": 0.583,
   "basis": "NO electrical steel 0.35 mm: 35W300 non-oriented ¥4.89–5.18/kg ex-VAT (Sep 2026; upper end used) — for M270-35A / M330-35A; direct",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-m235-35a": {
   "gbpPerKg": 0.6668,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×1.144 (book £1.99 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-no27-27a": {
   "gbpPerKg": 0.8175,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×1.402 (book £2.44 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-no25-25a": {
   "gbpPerKg": 0.9181,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×1.575 (book £2.74 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-no20-20a": {
   "gbpPerKg": 1.1526,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×1.977 (book £3.44 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-no15-15a": {
   "gbpPerKg": 1.3201,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×2.264 (book £3.94 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-no10-10a": {
   "gbpPerKg": 1.8562,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×3.184 (book £5.54 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-hsno-rotor-700": {
   "gbpPerKg": 0.8845,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×1.517 (book £2.64 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-hsno-rotor-960": {
   "gbpPerKg": 1.0856,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×1.862 (book £3.24 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-uhsno-1100": {
   "gbpPerKg": 1.2196,
   "basis": "NO electrical steel, premium / thin / high-strength: 35W300 ¥5.18 × the book's premium over M330-35A (Chinese 0.27–0.10 mm and HS rotor grade prices not found); ladder ×2.092 (book £3.64 ÷ base £1.74)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-m700-65a": {
   "gbpPerKg": 0.4435,
   "basis": "NO electrical steel 0.50 / 0.65 mm: 50W800 non-oriented ¥3,938/t ex-VAT (Sep 2026) × the book's premium over M700-65A, floored at 50W800; ladder ×1.000 (book £1.14 ÷ base £1.14)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-m600-50a": {
   "gbpPerKg": 0.4629,
   "basis": "NO electrical steel 0.50 / 0.65 mm: 50W800 non-oriented ¥3,938/t ex-VAT (Sep 2026) × the book's premium over M700-65A, floored at 50W800; ladder ×1.044 (book £1.19 ÷ base £1.14)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-m470-50a": {
   "gbpPerKg": 0.4824,
   "basis": "NO electrical steel 0.50 / 0.65 mm: 50W800 non-oriented ¥3,938/t ex-VAT (Sep 2026) × the book's premium over M700-65A, floored at 50W800; ladder ×1.088 (book £1.24 ÷ base £1.14)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-nogo-m400-50a": {
   "gbpPerKg": 0.5018,
   "basis": "NO electrical steel 0.50 / 0.65 mm: 50W800 non-oriented ¥3,938/t ex-VAT (Sep 2026) × the book's premium over M700-65A, floored at 50W800; ladder ×1.132 (book £1.29 ÷ base £1.14)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-m250-50a": {
   "gbpPerKg": 0.568,
   "basis": "NO electrical steel 0.50 / 0.65 mm: 50W800 non-oriented ¥3,938/t ex-VAT (Sep 2026) × the book's premium over M700-65A, floored at 50W800; ladder ×1.281 (book £1.46 ÷ base £1.14)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-no-semiproc-50": {
   "gbpPerKg": 0.4435,
   "basis": "NO electrical steel 0.50 / 0.65 mm: 50W800 non-oriented ¥3,938/t ex-VAT (Sep 2026) × the book's premium over M700-65A, floored at 50W800; ladder ×1.000 (book £1.09 ÷ base £1.14)",
   "source": "https://m.mysteel.com/hot/3849.html (2026-09-20)",
   "confidence": "Low"
  },
  "mat-gjs500": {
   "gbpPerKg": 0.3029,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.000/kg (book £0.86 − base £0.86) = +¥0.00",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjs400": {
   "gbpPerKg": 0.2629,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£-0.040/kg (book £0.82 − base £0.86) = +¥-0.36",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjs450-ssf": {
   "gbpPerKg": 0.2729,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£-0.030/kg (book £0.83 − base £0.86) = +¥-0.27",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjs500-14": {
   "gbpPerKg": 0.2829,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£-0.020/kg (book £0.84 − base £0.86) = +¥-0.18",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjs600": {
   "gbpPerKg": 0.3429,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.040/kg (book £0.9 − base £0.86) = +¥0.36",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjs700": {
   "gbpPerKg": 0.3929,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.090/kg (book £0.95 − base £0.86) = +¥0.80",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjs350-lt": {
   "gbpPerKg": 0.3129,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.010/kg (book £0.87 − base £0.86) = +¥0.09",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-simo": {
   "gbpPerKg": 0.7929,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.490/kg (book £1.35 − base £0.86) = +¥4.35",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-adi": {
   "gbpPerKg": 1.0229,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.720/kg (book £1.58 − base £0.86) = +¥6.39",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjv450": {
   "gbpPerKg": 0.5629,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.260/kg (book £1.12 − base £0.86) = +¥2.31",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjv500": {
   "gbpPerKg": 0.5929,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge ¥2.69/kg (Q10 nodular pig ¥2.80 + heavy scrap ¥2.05 + returns, RE-FeSi nodulariser + inoculant; the mix is an engineering assumption, arithmetic in research) + the book's grade premium in £/kg at ¥8.88/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +£0.290/kg (book £1.15 − base £0.86) = +¥2.58",
   "source": "https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://m.mysteel.com/hot/1487195.html (2026-09-30) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-gjl250": {
   "gbpPerKg": 0.2646,
   "basis": "Grey / malleable iron (charge): Grey-iron charge ¥2.35/kg (Z18 casting pig ¥2.61 + heavy scrap + returns; engineering-assumption mix) × the book's grade premium over GJL-250; ladder ×1.000 (book £0.64 ÷ base £0.64)",
   "source": "https://www.mysteel.com/hot/1486014.html (2026-09-30) ; https://www.mysteel.com/hot/1486014.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-gjl150": {
   "gbpPerKg": 0.2316,
   "basis": "Grey / malleable iron (charge): Grey-iron charge ¥2.35/kg (Z18 casting pig ¥2.61 + heavy scrap + returns; engineering-assumption mix) × the book's grade premium over GJL-250; ladder ×0.875 (book £0.56 ÷ base £0.64)",
   "source": "https://www.mysteel.com/hot/1486014.html (2026-09-30) ; https://www.mysteel.com/hot/1486014.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-gjl200": {
   "gbpPerKg": 0.2481,
   "basis": "Grey / malleable iron (charge): Grey-iron charge ¥2.35/kg (Z18 casting pig ¥2.61 + heavy scrap + returns; engineering-assumption mix) × the book's grade premium over GJL-250; ladder ×0.938 (book £0.6 ÷ base £0.64)",
   "source": "https://www.mysteel.com/hot/1486014.html (2026-09-30) ; https://www.mysteel.com/hot/1486014.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-gjl300": {
   "gbpPerKg": 0.2894,
   "basis": "Grey / malleable iron (charge): Grey-iron charge ¥2.35/kg (Z18 casting pig ¥2.61 + heavy scrap + returns; engineering-assumption mix) × the book's grade premium over GJL-250; ladder ×1.094 (book £0.7 ÷ base £0.64)",
   "source": "https://www.mysteel.com/hot/1486014.html (2026-09-30) ; https://www.mysteel.com/hot/1486014.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-gjl350": {
   "gbpPerKg": 0.306,
   "basis": "Grey / malleable iron (charge): Grey-iron charge ¥2.35/kg (Z18 casting pig ¥2.61 + heavy scrap + returns; engineering-assumption mix) × the book's grade premium over GJL-250; ladder ×1.156 (book £0.74 ÷ base £0.64)",
   "source": "https://www.mysteel.com/hot/1486014.html (2026-09-30) ; https://www.mysteel.com/hot/1486014.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-gjmb350": {
   "gbpPerKg": 0.2729,
   "basis": "Grey / malleable iron (charge): Grey-iron charge ¥2.35/kg (Z18 casting pig ¥2.61 + heavy scrap + returns; engineering-assumption mix) × the book's grade premium over GJL-250; ladder ×1.031 (book £0.66 ÷ base £0.64)",
   "source": "https://www.mysteel.com/hot/1486014.html (2026-09-30) ; https://www.mysteel.com/hot/1486014.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-gs-c25": {
   "gbpPerKg": 0.2432,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ¥2.16/kg (heavy melting scrap ¥2.05, Mysteel 45-city, + deoxidation) + the book's premium in £/kg (Cr–Mo); ladder +£0.000/kg (book £2.1 − base £2.1) = +¥0.00",
   "source": "https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-astm-a216-wcb": {
   "gbpPerKg": 0.2432,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ¥2.16/kg (heavy melting scrap ¥2.05, Mysteel 45-city, + deoxidation) + the book's premium in £/kg (Cr–Mo); ladder +£0.000/kg (book £2.1 − base £2.1) = +¥0.00",
   "source": "https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-g20mn5": {
   "gbpPerKg": 0.2432,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ¥2.16/kg (heavy melting scrap ¥2.05, Mysteel 45-city, + deoxidation) + the book's premium in £/kg (Cr–Mo); ladder +£0.000/kg (book £2.1 − base £2.1) = +¥0.00",
   "source": "https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-g42crmo4": {
   "gbpPerKg": 0.3832,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ¥2.16/kg (heavy melting scrap ¥2.05, Mysteel 45-city, + deoxidation) + the book's premium in £/kg (Cr–Mo); ladder +£0.140/kg (book £2.24 − base £2.1) = +¥1.24",
   "source": "https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07) ; https://news.mysteel.com/a/26100711/92F88C485B219078.html (2026-10-07)",
   "confidence": "Low"
  },
  "mat-ss304-cast": {
   "gbpPerKg": 0.9707,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ¥8.62/kg (304 scrap ¥8.36 + melt trim; virgin-alloy upper bound ¥14.9) + the book's premium in £/kg (Mo / Ni / Cr); ladder +£0.000/kg (book £5.17 − base £5.17) = +¥0.00",
   "source": "https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29) ; https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-cf8m-cast": {
   "gbpPerKg": 2.0607,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ¥8.62/kg (304 scrap ¥8.36 + melt trim; virgin-alloy upper bound ¥14.9) + the book's premium in £/kg (Mo / Ni / Cr); ladder +£1.090/kg (book £6.26 − base £5.17) = +¥9.68",
   "source": "https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29) ; https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-ca6nm-cast": {
   "gbpPerKg": 0.7907,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ¥8.62/kg (304 scrap ¥8.36 + melt trim; virgin-alloy upper bound ¥14.9) + the book's premium in £/kg (Mo / Ni / Cr); ladder +£-0.180/kg (book £4.99 − base £5.17) = +¥-1.60",
   "source": "https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29) ; https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-cd4mcun-cast": {
   "gbpPerKg": 2.3107,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ¥8.62/kg (304 scrap ¥8.36 + melt trim; virgin-alloy upper bound ¥14.9) + the book's premium in £/kg (Mo / Ni / Cr); ladder +£1.340/kg (book £6.51 − base £5.17) = +¥11.90",
   "source": "https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29) ; https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-gx40crnisi25-20": {
   "gbpPerKg": 2.4507,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ¥8.62/kg (304 scrap ¥8.36 + melt trim; virgin-alloy upper bound ¥14.9) + the book's premium in £/kg (Mo / Ni / Cr); ladder +£1.480/kg (book £6.65 − base £5.17) = +¥13.14",
   "source": "https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29) ; https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-17-4ph-cast": {
   "gbpPerKg": 5.4007,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ¥8.62/kg (304 scrap ¥8.36 + melt trim; virgin-alloy upper bound ¥14.9) + the book's premium in £/kg (Mo / Ni / Cr); ladder +£4.430/kg (book £9.6 − base £5.17) = +¥39.34",
   "source": "https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29) ; https://list1.mysteel.com/zhishi/ntjgzst25884.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-ni-resist-d2": {
   "gbpPerKg": 2.6919,
   "basis": "Ni-Resist D-2 (charge): 0.20 × Ni ¥107.65 (Changjiang, 9 Oct) + 0.02 × Cr ¥13.80 (HC FeCr) + 0.78 × ductile charge ¥2.69; direct",
   "source": "http://news.10jqka.com.cn/20261009/c680512152.shtml (2026-10-09) ; https://m.mysteel.com/zta/gaotangetie/ (2026-09)",
   "confidence": "Low"
  },
  "mat-ni-resist-d5s": {
   "gbpPerKg": 4.4773,
   "basis": "Ni-Resist D-5S (charge): 0.35 × Ni + 0.02 × Cr + 0.04 kg FeSi75 ¥5.442 + 0.59 × ductile charge; direct",
   "source": "http://news.10jqka.com.cn/20261009/c680512152.shtml (2026-10-09)",
   "confidence": "Low"
  },
  "mat-hicr-white": {
   "gbpPerKg": 0.5611,
   "basis": "High-Cr white iron (charge): 0.23 × Cr ¥13.80 + 0.77 × grey charge ¥2.35; direct",
   "source": "https://m.mysteel.com/zta/gaotangetie/ (2026-09)",
   "confidence": "Low"
  },
  "mat-adc12": {
   "gbpPerKg": 2.4414,
   "basis": "Secondary cast aluminium (ingot): SMM ADC12 ¥21,680/t ex-VAT (30 Sep 2026) × the book's premium over ADC12 (Mysteel Foshan A380 ¥22.30, 1 Sep, agrees); ladder ×1.000 (book £2.75 ÷ base £2.75)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://list1.m.mysteel.com/zhishi/lhjgfjg.html (2026-09-01)",
   "confidence": "Medium"
  },
  "mat-a380": {
   "gbpPerKg": 2.4858,
   "basis": "Secondary cast aluminium (ingot): SMM ADC12 ¥21,680/t ex-VAT (30 Sep 2026) × the book's premium over ADC12 (Mysteel Foshan A380 ¥22.30, 1 Sep, agrees); ladder ×1.018 (book £2.8 ÷ base £2.75)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://list1.m.mysteel.com/zhishi/lhjgfjg.html (2026-09-01)",
   "confidence": "Medium"
  },
  "mat-a413": {
   "gbpPerKg": 2.4414,
   "basis": "Secondary cast aluminium (ingot): SMM ADC12 ¥21,680/t ex-VAT (30 Sep 2026) × the book's premium over ADC12 (Mysteel Foshan A380 ¥22.30, 1 Sep, agrees); ladder ×1.000 (book £2.75 ÷ base £2.75)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://list1.m.mysteel.com/zhishi/lhjgfjg.html (2026-09-01)",
   "confidence": "Medium"
  },
  "mat-a319": {
   "gbpPerKg": 2.6368,
   "basis": "Secondary cast aluminium (ingot): SMM ADC12 ¥21,680/t ex-VAT (30 Sep 2026) × the book's premium over ADC12 (Mysteel Foshan A380 ¥22.30, 1 Sep, agrees); ladder ×1.080 (book £2.97 ÷ base £2.75)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://list1.m.mysteel.com/zhishi/lhjgfjg.html (2026-09-01)",
   "confidence": "Medium"
  },
  "mat-lm4": {
   "gbpPerKg": 2.5835,
   "basis": "Secondary cast aluminium (ingot): SMM ADC12 ¥21,680/t ex-VAT (30 Sep 2026) × the book's premium over ADC12 (Mysteel Foshan A380 ¥22.30, 1 Sep, agrees); ladder ×1.058 (book £2.91 ÷ base £2.75)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://list1.m.mysteel.com/zhishi/lhjgfjg.html (2026-09-01)",
   "confidence": "Medium"
  },
  "mat-en-ac-46200": {
   "gbpPerKg": 2.5302,
   "basis": "Secondary cast aluminium (ingot): SMM ADC12 ¥21,680/t ex-VAT (30 Sep 2026) × the book's premium over ADC12 (Mysteel Foshan A380 ¥22.30, 1 Sep, agrees); ladder ×1.036 (book £2.85 ÷ base £2.75)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://list1.m.mysteel.com/zhishi/lhjgfjg.html (2026-09-01)",
   "confidence": "Medium"
  },
  "mat-adc12-secondary": {
   "gbpPerKg": 2.4414,
   "basis": "Secondary ADC12: SMM ADC12 ¥21.68 — the book's \"secondary\" ¥18.12 sat below the market it is; direct",
   "source": "https://www.smm.com.cn/price (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-lm25": {
   "gbpPerKg": 2.4122,
   "basis": "A356 / AlSi7Mg: SMM A356.2 ingot ¥21,420/t ex-VAT (30 Sep 2026); direct",
   "source": "https://www.smm.com.cn/price (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-a365": {
   "gbpPerKg": 2.4122,
   "basis": "A356 / AlSi7Mg: SMM A356.2 ingot ¥21,420/t ex-VAT (30 Sep 2026); direct",
   "source": "https://www.smm.com.cn/price (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-alsi10mg": {
   "gbpPerKg": 2.4122,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.000 (book £2.89 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-a390": {
   "gbpPerKg": 2.6712,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.107 (book £3.3 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-a357": {
   "gbpPerKg": 2.5902,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.074 (book £3.2 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-lm6": {
   "gbpPerKg": 2.4122,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.000 (book £2.92 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-almg5-cast": {
   "gbpPerKg": 2.4931,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.034 (book £3.08 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-a206": {
   "gbpPerKg": 2.9464,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.221 (book £3.64 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-en-ac-45300": {
   "gbpPerKg": 2.5174,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.044 (book £3.11 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-lm13": {
   "gbpPerKg": 2.4931,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.034 (book £3.08 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-aural5": {
   "gbpPerKg": 2.485,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.030 (book £3.07 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-silafont36": {
   "gbpPerKg": 2.5093,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.040 (book £3.1 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-castasil37": {
   "gbpPerKg": 2.4526,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.017 (book £3.03 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-magsimal59": {
   "gbpPerKg": 2.5498,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.057 (book £3.15 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-al-hpdc-lowco2": {
   "gbpPerKg": 2.4284,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.007 (book £3 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-htf-gigacast": {
   "gbpPerKg": 2.6712,
   "basis": "Primary-based cast aluminium: A356 ¥21.42 × the book's premium over LM25, floored at A356 (AlSi10Mg, structural HPDC and giga-casting alloy prices not found; A00 ¥21.47); ladder ×1.107 (book £3.3 ÷ base £2.98)",
   "source": "https://www.smm.com.cn/price (2026-09-30) ; https://finance.sina.com.cn/money/future/indu/2026-09-30/doc-initqzmc2066184.shtml (2026-09 (article 2026-09-30))",
   "confidence": "Low"
  },
  "mat-c101-bar": {
   "gbpPerKg": 11.116,
   "basis": "ETP copper bar / sheet (floor): Changjiang 1# copper ¥98,710/t ex-VAT (30 Sep 2026) — the book's bar and sheet ¥96.78 were below the copper they contain; floor (raised to metal content)",
   "source": "https://m.ccmn.cn/ (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-c110-copper": {
   "gbpPerKg": 11.116,
   "basis": "ETP copper bar / sheet (floor): Changjiang 1# copper ¥98,710/t ex-VAT (30 Sep 2026) — the book's bar and sheet ¥96.78 were below the copper they contain; floor (raised to metal content)",
   "source": "https://m.ccmn.cn/ (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-brass-cz121": {
   "gbpPerKg": 7.4538,
   "basis": "Free-machining / forging brass rod: HPb59-1 brass rod ¥66,190/t ex-VAT (Ningbo, 29 Sep 2026) — CW614N / CW617N equivalent; direct",
   "source": "https://list1.mysteel.com/zhishi/nbtbjgzxxq.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-brass-cz122-forge": {
   "gbpPerKg": 7.4538,
   "basis": "Free-machining / forging brass rod: HPb59-1 brass rod ¥66,190/t ex-VAT (Ningbo, 29 Sep 2026) — CW614N / CW617N equivalent; direct",
   "source": "https://list1.mysteel.com/zhishi/nbtbjgzxxq.html (2026-09-29)",
   "confidence": "Medium"
  },
  "mat-cz108-brass": {
   "gbpPerKg": 8.3716,
   "basis": "70/30 and 63/37 brass sheet: H62 brass rod ¥74,340/t ex-VAT (Ningbo, 29 Sep) × the book's premium of CZ108 sheet — H62 is the nearest priced CuZn37; direct",
   "source": "https://list1.mysteel.com/zhishi/nbtbjgzxxq.html (2026-09-29)",
   "confidence": "Low"
  },
  "mat-bronze-c905": {
   "gbpPerKg": 13.9742,
   "basis": "Phosphor / tin bronze (floor): Metal content 0.89 × Cu ¥98.71 + 0.105 × Sn ¥345.13; floor (raised to metal content)",
   "source": "https://m.ccmn.cn/ (2026-09-30) ; https://news.metal.com/newscontent/104146823 (2026-10-09)",
   "confidence": "Low"
  },
  "mat-zamak3": {
   "gbpPerKg": 2.705,
   "basis": "Zamak 3: No.3 zinc alloy ingot ¥24,020/t ex-VAT (SMM, 30 Sep 2026); direct",
   "source": "https://list1.m.mysteel.com/zhishi/2026nxhjjgylb.html (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-zamak5": {
   "gbpPerKg": 2.7613,
   "basis": "Zamak 5 / 2 / ZA: No.5 zinc alloy ingot ¥24,520/t ex-VAT (30 Sep 2026); Zamak 2 and ZA-8 / ZA-27 × the book's premium over Zamak 5; ladder ×1.000 (book £3.24 ÷ base £3.24)",
   "source": "https://list1.m.mysteel.com/zhishi/2026nxhjjgylb.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-zamak2": {
   "gbpPerKg": 2.9232,
   "basis": "Zamak 5 / 2 / ZA: No.5 zinc alloy ingot ¥24,520/t ex-VAT (30 Sep 2026); Zamak 2 and ZA-8 / ZA-27 × the book's premium over Zamak 5; ladder ×1.059 (book £3.43 ÷ base £3.24)",
   "source": "https://list1.m.mysteel.com/zhishi/2026nxhjjgylb.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-za8": {
   "gbpPerKg": 2.9828,
   "basis": "Zamak 5 / 2 / ZA: No.5 zinc alloy ingot ¥24,520/t ex-VAT (30 Sep 2026); Zamak 2 and ZA-8 / ZA-27 × the book's premium over Zamak 5; ladder ×1.080 (book £3.5 ÷ base £3.24)",
   "source": "https://list1.m.mysteel.com/zhishi/2026nxhjjgylb.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-za27": {
   "gbpPerKg": 3.0936,
   "basis": "Zamak 5 / 2 / ZA: No.5 zinc alloy ingot ¥24,520/t ex-VAT (30 Sep 2026); Zamak 2 and ZA-8 / ZA-27 × the book's premium over Zamak 5; ladder ×1.120 (book £3.63 ÷ base £3.24)",
   "source": "https://list1.m.mysteel.com/zhishi/2026nxhjjgylb.html (2026-09-30)",
   "confidence": "Low"
  },
  "mat-mag-az91": {
   "gbpPerKg": 1.8041,
   "basis": "Magnesium die-cast alloys: AZ91D ingot ¥16.02/kg ex-VAT (Jul 2026); Mg ingot ¥13.72 (Fugu, 9 Oct) agrees; AM60 / AM50 / AE44 × the book's premium over AZ91D; ladder ×1.000 (book £3.81 ÷ base £3.81)",
   "source": "https://hq.91jinshu.com/zd91dmeihejin/202607/52846.html (2026-07-23) ; https://www.sohu.com/a/1085524211_121123889 (2026-10-09)",
   "confidence": "Low"
  },
  "mat-mag-am60": {
   "gbpPerKg": 1.733,
   "basis": "Magnesium die-cast alloys: AZ91D ingot ¥16.02/kg ex-VAT (Jul 2026); Mg ingot ¥13.72 (Fugu, 9 Oct) agrees; AM60 / AM50 / AE44 × the book's premium over AZ91D; ladder ×0.961 (book £3.66 ÷ base £3.81)",
   "source": "https://hq.91jinshu.com/zd91dmeihejin/202607/52846.html (2026-07-23) ; https://www.sohu.com/a/1085524211_121123889 (2026-10-09)",
   "confidence": "Low"
  },
  "mat-mag-am50": {
   "gbpPerKg": 1.7567,
   "basis": "Magnesium die-cast alloys: AZ91D ingot ¥16.02/kg ex-VAT (Jul 2026); Mg ingot ¥13.72 (Fugu, 9 Oct) agrees; AM60 / AM50 / AE44 × the book's premium over AZ91D; ladder ×0.974 (book £3.71 ÷ base £3.81)",
   "source": "https://hq.91jinshu.com/zd91dmeihejin/202607/52846.html (2026-07-23) ; https://www.sohu.com/a/1085524211_121123889 (2026-10-09)",
   "confidence": "Low"
  },
  "mat-mag-ae44": {
   "gbpPerKg": 2.377,
   "basis": "Magnesium die-cast alloys: AZ91D ingot ¥16.02/kg ex-VAT (Jul 2026); Mg ingot ¥13.72 (Fugu, 9 Oct) agrees; AM60 / AM50 / AE44 × the book's premium over AZ91D; ladder ×1.318 (book £5.02 ÷ base £3.81)",
   "source": "https://hq.91jinshu.com/zd91dmeihejin/202607/52846.html (2026-07-23) ; https://www.sohu.com/a/1085524211_121123889 (2026-10-09)",
   "confidence": "Low"
  },
  "mat-pp-homo": {
   "gbpPerKg": 0.9899,
   "basis": "PP family: PP T30S ¥8.79/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over PP homopolymer (copolymer K8003 not found); ladder ×1.000 (book £0.99 ÷ base £0.99)",
   "source": "http://www.chemrp.com/info/detail-20261001-6294429.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pp": {
   "gbpPerKg": 1.1498,
   "basis": "PP family: PP T30S ¥8.79/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over PP homopolymer (copolymer K8003 not found); ladder ×1.162 (book £1.15 ÷ base £0.99)",
   "source": "http://www.chemrp.com/info/detail-20261001-6294429.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pp-impact": {
   "gbpPerKg": 1.0399,
   "basis": "PP family: PP T30S ¥8.79/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over PP homopolymer (copolymer K8003 not found); ladder ×1.051 (book £1.04 ÷ base £0.99)",
   "source": "http://www.chemrp.com/info/detail-20261001-6294429.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pp-bm": {
   "gbpPerKg": 1.1098,
   "basis": "PP family: PP T30S ¥8.79/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over PP homopolymer (copolymer K8003 not found); ladder ×1.121 (book £1.11 ÷ base £0.99)",
   "source": "http://www.chemrp.com/info/detail-20261001-6294429.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-ppr-pipe": {
   "gbpPerKg": 1.1698,
   "basis": "PP family: PP T30S ¥8.79/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over PP homopolymer (copolymer K8003 not found); ladder ×1.182 (book £1.17 ÷ base £0.99)",
   "source": "http://www.chemrp.com/info/detail-20261001-6294429.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pp-roto": {
   "gbpPerKg": 1.4798,
   "basis": "PP family: PP T30S ¥8.79/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over PP homopolymer (copolymer K8003 not found); ladder ×1.495 (book £1.48 ÷ base £0.99)",
   "source": "http://www.chemrp.com/info/detail-20261001-6294429.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-hdpe": {
   "gbpPerKg": 1.0439,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.000 (book £1.05 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-hdpe-bm": {
   "gbpPerKg": 1.1334,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.086 (book £1.14 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-hdpe-fuel-coex": {
   "gbpPerKg": 1.5311,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.467 (book £1.54 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-hdpe-profile": {
   "gbpPerKg": 1.0439,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.000 (book £1.05 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-hdpe-roto": {
   "gbpPerKg": 1.2825,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.229 (book £1.29 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-xlpe-roto": {
   "gbpPerKg": 1.7299,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.657 (book £1.74 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-fr-pe-roto": {
   "gbpPerKg": 2.6645,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×2.552 (book £2.68 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-foam-pe-roto": {
   "gbpPerKg": 1.9785,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.895 (book £1.99 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-cond-pe-roto": {
   "gbpPerKg": 2.4756,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×2.371 (book £2.49 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pex-pipe": {
   "gbpPerKg": 1.6007,
   "basis": "PE family: HDPE ¥9.27/kg ex-VAT (SunSirs, 1 Oct 2026) × the book's premium over HDPE; ladder ×1.533 (book £1.61 ÷ base £1.05)",
   "source": "https://hdpe.100ppi.com/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-ldpe": {
   "gbpPerKg": 1.0315,
   "basis": "LDPE family: LDPE ¥9.16/kg ex-VAT (Aug 2026) × the book's premium over LDPE; ladder ×1.000 (book £1.09 ÷ base £1.09)",
   "source": "https://www.100ppi.com/news/detail-20260813-6060907.html (2026-08-13)",
   "confidence": "Medium"
  },
  "mat-ldpe-bm": {
   "gbpPerKg": 1.1356,
   "basis": "LDPE family: LDPE ¥9.16/kg ex-VAT (Aug 2026) × the book's premium over LDPE; ladder ×1.101 (book £1.2 ÷ base £1.09)",
   "source": "https://www.100ppi.com/news/detail-20260813-6060907.html (2026-08-13)",
   "confidence": "Medium"
  },
  "mat-ldpe-tube": {
   "gbpPerKg": 1.0315,
   "basis": "LDPE family: LDPE ¥9.16/kg ex-VAT (Aug 2026) × the book's premium over LDPE; ladder ×1.000 (book £1.09 ÷ base £1.09)",
   "source": "https://www.100ppi.com/news/detail-20260813-6060907.html (2026-08-13)",
   "confidence": "Medium"
  },
  "mat-lldpe": {
   "gbpPerKg": 0.9358,
   "basis": "LLDPE family: LLDPE ¥8.31/kg ex-VAT (1 Oct 2026) × the book's premium over LLDPE; ladder ×1.000 (book £1.05 ÷ base £1.05)",
   "source": "https://m.10jqka.com.cn/20261001/c680427759.shtml (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-lldpe-bm": {
   "gbpPerKg": 1.0428,
   "basis": "LLDPE family: LLDPE ¥8.31/kg ex-VAT (1 Oct 2026) × the book's premium over LLDPE; ladder ×1.114 (book £1.17 ÷ base £1.05)",
   "source": "https://m.10jqka.com.cn/20261001/c680427759.shtml (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-lldpe-roto": {
   "gbpPerKg": 1.3101,
   "basis": "LLDPE family: LLDPE ¥8.31/kg ex-VAT (1 Oct 2026) × the book's premium over LLDPE; ladder ×1.400 (book £1.47 ÷ base £1.05)",
   "source": "https://m.10jqka.com.cn/20261001/c680427759.shtml (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-upvc": {
   "gbpPerKg": 0.4854,
   "basis": "PVC family: PVC SG-5 resin ¥4.31/kg ex-VAT (5 Oct 2026) × the book's premium of each compound over uPVC; ladder ×1.000 (book £0.76 ÷ base £0.76)",
   "source": "https://pvc.100ppi.com/news/list---1.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-fpvc": {
   "gbpPerKg": 0.7089,
   "basis": "PVC family: PVC SG-5 resin ¥4.31/kg ex-VAT (5 Oct 2026) × the book's premium of each compound over uPVC; ladder ×1.461 (book £1.11 ÷ base £0.76)",
   "source": "https://pvc.100ppi.com/news/list---1.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-pvc-bm": {
   "gbpPerKg": 0.5428,
   "basis": "PVC family: PVC SG-5 resin ¥4.31/kg ex-VAT (5 Oct 2026) × the book's premium of each compound over uPVC; ladder ×1.118 (book £0.85 ÷ base £0.76)",
   "source": "https://pvc.100ppi.com/news/list---1.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-upvc-window-profile": {
   "gbpPerKg": 0.8238,
   "basis": "PVC family: PVC SG-5 resin ¥4.31/kg ex-VAT (5 Oct 2026) × the book's premium of each compound over uPVC; ladder ×1.697 (book £1.29 ÷ base £0.76)",
   "source": "https://pvc.100ppi.com/news/list---1.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-pvcp-profile": {
   "gbpPerKg": 0.9835,
   "basis": "PVC family: PVC SG-5 resin ¥4.31/kg ex-VAT (5 Oct 2026) × the book's premium of each compound over uPVC; ladder ×2.026 (book £1.54 ÷ base £0.76)",
   "source": "https://pvc.100ppi.com/news/list---1.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-abs": {
   "gbpPerKg": 1.1273,
   "basis": "ABS family: ABS ¥10.01/kg ex-VAT (1 Oct 2026) × the book's premium over ABS; ladder ×1.000 (book £1.62 ÷ base £1.62)",
   "source": "https://abs.100ppi.com/news/list--121311-1.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-abs-fr": {
   "gbpPerKg": 1.3986,
   "basis": "ABS family: ABS ¥10.01/kg ex-VAT (1 Oct 2026) × the book's premium over ABS; ladder ×1.241 (book £2.01 ÷ base £1.62)",
   "source": "https://abs.100ppi.com/news/list--121311-1.html (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-gpps": {
   "gbpPerKg": 1.1092,
   "basis": "PS: PS ¥9.85/kg ex-VAT (5 Oct 2026) × the book's premium over GPPS; ladder ×1.000 (book £1.37 ÷ base £1.37)",
   "source": "http://www.chemrp.com/info/detail-20260902-6155369.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-hips": {
   "gbpPerKg": 1.1092,
   "basis": "PS: PS ¥9.85/kg ex-VAT (5 Oct 2026) × the book's premium over GPPS; ladder ×1.000 (book £1.37 ÷ base £1.37)",
   "source": "http://www.chemrp.com/info/detail-20260902-6155369.html (2026-10-05)",
   "confidence": "Medium"
  },
  "mat-pc": {
   "gbpPerKg": 1.2523,
   "basis": "PC family: PC ¥11.12/kg ex-VAT (Jul 2026; still falling in Sep) × the book's premium over PC; ladder ×1.000 (book £2.52 ÷ base £2.52)",
   "source": "http://www.chemrp.com/info/detail-20260709-5896771.html (2026-07-09)",
   "confidence": "Medium"
  },
  "mat-pc-glazing": {
   "gbpPerKg": 2.0871,
   "basis": "PC family: PC ¥11.12/kg ex-VAT (Jul 2026; still falling in Sep) × the book's premium over PC; ladder ×1.667 (book £4.2 ÷ base £2.52)",
   "source": "http://www.chemrp.com/info/detail-20260709-5896771.html (2026-07-09)",
   "confidence": "Medium"
  },
  "mat-pc-bm": {
   "gbpPerKg": 1.938,
   "basis": "PC family: PC ¥11.12/kg ex-VAT (Jul 2026; still falling in Sep) × the book's premium over PC; ladder ×1.548 (book £3.9 ÷ base £2.52)",
   "source": "http://www.chemrp.com/info/detail-20260709-5896771.html (2026-07-09)",
   "confidence": "Medium"
  },
  "mat-pa6": {
   "gbpPerKg": 1.1791,
   "basis": "PA6 family: PA6 chips ¥10.47/kg ex-VAT (Jul 2026) × the book's premium over PA6; ladder ×1.000 (book £1.68 ÷ base £1.68)",
   "source": "https://pa6.100ppi.com/ (2026-07-13)",
   "confidence": "Medium"
  },
  "mat-pa6-bm": {
   "gbpPerKg": 2.1756,
   "basis": "PA6 family: PA6 chips ¥10.47/kg ex-VAT (Jul 2026) × the book's premium over PA6; ladder ×1.845 (book £3.1 ÷ base £1.68)",
   "source": "https://pa6.100ppi.com/ (2026-07-13)",
   "confidence": "Medium"
  },
  "mat-pa6-ext-tube": {
   "gbpPerKg": 1.1791,
   "basis": "PA6 family: PA6 chips ¥10.47/kg ex-VAT (Jul 2026) × the book's premium over PA6; ladder ×1.000 (book £1.68 ÷ base £1.68)",
   "source": "https://pa6.100ppi.com/ (2026-07-13)",
   "confidence": "Medium"
  },
  "mat-pa66": {
   "gbpPerKg": 1.9032,
   "basis": "PA66: PA66 chips ¥16.90/kg ex-VAT (producer offers, 22 Sep 2026); direct",
   "source": "http://stock.10jqka.com.cn/20260922/c680178557.shtml (2026-09-22)",
   "confidence": "Medium"
  },
  "mat-pom": {
   "gbpPerKg": 1.2995,
   "basis": "POM: POM ¥11.54/kg ex-VAT (Jun 2026) × the book's premium over POM; ladder ×1.000 (book £2.05 ÷ base £2.05)",
   "source": "https://www.100ppi.com/news/detail-20260724-5970637.html (2026-06-12)",
   "confidence": "Medium"
  },
  "mat-pom-rod": {
   "gbpPerKg": 1.4707,
   "basis": "POM: POM ¥11.54/kg ex-VAT (Jun 2026) × the book's premium over POM; ladder ×1.132 (book £2.32 ÷ base £2.05)",
   "source": "https://www.100ppi.com/news/detail-20260724-5970637.html (2026-06-12)",
   "confidence": "Medium"
  },
  "mat-pbt": {
   "gbpPerKg": 0.9966,
   "basis": "PBT: PBT ≤ ¥8.85/kg ex-VAT (Q2 2026: OilChem — trades below ¥10,000/t incl. VAT; a ceiling); direct",
   "source": "https://plas.oilchem.net/plastic/pbt.shtml (2026-Q2)",
   "confidence": "Low"
  },
  "mat-pet-bg": {
   "gbpPerKg": 0.8716,
   "basis": "PET family: PET bottle chip ¥7.74/kg ex-VAT (1 Oct 2026) × the book's premium over PET bottle grade; ladder ×1.000 (book £1.21 ÷ base £1.21)",
   "source": "https://m.10jqka.com.cn/20261001/c680427815.shtml (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pet-preform": {
   "gbpPerKg": 0.9004,
   "basis": "PET family: PET bottle chip ¥7.74/kg ex-VAT (1 Oct 2026) × the book's premium over PET bottle grade; ladder ×1.033 (book £1.25 ÷ base £1.21)",
   "source": "https://m.10jqka.com.cn/20261001/c680427815.shtml (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-pmma": {
   "gbpPerKg": 1.5045,
   "basis": "PMMA family: PMMA ¥13.36/kg ex-VAT (30 Sep 2026) × the book's premium over PMMA; ladder ×1.000 (book £2.4 ÷ base £2.4)",
   "source": "https://m.mysteel.com/hot/1592840.html (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-tpu-shore85": {
   "gbpPerKg": 1.7736,
   "basis": "TPU family: TPU (Wanhua 1565A) ¥15.75/kg ex-VAT (30 Sep 2026) × the book's premium over TPU 85A; ladder ×1.000 (book £2.52 ÷ base £2.52)",
   "source": "https://rp.100ppi.com/price/plist-459-1.html (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-tpu-ext-hose": {
   "gbpPerKg": 1.7736,
   "basis": "TPU family: TPU (Wanhua 1565A) ¥15.75/kg ex-VAT (30 Sep 2026) × the book's premium over TPU 85A; ladder ×1.000 (book £2.52 ÷ base £2.52)",
   "source": "https://rp.100ppi.com/price/plist-459-1.html (2026-09-30)",
   "confidence": "Medium"
  },
  "mat-peek": {
   "gbpPerKg": 27.8491,
   "basis": "PEEK family: PEEK ≈ ¥247/kg ex-VAT — 中研股份 FY2025 PEEK revenue ÷ tonnes sold (a domestic producer ASP, derived); ladder ×1.000 (book £76 ÷ base £76)",
   "source": "https://news.qq.com/rain/a/20260429A0934U00 (2025 (FY, published 2026-04-29))",
   "confidence": "Low"
  },
  "mat-peek-ext": {
   "gbpPerKg": 27.8491,
   "basis": "PEEK family: PEEK ≈ ¥247/kg ex-VAT — 中研股份 FY2025 PEEK revenue ÷ tonnes sold (a domestic producer ASP, derived); ladder ×1.000 (book £76 ÷ base £76)",
   "source": "https://news.qq.com/rain/a/20260429A0934U00 (2025 (FY, published 2026-04-29))",
   "confidence": "Low"
  },
  "mat-nr": {
   "gbpPerKg": 1.9032,
   "basis": "Natural rubber (raw): SCRWF / NR ¥16.90/kg ex-VAT (SunSirs, 6 Oct 2026) for the book's raw NR SMR20 line; compounds held; direct",
   "source": "https://nr.100ppi.com/ (2026-10-06)",
   "confidence": "Medium"
  }
 },
 "machines": {
  "hoursPerYear": 6336,
  "shiftDepreciationFactor": 1,
  "lifeYears": 10,
  "financeRate": 0.035,
  "ukFinanceRate": 0.04,
  "maintenancePctOfCapex": 0.035,
  "rentGbpPerM2Yr": 34.4189,
  "ukRentGbpPerM2Yr": 110,
  "ukElectricityGbpPerKwh": 0.182,
  "labourRatio": 0.1335,
  "capitalHeldFactor": 0.55,
  "basis": "two 12-h shifts × 11 h worked × 24 days/month × 12 = 6,336 h (the labour model's pattern); PRC straight-line (time-based) depreciation — no shift uplift on held capital; PBoC 5-year LPR 3.5% (20 Sep 2026; 1-year 3.0%) — the book's line build-ups use 4% on half the capex; rent ¥25.47/m²/month (JLL Shanghai logistics rent Q2 2026 ¥31.94/m²/month (a ceiling for a factory) and Dongguan factory rents ¥10–28 (midpoint ¥19; estate-agent article, 2025) — mean; Wuhan / Chongqing averages not found (Chongqing listings ¥4–12 suggest this is high for the inland clusters)); maintenance the library's own line build-up rule (3.5% of capex); no Chinese norm found",
  "heldBasis": "capex not sourced for China: the book's capital (UK × 0.55) is HELD; the China operating model (2 × 12 h hours, straight-line, LPR finance, rent, tariff, support at China wages) is applied",
  "groups": [
   {
    "id": "cnc-vmc-domestic",
    "match": "^(mach-vmc3|mach-haas-vf2|mach-drill)$",
    "refId": "mach-vmc3",
    "refCapexGbp": 32411.82,
    "basis": "Haitian Precision 海天精工 2025 VMC average selling price ¥287,817 ex-VAT (¥841M ÷ 2,922 units); delivery, options and installation not in it",
    "source": "https://finance.sina.cn/2026-03-23/detail-inhrynrq1147454.d.html ; units: http://dataclouds.cninfo.com.cn/shgonggao/hsomarket/2026/20260323/71ad745b243c48e79d848681d7931b2a.PDF",
    "confidence": "Medium"
   },
   {
    "id": "cnc-lathe-domestic",
    "match": "^(mach-lathe-cnc|mach-mazak-qt200)$",
    "refId": "mach-lathe-cnc",
    "refCapexGbp": 24259.35,
    "basis": "Headman 浙海德曼 2025 slant-bed CNC lathe ¥215,423 (¥609M ÷ 2,827 units produced — an approximation)",
    "source": "https://finance.sina.com.cn/stock/aigc/stockfs/2026-04-27/doc-inhvyknv2104372.shtml ; units: https://basic.10jqka.com.cn/688577/operate.html",
    "confidence": "Low"
   },
   {
    "id": "cnc-5axis-domestic",
    "match": "^(mach-vmc5|mach-dmg-dmu50|mach-haas-umc500)$",
    "refId": "mach-vmc5",
    "refCapexGbp": 273096.85,
    "basis": "KEDE 科德数控 2024 five-axis average transaction price ¥2.4251M ex-VAT (its mix runs to large machines — top of range; Nawi IPO ¥2.0M)",
    "source": "https://stcn.com/article/detail/1725042.html ; https://www.stcn.com/article/detail/1413392.html",
    "confidence": "Low"
   }
  ]
 }
};
