/**
 * India rate book — GENERATED by `scripts/country-book.ts` from `scripts/rate-refresh/2026-10-india.json`.
 * Do not edit by hand: change the config (every figure carries its source there) and re-run the script.
 * Register of every rate (current v new, decision, basis): scripts/rate-refresh/india-2026-10/register.csv.
 */
import type { CountryBook } from '../country-books.js';

export const INDIA_BOOK: CountryBook = {
 "region": "IN",
 "asOf": "2026-10-10",
 "fxToGBP": 127.2,
 "labourGrades": {
  "forge": {
   "gbpPerHr": 1.0362,
   "basis": "G=22,000; basic=0.5G=11,000; PF+EDLI+admin=13%xmin(basic,15000)=1,430; ESI=3.25%xG if G<=21000 =0; bonus=8.33%xmin(basic,18677) if basic<=21000 =916; gratuity=4.81%xbasic=529; monthly employer cost=24,875 (+13.1%); x12=298,505/yr / 2,264 h = 131.8 INR/h. Included: employer PF 12% + EDLI/admin 1% (PF wage ≤ ₹15,000), ESI 3.25% (gross ≤ ₹21,000), statutory bonus 8.33%, gratuity 4.81%, basic = 50% of gross (Code on Wages); 2,264 productive h/yr (312 paid days − 29 leave/holiday days). NOT included: night-shift allowance, canteen / transport / uniform, group insurance, labour-agency margin on contract workers (~half of auto employment), bonus above 8.33% — not found in any source this round",
   "source": "https://wageindicator.org/en-in/work-in-india/role-and-pay/india-blacksmiths-hammersmiths-and-forging-press",
   "confidence": "Medium"
  },
  "furnace": {
   "gbpPerHr": 1.0833,
   "basis": "G=23,000; basic=0.5G=11,500; PF+EDLI+admin=13%xmin(basic,15000)=1,495; ESI=3.25%xG if G<=21000 =0; bonus=8.33%xmin(basic,18677) if basic<=21000 =958; gratuity=4.81%xbasic=553; monthly employer cost=26,006 (+13.1%); x12=312,073/yr / 2,264 h = 137.8 INR/h. Included: employer PF 12% + EDLI/admin 1% (PF wage ≤ ₹15,000), ESI 3.25% (gross ≤ ₹21,000), statutory bonus 8.33%, gratuity 4.81%, basic = 50% of gross (Code on Wages); 2,264 productive h/yr (312 paid days − 29 leave/holiday days). NOT included: night-shift allowance, canteen / transport / uniform, group insurance, labour-agency margin on contract workers (~half of auto employment), bonus above 8.33% — not found in any source this round",
   "source": "https://in.indeed.com/cmp/Marks-Engineering-Works---Foundry-Division",
   "confidence": "Medium"
  },
  "blow": {
   "gbpPerHr": 0.8726,
   "basis": "G=18,000; basic=0.5G=9,000; PF+EDLI+admin=13%xmin(basic,15000)=1,170; ESI=3.25%xG if G<=21000 =585; bonus=8.33%xmin(basic,18677) if basic<=21000 =750; gratuity=4.81%xbasic=433; monthly employer cost=20,938 (+16.3%); x12=251,251/yr / 2,264 h = 111.0 INR/h. Included: employer PF 12% + EDLI/admin 1% (PF wage ≤ ₹15,000), ESI 3.25% (gross ≤ ₹21,000), statutory bonus 8.33%, gratuity 4.81%, basic = 50% of gross (Code on Wages); 2,264 productive h/yr (312 paid days − 29 leave/holiday days). NOT included: night-shift allowance, canteen / transport / uniform, group insurance, labour-agency margin on contract workers (~half of auto employment), bonus above 8.33% — not found in any source this round",
   "source": "https://corpready.in/salary/injection-moulding-operator",
   "confidence": "Medium"
  },
  "roto": {
   "gbpPerHr": 0.8726,
   "basis": "G=18,000; basic=0.5G=9,000; PF+EDLI+admin=13%xmin(basic,15000)=1,170; ESI=3.25%xG if G<=21000 =585; bonus=8.33%xmin(basic,18677) if basic<=21000 =750; gratuity=4.81%xbasic=433; monthly employer cost=20,938 (+16.3%); x12=251,251/yr / 2,264 h = 111.0 INR/h. Included: employer PF 12% + EDLI/admin 1% (PF wage ≤ ₹15,000), ESI 3.25% (gross ≤ ₹21,000), statutory bonus 8.33%, gratuity 4.81%, basic = 50% of gross (Code on Wages); 2,264 productive h/yr (312 paid days − 29 leave/holiday days). NOT included: night-shift allowance, canteen / transport / uniform, group insurance, labour-agency margin on contract workers (~half of auto employment), bonus above 8.33% — not found in any source this round",
   "source": "https://corpready.in/salary/injection-moulding-operator",
   "confidence": "Medium"
  },
  "thermoform": {
   "gbpPerHr": 0.8726,
   "basis": "G=18,000; basic=0.5G=9,000; PF+EDLI+admin=13%xmin(basic,15000)=1,170; ESI=3.25%xG if G<=21000 =585; bonus=8.33%xmin(basic,18677) if basic<=21000 =750; gratuity=4.81%xbasic=433; monthly employer cost=20,938 (+16.3%); x12=251,251/yr / 2,264 h = 111.0 INR/h. Included: employer PF 12% + EDLI/admin 1% (PF wage ≤ ₹15,000), ESI 3.25% (gross ≤ ₹21,000), statutory bonus 8.33%, gratuity 4.81%, basic = 50% of gross (Code on Wages); 2,264 productive h/yr (312 paid days − 29 leave/holiday days). NOT included: night-shift allowance, canteen / transport / uniform, group insurance, labour-agency margin on contract workers (~half of auto employment), bonus above 8.33% — not found in any source this round",
   "source": "https://corpready.in/salary/injection-moulding-operator",
   "confidence": "Medium"
  },
  "trim-router": {
   "gbpPerHr": 0.8726,
   "basis": "G=18,000; basic=0.5G=9,000; PF+EDLI+admin=13%xmin(basic,15000)=1,170; ESI=3.25%xG if G<=21000 =585; bonus=8.33%xmin(basic,18677) if basic<=21000 =750; gratuity=4.81%xbasic=433; monthly employer cost=20,938 (+16.3%); x12=251,251/yr / 2,264 h = 111.0 INR/h. Included: employer PF 12% + EDLI/admin 1% (PF wage ≤ ₹15,000), ESI 3.25% (gross ≤ ₹21,000), statutory bonus 8.33%, gratuity 4.81%, basic = 50% of gross (Code on Wages); 2,264 productive h/yr (312 paid days − 29 leave/holiday days). NOT included: night-shift allowance, canteen / transport / uniform, group insurance, labour-agency margin on contract workers (~half of auto employment), bonus above 8.33% — not found in any source this round",
   "source": "https://corpready.in/salary/injection-moulding-operator",
   "confidence": "Medium"
  }
 },
 "materials": {
  "mat-dc01": {
   "gbpPerKg": 0.5661,
   "basis": "CR coil (commodity CRCA): JPC / Ministry of Steel retail, Sep 2026, 4-metro average, CR coil 0.63 mm, ₹84,972/t incl. GST ÷ 1.18; direct",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-dc04": {
   "gbpPerKg": 0.5661,
   "basis": "CR coil (commodity CRCA): JPC / Ministry of Steel retail, Sep 2026, 4-metro average, CR coil 0.63 mm, ₹84,972/t incl. GST ÷ 1.18; direct",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-dc05": {
   "gbpPerKg": 0.5661,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; the anchor grade itself",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-dc06": {
   "gbpPerKg": 0.5729,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.012 (book £0.85 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-if-dx56": {
   "gbpPerKg": 0.6739,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.190 (book £1 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-if-hs260": {
   "gbpPerKg": 0.7616,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.345 (book £1.13 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-bh260": {
   "gbpPerKg": 0.7413,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.310 (book £1.1 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-greensteel-dc01": {
   "gbpPerKg": 0.7413,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.310 (book £1.1 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-hsla340": {
   "gbpPerKg": 0.802,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.417 (book £1.19 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-hsla420": {
   "gbpPerKg": 0.8694,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.536 (book £1.29 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-hsla550": {
   "gbpPerKg": 0.9368,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.655 (book £1.39 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-dp600": {
   "gbpPerKg": 0.8761,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.548 (book £1.3 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-dp780": {
   "gbpPerKg": 0.9233,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.631 (book £1.37 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-dp980": {
   "gbpPerKg": 1.0109,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.786 (book £1.5 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-dp1000": {
   "gbpPerKg": 1.0581,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.869 (book £1.57 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-trip780": {
   "gbpPerKg": 0.9772,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.726 (book £1.45 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-cp800": {
   "gbpPerKg": 0.9637,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.702 (book £1.43 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-ms1200": {
   "gbpPerKg": 1.0783,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.905 (book £1.6 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-ms1300": {
   "gbpPerKg": 1.1255,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.988 (book £1.67 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-ms1500": {
   "gbpPerKg": 1.1929,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×2.107 (book £1.77 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-qp980": {
   "gbpPerKg": 1.1659,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×2.060 (book £1.73 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-medmn1180": {
   "gbpPerKg": 1.2131,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×2.143 (book £1.8 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-22mnb5": {
   "gbpPerKg": 1.2064,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×2.131 (book £1.79 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-usibor1500": {
   "gbpPerKg": 1.3479,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×2.381 (book £2 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-usibor2000": {
   "gbpPerKg": 1.6175,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×2.857 (book £2.4 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-c67s-spring": {
   "gbpPerKg": 1.0783,
   "basis": "CR automotive grades: CR anchor (JPC Sep 2026) × the book's grade premium over its DC01/DC04 mean (£0.84/kg UK); India grade extras for IF / HSLA / DP / TRIP / CP / MS / PHS not found; ladder ×1.905 (book £1.6 ÷ base £0.84)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09) ; https://www.hellenicshippingnews.com/explained-steel-firms-renegotiating-auto-contracts-and-the-impact-on-stocks-consumers/ (n/a)",
   "confidence": "Low"
  },
  "mat-hrpo": {
   "gbpPerKg": 0.5596,
   "basis": "HR pickled & oiled: HR coil JPC Sep 2026 ₹64.48 + HRPO extra ₹6.70 (Tata Nexarc Mumbai HRPO May 2026 − BigMint HRC May 2026); direct",
   "source": "https://www.tatanexarc.com/steel/steel-prices-in-india/ (2026-09 (derived)) ; https://www.tatanexarc.com/steel/steel-prices-in-india/ (2026-05)",
   "confidence": "Medium"
  },
  "mat-s355mc": {
   "gbpPerKg": 0.5267,
   "basis": "HR structural: HR coil JPC Sep 2026 (₹76,085/t incl. GST ÷ 1.18) × the book's premium over HRPO; S355MC / S420MC extras not found; ladder ×1.039 (book £0.8 ÷ base £0.77)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-s420mc": {
   "gbpPerKg": 0.5398,
   "basis": "HR structural: HR coil JPC Sep 2026 (₹76,085/t incl. GST ÷ 1.18) × the book's premium over HRPO; S355MC / S420MC extras not found; ladder ×1.065 (book £0.82 ÷ base £0.77)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-dc01-gi": {
   "gbpPerKg": 0.6273,
   "basis": "Coated sheet: GP sheet 0.63 mm JPC Sep 2026 (₹94,148/t incl. GST ÷ 1.18) × the book's premium over DC01 GI; coating-grade extras not found; the anchor grade itself",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-dc03-ga": {
   "gbpPerKg": 0.6499,
   "basis": "Coated sheet: GP sheet 0.63 mm JPC Sep 2026 (₹94,148/t incl. GST ÷ 1.18) × the book's premium over DC01 GI; coating-grade extras not found; ladder ×1.036 (book £1.15 ÷ base £1.11)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-dc01-ze": {
   "gbpPerKg": 0.6273,
   "basis": "Coated sheet: GP sheet 0.63 mm JPC Sep 2026 (₹94,148/t incl. GST ÷ 1.18) × the book's premium over DC01 GI; coating-grade extras not found; the anchor grade itself",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-znni-eg": {
   "gbpPerKg": 0.6951,
   "basis": "Coated sheet: GP sheet 0.63 mm JPC Sep 2026 (₹94,148/t incl. GST ÷ 1.18) × the book's premium over DC01 GI; coating-grade extras not found; ladder ×1.108 (book £1.23 ÷ base £1.11)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-zm-coated": {
   "gbpPerKg": 0.6781,
   "basis": "Coated sheet: GP sheet 0.63 mm JPC Sep 2026 (₹94,148/t incl. GST ÷ 1.18) × the book's premium over DC01 GI; coating-grade extras not found; ladder ×1.081 (book £1.2 ÷ base £1.11)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-tinplate-etp": {
   "gbpPerKg": 0.7629,
   "basis": "Coated sheet: GP sheet 0.63 mm JPC Sep 2026 (₹94,148/t incl. GST ÷ 1.18) × the book's premium over DC01 GI; coating-grade extras not found; ladder ×1.216 (book £1.35 ÷ base £1.11)",
   "source": "https://indianmasterminds.com/news/india-steel-demand-apr-aug-2026-236706/ (2026-09)",
   "confidence": "Low"
  },
  "mat-en8": {
   "gbpPerKg": 0.6517,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.140 (book £0.98 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel1045": {
   "gbpPerKg": 0.6318,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.105 (book £0.95 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-c45": {
   "gbpPerKg": 0.5719,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; the anchor grade itself",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-c35": {
   "gbpPerKg": 0.5719,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; the anchor grade itself",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel1020": {
   "gbpPerKg": 0.5719,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; the anchor grade itself",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-a105": {
   "gbpPerKg": 0.5719,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; the anchor grade itself",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-c70s6": {
   "gbpPerKg": 0.6118,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.070 (book £0.92 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel1141": {
   "gbpPerKg": 0.6983,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.221 (book £1.05 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-en3-bar": {
   "gbpPerKg": 0.6251,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.093 (book £0.94 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-11smnpb30": {
   "gbpPerKg": 0.7781,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.360 (book £1.17 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-30mnvs6": {
   "gbpPerKg": 0.7648,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-38mnvs6": {
   "gbpPerKg": 0.7648,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-42crmo4": {
   "gbpPerKg": 1.0707,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.872 (book £1.61 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel4140": {
   "gbpPerKg": 1.0707,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.872 (book £1.61 [mat-steel-42crmo4] ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel4340": {
   "gbpPerKg": 0.9643,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.686 (book £1.45 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel4130": {
   "gbpPerKg": 1.0641,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.860 (book £1.6 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel8620": {
   "gbpPerKg": 0.9976,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.744 (book £1.5 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-20mncr5": {
   "gbpPerKg": 0.9843,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.721 (book £1.48 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-16mncr5": {
   "gbpPerKg": 0.9843,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.721 (book £1.48 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-41cr4": {
   "gbpPerKg": 0.9843,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.721 (book £1.48 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-34crnimo6": {
   "gbpPerKg": 1.2037,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×2.105 (book £1.81 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-18crnimo7-6": {
   "gbpPerKg": 1.2436,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×2.174 (book £1.87 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-52100": {
   "gbpPerKg": 1.1306,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×1.977 (book £1.7 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-f22": {
   "gbpPerKg": 1.3966,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×2.442 (book £2.1 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-steel-300m": {
   "gbpPerKg": 2.5272,
   "basis": "Carbon / alloy bar and forging stock: BigMint EN8 / C45 black round bar 110–150 mm ex-Mumbai ₹72,750/t (22 Apr 2026, latest found) × the book's grade premium over C45 billet; alloy-bar and bright-bar extras not found; ladder ×4.419 (book £3.8 ÷ base £0.86)",
   "source": "https://www.bigmint.co/intel/detail/india-alloy-steel-round-bar-prices-remain-stable-w-o-w-36412 (2026-04-22) ; https://dir.indiamart.com/pune/alloy-steel-bars.html (undated listings)",
   "confidence": "Low"
  },
  "mat-ss316l-bar": {
   "gbpPerKg": 2.673,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; the anchor grade itself",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss304l-bar": {
   "gbpPerKg": 1.9973,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×0.747 (book £4.73 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss410-bar": {
   "gbpPerKg": 1.5328,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×0.573 (book £3.63 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss420-bar": {
   "gbpPerKg": 1.5371,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×0.575 (book £3.64 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss431-bar": {
   "gbpPerKg": 1.668,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×0.624 (book £3.95 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss17-4ph-bar": {
   "gbpPerKg": 3.9271,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×1.469 (book £9.3 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss15-5ph-bar": {
   "gbpPerKg": 4.1805,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×1.564 (book £9.9 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss2205-bar": {
   "gbpPerKg": 2.7067,
   "basis": "Stainless forging bar: BigMint SS 316L black round bar ex-Mumbai ₹340,000/t (~Jun 2026) × the book's grade premium over 316L forging bar; other stainless bar prices not found in India; ladder ×1.013 (book £6.41 ÷ base £6.33)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss316l": {
   "gbpPerKg": 2.673,
   "basis": "Stainless machining bar: BigMint SS 316L black round bar ₹340/kg (~Jun 2026) × the book's premium over its 316L machining bar; the anchor grade itself",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss304-bar": {
   "gbpPerKg": 2.3887,
   "basis": "Stainless machining bar: BigMint SS 316L black round bar ₹340/kg (~Jun 2026) × the book's premium over its 316L machining bar; ladder ×0.894 (book £3.53 ÷ base £3.95)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss303": {
   "gbpPerKg": 2.5918,
   "basis": "Stainless machining bar: BigMint SS 316L black round bar ₹340/kg (~Jun 2026) × the book's premium over its 316L machining bar; ladder ×0.970 (book £3.83 ÷ base £3.95)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss416-bar": {
   "gbpPerKg": 2.6594,
   "basis": "Stainless machining bar: BigMint SS 316L black round bar ₹340/kg (~Jun 2026) × the book's premium over its 316L machining bar; ladder ×0.995 (book £3.93 ÷ base £3.95)",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss316-sheet": {
   "gbpPerKg": 3.1053,
   "basis": "316L sheet: BigMint 316 HR coil ex-Mumbai ₹395,000/t (~Jun 2026); CR extra not found; direct",
   "source": "https://www.bigmint.co/insights/detail/india-stainless-steel-finished-prices-ease-w-o-w-on-weak-demand-softening-nickel-prices-765276 (2026-06 (approx.))",
   "confidence": "Low"
  },
  "mat-ss304-sheet": {
   "gbpPerKg": 1.7256,
   "basis": "304L sheet: 304 CR coil narrow Mumbai ₹215/kg (Nexizo, 1 Jul 2026) and a stockist ₹224/kg — mean; aggregator evidence, low confidence; direct",
   "source": "https://nexizo.ai/stainless-steel-category (2026-07-01)",
   "confidence": "Low"
  },
  "mat-ss301-spring": {
   "gbpPerKg": 2.2399,
   "basis": "301 spring strip: 304L sheet ₹219.5 × the book's premium of 301 spring strip over 304L sheet; ladder ×1.298 (book £4.53 ÷ base £3.49)",
   "source": "https://nexizo.ai/stainless-steel-category (2026-07-01)",
   "confidence": "Low"
  },
  "mat-aisi430": {
   "gbpPerKg": 1.0528,
   "basis": "430 ferritic sheet: China 430 2B ₹123.7/kg (9 Sep 2026 reference, before freight) × 1.0825 (BCD 7.5% + SWS 0.75%) — import parity, freight not added; direct",
   "source": "https://www.sakysteel.com/news/china-stainless-steel-market-price-update-september-9-2026 (2026-09-09)",
   "confidence": "Low"
  },
  "mat-ss409l-sheet": {
   "gbpPerKg": 1.0557,
   "basis": "409L / 441 ferritic sheet: China 409L ₹124.0/kg × 1.0825 duty — import parity; 441 at the book's premium over 409L; the anchor grade itself",
   "source": "https://www.sakysteel.com/news/china-stainless-steel-market-price-update-september-9-2026 (2026-09-09)",
   "confidence": "Low"
  },
  "mat-ss441-sheet": {
   "gbpPerKg": 1.1705,
   "basis": "409L / 441 ferritic sheet: China 409L ₹124.0/kg × 1.0825 duty — import parity; 441 at the book's premium over 409L; ladder ×1.109 (book £3.16 ÷ base £2.85)",
   "source": "https://www.sakysteel.com/news/china-stainless-steel-market-price-update-september-9-2026 (2026-09-09)",
   "confidence": "Low"
  },
  "mat-gjs500": {
   "gbpPerKg": 0.3617,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; the anchor grade itself",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjs400": {
   "gbpPerKg": 0.3449,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×0.953 (book £0.82 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjs450-ssf": {
   "gbpPerKg": 0.3491,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×0.965 (book £0.83 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjs500-14": {
   "gbpPerKg": 0.3533,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×0.977 (book £0.84 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjs600": {
   "gbpPerKg": 0.3785,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.047 (book £0.9 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjs700": {
   "gbpPerKg": 0.3996,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.105 (book £0.95 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjs350-lt": {
   "gbpPerKg": 0.3659,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.012 (book £0.87 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-simo": {
   "gbpPerKg": 0.5678,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.570 (book £1.35 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-adi": {
   "gbpPerKg": 0.6645,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.837 (book £1.58 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjv450": {
   "gbpPerKg": 0.4711,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.302 (book £1.12 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjv500": {
   "gbpPerKg": 0.4837,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Metallic charge for GJS-500-7, mix A (60% pig iron ₹47.05 + steel scrap ₹39.8 + returns at charge cost; KTU ductile charge study) = ₹46.01/kg, the upper of the two mixes; FeSiMg and inoculant not priced (not found) × the book's grade premium over GJS-500-7; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://matsc.ktu.lt/index.php/MatSc/article/view/26589/13665 (2026-10 (inputs Apr-Oct 2026)) ; https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10-06) ; https://www.bigmint.co/insights/detail/india-foundry-scrap-market-remains-under-pressure-low-manganese-cr-busheling-sees-sharper-correction-758327 (2026-04 to 2026-07)",
   "confidence": "Low"
  },
  "mat-gjl250": {
   "gbpPerKg": 0.3349,
   "basis": "Grey / malleable iron (charge): Metallic charge for GJL-250 ₹42.6/kg (40% steel scrap + 20% pig iron + returns; the mix is a CostVision engineering assumption — no Indian grey-iron charge mix found) × the book's grade premium over GJL-250; the anchor grade itself",
   "source": "https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10 (inputs Apr-Oct 2026))",
   "confidence": "Low"
  },
  "mat-gjl150": {
   "gbpPerKg": 0.293,
   "basis": "Grey / malleable iron (charge): Metallic charge for GJL-250 ₹42.6/kg (40% steel scrap + 20% pig iron + returns; the mix is a CostVision engineering assumption — no Indian grey-iron charge mix found) × the book's grade premium over GJL-250; ladder ×0.875 (book £0.56 ÷ base £0.64)",
   "source": "https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10 (inputs Apr-Oct 2026))",
   "confidence": "Low"
  },
  "mat-gjl200": {
   "gbpPerKg": 0.314,
   "basis": "Grey / malleable iron (charge): Metallic charge for GJL-250 ₹42.6/kg (40% steel scrap + 20% pig iron + returns; the mix is a CostVision engineering assumption — no Indian grey-iron charge mix found) × the book's grade premium over GJL-250; ladder ×0.938 (book £0.6 ÷ base £0.64)",
   "source": "https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10 (inputs Apr-Oct 2026))",
   "confidence": "Low"
  },
  "mat-gjl300": {
   "gbpPerKg": 0.3663,
   "basis": "Grey / malleable iron (charge): Metallic charge for GJL-250 ₹42.6/kg (40% steel scrap + 20% pig iron + returns; the mix is a CostVision engineering assumption — no Indian grey-iron charge mix found) × the book's grade premium over GJL-250; ladder ×1.094 (book £0.7 ÷ base £0.64)",
   "source": "https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10 (inputs Apr-Oct 2026))",
   "confidence": "Low"
  },
  "mat-gjl350": {
   "gbpPerKg": 0.3872,
   "basis": "Grey / malleable iron (charge): Metallic charge for GJL-250 ₹42.6/kg (40% steel scrap + 20% pig iron + returns; the mix is a CostVision engineering assumption — no Indian grey-iron charge mix found) × the book's grade premium over GJL-250; ladder ×1.156 (book £0.74 ÷ base £0.64)",
   "source": "https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10 (inputs Apr-Oct 2026))",
   "confidence": "Low"
  },
  "mat-gjmb350": {
   "gbpPerKg": 0.3454,
   "basis": "Grey / malleable iron (charge): Metallic charge for GJL-250 ₹42.6/kg (40% steel scrap + 20% pig iron + returns; the mix is a CostVision engineering assumption — no Indian grey-iron charge mix found) × the book's grade premium over GJL-250; ladder ×1.031 (book £0.66 ÷ base £0.64)",
   "source": "https://www.bigmint.co/insights/detail/india-pig-iron-prices-rise-in-september-as-exports-input-costs-hurt-availability-796063 (2026-10 (inputs Apr-Oct 2026))",
   "confidence": "Low"
  },
  "mat-gs-c25": {
   "gbpPerKg": 0.3007,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ₹38.25/kg (melting scrap: Chennai foundry plate ₹38.6, Alang HMS ₹36.5 + deoxidation) × the book's premium over GS-C25; the anchor grade itself",
   "source": "https://www.mysteel.net/news/5139931-india-alang-melting-scrap-prices-hold-steady-amid-subdued-post-festival-buying (2026-09)",
   "confidence": "Low"
  },
  "mat-astm-a216-wcb": {
   "gbpPerKg": 0.3007,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ₹38.25/kg (melting scrap: Chennai foundry plate ₹38.6, Alang HMS ₹36.5 + deoxidation) × the book's premium over GS-C25; the anchor grade itself",
   "source": "https://www.mysteel.net/news/5139931-india-alang-melting-scrap-prices-hold-steady-amid-subdued-post-festival-buying (2026-09)",
   "confidence": "Low"
  },
  "mat-g20mn5": {
   "gbpPerKg": 0.3007,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ₹38.25/kg (melting scrap: Chennai foundry plate ₹38.6, Alang HMS ₹36.5 + deoxidation) × the book's premium over GS-C25; the anchor grade itself",
   "source": "https://www.mysteel.net/news/5139931-india-alang-melting-scrap-prices-hold-steady-amid-subdued-post-festival-buying (2026-09)",
   "confidence": "Low"
  },
  "mat-g42crmo4": {
   "gbpPerKg": 0.3208,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge ₹38.25/kg (melting scrap: Chennai foundry plate ₹38.6, Alang HMS ₹36.5 + deoxidation) × the book's premium over GS-C25; ladder ×1.067 (book £2.24 ÷ base £2.1)",
   "source": "https://www.mysteel.net/news/5139931-india-alang-melting-scrap-prices-hold-steady-amid-subdued-post-festival-buying (2026-09)",
   "confidence": "Low"
  },
  "mat-hadfield": {
   "gbpPerKg": 0.3514,
   "basis": "Hadfield Mn steel (charge): 12% Mn via HC FeMn 70% (₹79.2) + steel scrap; direct",
   "source": "https://www.bigmint.co/insights/detail/weekly-round-up-indian-ferro-alloys-prices-witness-mixed-trends-w-o-w-764117 (2026-06/09)",
   "confidence": "Low"
  },
  "mat-hicr-white": {
   "gbpPerKg": 0.5731,
   "basis": "High-Cr white iron (charge): 23% Cr via HC FeCr 60% (₹122.2) + grey-iron metallic charge; direct",
   "source": "https://www.bigmint.co/insights/detail/india-ferro-chrome-prices-rise-slightly-w-o-w-as-sellers-quote-firm-offers-759134 (2026-06)",
   "confidence": "Low"
  },
  "mat-ni-resist-d2": {
   "gbpPerKg": 2.8648,
   "basis": "Ni-Resist D-2 (charge): 20% Ni at MCX nickel ₹1,625.5 + 2% Cr + iron units; direct",
   "source": "https://cbonds.com/indexes/221359/ (2026-08)",
   "confidence": "Low"
  },
  "mat-ni-resist-d5s": {
   "gbpPerKg": 4.7445,
   "basis": "Ni-Resist D-5S (charge): 35% Ni at MCX nickel + Cr + Si + iron units; direct",
   "source": "https://cbonds.com/indexes/221359/ (2026-08)",
   "confidence": "Low"
  },
  "mat-ss304-cast": {
   "gbpPerKg": 1.1399,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ₹145/kg DAP Delhi (SMM, 21 Aug 2026) × the book's premium over CF8; the anchor grade itself",
   "source": "https://news.metal.com/newscontent/104081100-smm-stainless-steel-flash-indias-stainless-steel-scrap-prices-strengthen-amid-tight-supply-and-firm-alloy-costs (2026-08-21)",
   "confidence": "Low"
  },
  "mat-cf8m-cast": {
   "gbpPerKg": 1.3803,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ₹145/kg DAP Delhi (SMM, 21 Aug 2026) × the book's premium over CF8; ladder ×1.211 (book £6.26 ÷ base £5.17)",
   "source": "https://news.metal.com/newscontent/104081100-smm-stainless-steel-flash-indias-stainless-steel-scrap-prices-strengthen-amid-tight-supply-and-firm-alloy-costs (2026-08-21)",
   "confidence": "Low"
  },
  "mat-ca6nm-cast": {
   "gbpPerKg": 1.1002,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ₹145/kg DAP Delhi (SMM, 21 Aug 2026) × the book's premium over CF8; ladder ×0.965 (book £4.99 ÷ base £5.17)",
   "source": "https://news.metal.com/newscontent/104081100-smm-stainless-steel-flash-indias-stainless-steel-scrap-prices-strengthen-amid-tight-supply-and-firm-alloy-costs (2026-08-21)",
   "confidence": "Low"
  },
  "mat-cd4mcun-cast": {
   "gbpPerKg": 1.4354,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ₹145/kg DAP Delhi (SMM, 21 Aug 2026) × the book's premium over CF8; ladder ×1.259 (book £6.51 ÷ base £5.17)",
   "source": "https://news.metal.com/newscontent/104081100-smm-stainless-steel-flash-indias-stainless-steel-scrap-prices-strengthen-amid-tight-supply-and-firm-alloy-costs (2026-08-21)",
   "confidence": "Low"
  },
  "mat-gx40crnisi25-20": {
   "gbpPerKg": 1.4663,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ₹145/kg DAP Delhi (SMM, 21 Aug 2026) × the book's premium over CF8; ladder ×1.286 (book £6.65 ÷ base £5.17)",
   "source": "https://news.metal.com/newscontent/104081100-smm-stainless-steel-flash-indias-stainless-steel-scrap-prices-strengthen-amid-tight-supply-and-firm-alloy-costs (2026-08-21)",
   "confidence": "Low"
  },
  "mat-17-4ph-cast": {
   "gbpPerKg": 2.1167,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap ₹145/kg DAP Delhi (SMM, 21 Aug 2026) × the book's premium over CF8; ladder ×1.857 (book £9.6 ÷ base £5.17)",
   "source": "https://news.metal.com/newscontent/104081100-smm-stainless-steel-flash-indias-stainless-steel-scrap-prices-strengthen-amid-tight-supply-and-firm-alloy-costs (2026-08-21)",
   "confidence": "Low"
  },
  "mat-adc12": {
   "gbpPerKg": 2.3969,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); the anchor grade itself",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a380": {
   "gbpPerKg": 2.4404,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.018 (book £2.8 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-alsi10mg": {
   "gbpPerKg": 2.5189,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.051 (book £2.89 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a365": {
   "gbpPerKg": 2.4143,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.007 (book £2.77 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a413": {
   "gbpPerKg": 2.3969,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); the anchor grade itself",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a319": {
   "gbpPerKg": 2.5886,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.080 (book £2.97 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a390": {
   "gbpPerKg": 2.8762,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.200 (book £3.3 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a357": {
   "gbpPerKg": 2.7891,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.164 (book £3.2 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-lm25": {
   "gbpPerKg": 2.5973,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.084 (book £2.98 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-lm6": {
   "gbpPerKg": 2.545,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.062 (book £2.92 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-lm4": {
   "gbpPerKg": 2.5363,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.058 (book £2.91 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-almg5-cast": {
   "gbpPerKg": 2.6845,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.120 (book £3.08 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-a206": {
   "gbpPerKg": 3.1726,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.324 (book £3.64 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-en-ac-46200": {
   "gbpPerKg": 2.484,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.036 (book £2.85 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-en-ac-45300": {
   "gbpPerKg": 2.7106,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.131 (book £3.11 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-lm13": {
   "gbpPerKg": 2.6845,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.120 (book £3.08 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-aural5": {
   "gbpPerKg": 2.6758,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.116 (book £3.07 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-silafont36": {
   "gbpPerKg": 2.7019,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.127 (book £3.1 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-castasil37": {
   "gbpPerKg": 2.6409,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.102 (book £3.03 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-magsimal59": {
   "gbpPerKg": 2.7455,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.145 (book £3.15 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-al-hpdc-lowco2": {
   "gbpPerKg": 2.6148,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.091 (book £3 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-htf-gigacast": {
   "gbpPerKg": 2.8762,
   "basis": "Cast aluminium alloys: ADC12 alloy ingot, SMM 7 Oct 2026: Mumbai ₹305,000/t, Delhi ₹304,750/t (an automaker bought at ₹304,500/t) — mean; ADC12, A380 and secondary ADC12 are the same Indian market (made from scrap). Other alloys × the book's premium over ADC12 (India LM6 / LM25 / A356 / AlSi10Mg ingot prices not found); ladder ×1.200 (book £3.3 ÷ base £2.75)",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-adc12-secondary": {
   "gbpPerKg": 2.3969,
   "basis": "Secondary ADC12: Same Indian ADC12 market (SMM 7 Oct 2026): Indian ADC12 is scrap-based — the book's ₹248 \"secondary\" sat ₹57 below it; direct",
   "source": "https://news.metal.com/newscontent/104146665-smm-analysis-indian-adc-12-prices-drop-as-automakers-cut-purchases-amid-lme-aluminium-decline (2026-10-07)",
   "confidence": "Medium"
  },
  "mat-c101-bar": {
   "gbpPerKg": 10.8884,
   "basis": "ETP copper bar / sheet (floor): Copper cathode ₹1,385/kg (MCX ₹1,384.75, 11 Sep 2026; Oct ≈ $6.49/lb) — the book's ETP bar ₹1,370 and sheet ₹1,336 were below the copper they contain; conversion premium not found, so floored at metal; floor (raised to metal content)",
   "source": "https://www.alpha-maven.com/story/venture-capital/commodity-update-copper-sourcebenchmarkmineralscom (2026-10-02) ; https://www.jmfinancialservices.in/market-news-and-insights/1732126 (2026-09-11)",
   "confidence": "Low"
  },
  "mat-c110-copper": {
   "gbpPerKg": 10.8884,
   "basis": "ETP copper bar / sheet (floor): Copper cathode ₹1,385/kg (MCX ₹1,384.75, 11 Sep 2026; Oct ≈ $6.49/lb) — the book's ETP bar ₹1,370 and sheet ₹1,336 were below the copper they contain; conversion premium not found, so floored at metal; floor (raised to metal content)",
   "source": "https://www.alpha-maven.com/story/venture-capital/commodity-update-copper-sourcebenchmarkmineralscom (2026-10-02) ; https://www.jmfinancialservices.in/market-news-and-insights/1732126 (2026-09-11)",
   "confidence": "Low"
  },
  "mat-ab2-cast": {
   "gbpPerKg": 9.6305,
   "basis": "Aluminium bronze AB2 (floor): Metal content of CuAl10Ni5Fe5 ≈ ₹1,225/kg (Cu + Al + Ni + Fe at the anchors) — the book's AB2 casting ₹1,183 was below it; floor (raised to metal content)",
   "source": "https://cbonds.com/indexes/181085/ (2026-10)",
   "confidence": "Low"
  },
  "mat-pp-homo": {
   "gbpPerKg": 1.0169,
   "basis": "PP family: PP: Delhi ex-godown ₹131.0 (Credco, 25 Sep 2026) and India index ₹127.7 (IMARC, Sep 2026) — mean; grades × the book's premium over PP homopolymer; the anchor grade itself",
   "source": "https://credcosourcing.com/prices (2026-09-25) ; https://www.imarcgroup.com/polypropylene-pricing-report (2026-09)",
   "confidence": "Medium"
  },
  "mat-pp": {
   "gbpPerKg": 1.1813,
   "basis": "PP family: PP: Delhi ex-godown ₹131.0 (Credco, 25 Sep 2026) and India index ₹127.7 (IMARC, Sep 2026) — mean; grades × the book's premium over PP homopolymer; ladder ×1.162 (book £1.15 ÷ base £0.99)",
   "source": "https://credcosourcing.com/prices (2026-09-25) ; https://www.imarcgroup.com/polypropylene-pricing-report (2026-09)",
   "confidence": "Medium"
  },
  "mat-pp-impact": {
   "gbpPerKg": 1.0683,
   "basis": "PP family: PP: Delhi ex-godown ₹131.0 (Credco, 25 Sep 2026) and India index ₹127.7 (IMARC, Sep 2026) — mean; grades × the book's premium over PP homopolymer; ladder ×1.051 (book £1.04 ÷ base £0.99)",
   "source": "https://credcosourcing.com/prices (2026-09-25) ; https://www.imarcgroup.com/polypropylene-pricing-report (2026-09)",
   "confidence": "Medium"
  },
  "mat-pp-bm": {
   "gbpPerKg": 1.1402,
   "basis": "PP family: PP: Delhi ex-godown ₹131.0 (Credco, 25 Sep 2026) and India index ₹127.7 (IMARC, Sep 2026) — mean; grades × the book's premium over PP homopolymer; ladder ×1.121 (book £1.11 ÷ base £0.99)",
   "source": "https://credcosourcing.com/prices (2026-09-25) ; https://www.imarcgroup.com/polypropylene-pricing-report (2026-09)",
   "confidence": "Medium"
  },
  "mat-ppr-pipe": {
   "gbpPerKg": 1.2018,
   "basis": "PP family: PP: Delhi ex-godown ₹131.0 (Credco, 25 Sep 2026) and India index ₹127.7 (IMARC, Sep 2026) — mean; grades × the book's premium over PP homopolymer; ladder ×1.182 (book £1.17 ÷ base £0.99)",
   "source": "https://credcosourcing.com/prices (2026-09-25) ; https://www.imarcgroup.com/polypropylene-pricing-report (2026-09)",
   "confidence": "Medium"
  },
  "mat-pp-roto": {
   "gbpPerKg": 1.5202,
   "basis": "PP family: PP: Delhi ex-godown ₹131.0 (Credco, 25 Sep 2026) and India index ₹127.7 (IMARC, Sep 2026) — mean; grades × the book's premium over PP homopolymer; ladder ×1.495 (book £1.48 ÷ base £0.99)",
   "source": "https://credcosourcing.com/prices (2026-09-25) ; https://www.imarcgroup.com/polypropylene-pricing-report (2026-09)",
   "confidence": "Medium"
  },
  "mat-hdpe": {
   "gbpPerKg": 1.0692,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; the anchor grade itself",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-ldpe": {
   "gbpPerKg": 1.1099,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.038 (book £1.09 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-lldpe": {
   "gbpPerKg": 1.0692,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; the anchor grade itself",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-hdpe-bm": {
   "gbpPerKg": 1.1608,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.086 (book £1.14 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-hdpe-fuel-coex": {
   "gbpPerKg": 1.5681,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.467 (book £1.54 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-ldpe-bm": {
   "gbpPerKg": 1.2219,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.143 (book £1.2 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-lldpe-bm": {
   "gbpPerKg": 1.1914,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.114 (book £1.17 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-hdpe-profile": {
   "gbpPerKg": 1.0692,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; the anchor grade itself",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-ldpe-tube": {
   "gbpPerKg": 1.1099,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.038 (book £1.09 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-hdpe-roto": {
   "gbpPerKg": 1.3136,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.229 (book £1.29 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-lldpe-roto": {
   "gbpPerKg": 1.4969,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.400 (book £1.47 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-xlpe-roto": {
   "gbpPerKg": 1.7718,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.657 (book £1.74 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-fr-pe-roto": {
   "gbpPerKg": 2.729,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×2.552 (book £2.68 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-foam-pe-roto": {
   "gbpPerKg": 2.0264,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.895 (book £1.99 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-cond-pe-roto": {
   "gbpPerKg": 2.5355,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×2.371 (book £2.49 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-pex-pipe": {
   "gbpPerKg": 1.6394,
   "basis": "PE family: HDPE: Delhi ex-godown GAIL ₹135.5, Haldia ₹136.5 (Credco, 25 Sep 2026) — mean; LDPE / LLDPE / blow / pipe / roto / sheet grades × the book's premium over HDPE; ladder ×1.533 (book £1.61 ÷ base £1.05)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-upvc": {
   "gbpPerKg": 0.8039,
   "basis": "PVC family: PVC K67: Delhi ex-godown ₹108.0 and Hygain ₹96.5 (Credco, 25 Sep 2026) — mean; compounds × the book's premium over uPVC; the anchor grade itself",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-fpvc": {
   "gbpPerKg": 1.174,
   "basis": "PVC family: PVC K67: Delhi ex-godown ₹108.0 and Hygain ₹96.5 (Credco, 25 Sep 2026) — mean; compounds × the book's premium over uPVC; ladder ×1.461 (book £1.11 ÷ base £0.76)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-pvc-bm": {
   "gbpPerKg": 0.899,
   "basis": "PVC family: PVC K67: Delhi ex-godown ₹108.0 and Hygain ₹96.5 (Credco, 25 Sep 2026) — mean; compounds × the book's premium over uPVC; ladder ×1.118 (book £0.85 ÷ base £0.76)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-upvc-window-profile": {
   "gbpPerKg": 1.3644,
   "basis": "PVC family: PVC K67: Delhi ex-godown ₹108.0 and Hygain ₹96.5 (Credco, 25 Sep 2026) — mean; compounds × the book's premium over uPVC; ladder ×1.697 (book £1.29 ÷ base £0.76)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-pvcp-profile": {
   "gbpPerKg": 1.6289,
   "basis": "PVC family: PVC K67: Delhi ex-godown ₹108.0 and Hygain ₹96.5 (Credco, 25 Sep 2026) — mean; compounds × the book's premium over uPVC; ladder ×2.026 (book £1.54 ÷ base £0.76)",
   "source": "https://credcosourcing.com/prices (2026-09-25)",
   "confidence": "Medium"
  },
  "mat-pet-bg": {
   "gbpPerKg": 0.8215,
   "basis": "PET: PET bottle chip, India index ₹104.5 (Sep 2026); the anchor grade itself",
   "source": "https://www.polyestertime.com/pet-bottle-grade-chip-price-trends/ (2026-09-10)",
   "confidence": "Low"
  },
  "mat-pet-preform": {
   "gbpPerKg": 0.8487,
   "basis": "PET: PET bottle chip, India index ₹104.5 (Sep 2026); ladder ×1.033 (book £1.25 ÷ base £1.21)",
   "source": "https://www.polyestertime.com/pet-bottle-grade-chip-price-trends/ (2026-09-10)",
   "confidence": "Low"
  },
  "mat-abs": {
   "gbpPerKg": 1.3003,
   "basis": "ABS family: ABS India index ₹165.4 (Business Analytiq, Sep 2026); the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/abs-price-index/ (2026-09)",
   "confidence": "Low"
  },
  "mat-pc": {
   "gbpPerKg": 1.7038,
   "basis": "PC family: PC CIF India ₹200.2 (Jul 2026) × 1.0825 (BCD 7.5% + SWS, back in force from 1 Jul 2026); domestic May average ₹211 agrees; the anchor grade itself",
   "source": "https://www.procurementresource.com/resource-center/polycarbonate-price-trends (2026-07) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pc-glazing": {
   "gbpPerKg": 2.8396,
   "basis": "PC family: PC CIF India ₹200.2 (Jul 2026) × 1.0825 (BCD 7.5% + SWS, back in force from 1 Jul 2026); domestic May average ₹211 agrees; ladder ×1.667 (book £4.2 ÷ base £2.52)",
   "source": "https://www.procurementresource.com/resource-center/polycarbonate-price-trends (2026-07) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pc-bm": {
   "gbpPerKg": 2.6368,
   "basis": "PC family: PC CIF India ₹200.2 (Jul 2026) × 1.0825 (BCD 7.5% + SWS, back in force from 1 Jul 2026); domestic May average ₹211 agrees; ladder ×1.548 (book £3.9 ÷ base £2.52)",
   "source": "https://www.procurementresource.com/resource-center/polycarbonate-price-trends (2026-07) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pa6": {
   "gbpPerKg": 1.6459,
   "basis": "PA6 family: PA6 CIF India ₹193.4 (Jun 2026, Plastemart) × 1.0825 duty; a second source reads higher (₹259) — the lower, dated figure is used; the anchor grade itself",
   "source": "https://www.plastemart.com/nylon-6-PA-6-cif-india-prices (2026-06) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pa6-bm": {
   "gbpPerKg": 3.0371,
   "basis": "PA6 family: PA6 CIF India ₹193.4 (Jun 2026, Plastemart) × 1.0825 duty; a second source reads higher (₹259) — the lower, dated figure is used; ladder ×1.845 (book £3.1 ÷ base £1.68)",
   "source": "https://www.plastemart.com/nylon-6-PA-6-cif-india-prices (2026-06) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pa6-ext-tube": {
   "gbpPerKg": 1.6459,
   "basis": "PA6 family: PA6 CIF India ₹193.4 (Jun 2026, Plastemart) × 1.0825 duty; a second source reads higher (₹259) — the lower, dated figure is used; the anchor grade itself",
   "source": "https://www.plastemart.com/nylon-6-PA-6-cif-india-prices (2026-06) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pa66": {
   "gbpPerKg": 2.2637,
   "basis": "PA66 family: PA66 CIF India ₹266.0 (Jun 2026, Plastemart) × 1.0825 duty; the anchor grade itself",
   "source": "https://www.plastemart.com/nylon-66-PA-66-polymer-prices-cif-india-pricelist (2026-06) ; https://www.taxscan.in/top-stories/cbic-slashes-import-duty-on-40-chemicals-plastics-raw-materials-1444480 (2026-04-02)",
   "confidence": "Low"
  },
  "mat-pbt": {
   "gbpPerKg": 1.9544,
   "basis": "PBT family: PBT India index ₹248.6 (Business Analytiq, Sep 2026); moderate confidence; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polybutylene-terephthalate-pbt-price-index/ (2026-09)",
   "confidence": "Low"
  },
  "mat-nr": {
   "gbpPerKg": 2.1855,
   "basis": "Natural rubber (raw): RSS-4 Kottayam ₹278/kg (Rubber Board figure, 26 Sep 2026) for the book's raw NR SMR20 line; compounds (70 Shore A) held; direct",
   "source": "https://thecanarapost.com/todays-rubber-prices-kottayam-and-international-market/ (2026-09-26)",
   "confidence": "Medium"
  }
 },
 "machines": {
  "hoursPerYear": 7200,
  "shiftDepreciationFactor": 1.3333,
  "lifeYears": 7.5,
  "financeRate": 0.0875,
  "ukFinanceRate": 0.04,
  "maintenancePctOfCapex": 0.035,
  "rentGbpPerM2Yr": 25.4373,
  "ukRentGbpPerM2Yr": 110,
  "ukElectricityGbpPerKwh": 0.182,
  "labourRatio": 0.0455,
  "capitalHeldFactor": 0.52,
  "basis": "3 shifts × 8 h × 300 working days (Indian cost-accounting convention); Companies Act 2013 Schedule II: depreciation +50% for double shift, +100% for triple — a held (2-shift) capital charge × 2.0 / 1.5 at 3 shifts; 1-year MCLR 8.70–8.80% (SBI, BoB, BoI, Jul–Oct 2026); the book's line build-ups use 4% on half the capex; rent ₹25.05/sq ft/month (Knight Frank H1 2026 industrial / warehousing rent: Pune 28.7, Chennai 25.7, Bengaluru 23.5, NCR 22.3 ₹/sq ft/month — mean); maintenance the library's own line build-up rule (3.5% of capex); no Indian norm found",
  "heldBasis": "capex not sourced for India: the book's capital (UK × 0.52) is HELD; the India operating model (3-shift hours, Schedule II, finance, rent, tariff, support at India wages) is applied",
  "groups": [
   {
    "id": "cnc-machining-domestic",
    "match": "^(mach-vmc3|mach-haas-vf2|mach-lathe-cnc|mach-mazak-qt200|mach-drill)$",
    "refId": "mach-vmc3",
    "refCapexGbp": 27169.81,
    "basis": "Jyoti CNC average realisation per machine sold ₹34.56 lakh (Q1 FY27; domestic VMC / turning-centre maker); an Indian-built machine of the class — an imported HAAS / Mazak costs more (not found)",
    "source": "https://compoundingai.in/market-news/jyoticnc-q1-fy27-earnings-call",
    "confidence": "Medium"
   }
  ]
 }
};
