/**
 * Poland rate book — GENERATED by `scripts/country-book.ts` from `scripts/rate-refresh/2026-10-poland.json`.
 * Do not edit by hand: change the config (every figure carries its source there) and re-run the script.
 * Register of every rate (current v new, decision, basis): scripts/rate-refresh/poland-2026-10/register.csv.
 */
import type { CountryBook } from '../country-books.js';

export const POLAND_BOOK: CountryBook = {
 "region": "PL",
 "asOf": "2026-10-10",
 "fxToGBP": 5.096,
 "currencySymbol": "zł",
 "labourGrades": {
  "forge": {
   "gbpPerHr": 11.7681,
   "basis": "3 × 8 h Mon–Fri. Pay: 12 × 6,867 = 82,404 − sick-pay saving 20% × 10 days × (6,867 ÷ 20.92 days) 657 = 81,747; + night allowance 5.744 PLN/h × (1,720 ÷ 3 = 573.3 night h) = 3,293; + employer on-costs 21.98% × contribution base (82,404 − sick days 3,283 + night 3,293 = 82,414) = 18,115; annual cost 103,155 ÷ 1,720 productive h = 59.97. Included: Fully-loaded hourly cost INCLUDES: gross total pay (Sedlak OBW \"wynagrodzenie całkowite\" = base + bonuses / variable pay, indexed to 2026 and adjusted to the four clusters), paid annual leave and public holidays (inside the 12 monthly salaries), sick pay at 80% for 10 days, the statutory night allowance on one third of hours worked (3 × 8 h, shop-floor roles), and employer ZUS + FP + FGŚP + PPK (21.98%); divided by 1,720 productive hours.. NOT included: NOT included (not sourced): 13th-month salary (no statutory 13th month in Polish private industry — any annual bonus is already inside OBW total pay), shift allowances above the statutory night allowance, ZFŚS social fund write-off (mandatory at ≥50 FTE), bridging-pension FEP 1.5%, PFRON, meal / transport / work-clothing / medical exams, training time, overtime and weekend premiums, agency-worker margins, severance and jubilee-award accruals.",
   "source": "https://wynagrodzenia.pl/moja-placa/ile-zarabia-operator-pras",
   "confidence": "Medium"
  },
  "furnace": {
   "gbpPerHr": 11.1009,
   "basis": "3 × 8 h Mon–Fri. Pay: 12 × 6,462 = 77,544 − sick-pay saving 20% × 10 days × (6,462 ÷ 20.92 days) 618 = 76,926; + night allowance 5.744 PLN/h × (1,720 ÷ 3 = 573.3 night h) = 3,293; + employer on-costs 21.98% × contribution base (77,544 − sick days 3,089 + night 3,293 = 77,748) = 17,089; annual cost 97,308 ÷ 1,720 productive h = 56.57. Included: Fully-loaded hourly cost INCLUDES: gross total pay (Sedlak OBW \"wynagrodzenie całkowite\" = base + bonuses / variable pay, indexed to 2026 and adjusted to the four clusters), paid annual leave and public holidays (inside the 12 monthly salaries), sick pay at 80% for 10 days, the statutory night allowance on one third of hours worked (3 × 8 h, shop-floor roles), and employer ZUS + FP + FGŚP + PPK (21.98%); divided by 1,720 productive hours.. NOT included: NOT included (not sourced): 13th-month salary (no statutory 13th month in Polish private industry — any annual bonus is already inside OBW total pay), shift allowances above the statutory night allowance, ZFŚS social fund write-off (mandatory at ≥50 FTE), bridging-pension FEP 1.5%, PFRON, meal / transport / work-clothing / medical exams, training time, overtime and weekend premiums, agency-worker margins, severance and jubilee-award accruals.",
   "source": "https://wynagrodzenia.pl/moja-placa/ile-zarabia-formierz",
   "confidence": "Medium"
  },
  "blow": {
   "gbpPerHr": 10.8104,
   "basis": "3 × 8 h Mon–Fri. Pay: 12 × 6,285 = 75,420 − sick-pay saving 20% × 10 days × (6,285 ÷ 20.92 days) 601 = 74,819; + night allowance 5.744 PLN/h × (1,720 ÷ 3 = 573.3 night h) = 3,293; + employer on-costs 21.98% × contribution base (75,420 − sick days 3,005 + night 3,293 = 75,709) = 16,641; annual cost 94,753 ÷ 1,720 productive h = 55.09. Included: Fully-loaded hourly cost INCLUDES: gross total pay (Sedlak OBW \"wynagrodzenie całkowite\" = base + bonuses / variable pay, indexed to 2026 and adjusted to the four clusters), paid annual leave and public holidays (inside the 12 monthly salaries), sick pay at 80% for 10 days, the statutory night allowance on one third of hours worked (3 × 8 h, shop-floor roles), and employer ZUS + FP + FGŚP + PPK (21.98%); divided by 1,720 productive hours.. NOT included: NOT included (not sourced): 13th-month salary (no statutory 13th month in Polish private industry — any annual bonus is already inside OBW total pay), shift allowances above the statutory night allowance, ZFŚS social fund write-off (mandatory at ≥50 FTE), bridging-pension FEP 1.5%, PFRON, meal / transport / work-clothing / medical exams, training time, overtime and weekend premiums, agency-worker margins, severance and jubilee-award accruals.",
   "source": "https://wynagrodzenia.pl/moja-placa/ile-zarabia-operator-wtryskarki",
   "confidence": "Medium"
  },
  "roto": {
   "gbpPerHr": 10.8104,
   "basis": "3 × 8 h Mon–Fri. Pay: 12 × 6,285 = 75,420 − sick-pay saving 20% × 10 days × (6,285 ÷ 20.92 days) 601 = 74,819; + night allowance 5.744 PLN/h × (1,720 ÷ 3 = 573.3 night h) = 3,293; + employer on-costs 21.98% × contribution base (75,420 − sick days 3,005 + night 3,293 = 75,709) = 16,641; annual cost 94,753 ÷ 1,720 productive h = 55.09. Included: Fully-loaded hourly cost INCLUDES: gross total pay (Sedlak OBW \"wynagrodzenie całkowite\" = base + bonuses / variable pay, indexed to 2026 and adjusted to the four clusters), paid annual leave and public holidays (inside the 12 monthly salaries), sick pay at 80% for 10 days, the statutory night allowance on one third of hours worked (3 × 8 h, shop-floor roles), and employer ZUS + FP + FGŚP + PPK (21.98%); divided by 1,720 productive hours.. NOT included: NOT included (not sourced): 13th-month salary (no statutory 13th month in Polish private industry — any annual bonus is already inside OBW total pay), shift allowances above the statutory night allowance, ZFŚS social fund write-off (mandatory at ≥50 FTE), bridging-pension FEP 1.5%, PFRON, meal / transport / work-clothing / medical exams, training time, overtime and weekend premiums, agency-worker margins, severance and jubilee-award accruals.",
   "source": "https://wynagrodzenia.pl/moja-placa/ile-zarabia-operator-wtryskarki",
   "confidence": "Medium"
  },
  "thermoform": {
   "gbpPerHr": 10.8104,
   "basis": "3 × 8 h Mon–Fri. Pay: 12 × 6,285 = 75,420 − sick-pay saving 20% × 10 days × (6,285 ÷ 20.92 days) 601 = 74,819; + night allowance 5.744 PLN/h × (1,720 ÷ 3 = 573.3 night h) = 3,293; + employer on-costs 21.98% × contribution base (75,420 − sick days 3,005 + night 3,293 = 75,709) = 16,641; annual cost 94,753 ÷ 1,720 productive h = 55.09. Included: Fully-loaded hourly cost INCLUDES: gross total pay (Sedlak OBW \"wynagrodzenie całkowite\" = base + bonuses / variable pay, indexed to 2026 and adjusted to the four clusters), paid annual leave and public holidays (inside the 12 monthly salaries), sick pay at 80% for 10 days, the statutory night allowance on one third of hours worked (3 × 8 h, shop-floor roles), and employer ZUS + FP + FGŚP + PPK (21.98%); divided by 1,720 productive hours.. NOT included: NOT included (not sourced): 13th-month salary (no statutory 13th month in Polish private industry — any annual bonus is already inside OBW total pay), shift allowances above the statutory night allowance, ZFŚS social fund write-off (mandatory at ≥50 FTE), bridging-pension FEP 1.5%, PFRON, meal / transport / work-clothing / medical exams, training time, overtime and weekend premiums, agency-worker margins, severance and jubilee-award accruals.",
   "source": "https://wynagrodzenia.pl/moja-placa/ile-zarabia-operator-wtryskarki",
   "confidence": "Medium"
  },
  "trim-router": {
   "gbpPerHr": 13.0181,
   "basis": "3 × 8 h Mon–Fri. Pay: 12 × 7,625 = 91,500 − sick-pay saving 20% × 10 days × (7,625 ÷ 20.92 days) 729 = 90,771; + night allowance 5.744 PLN/h × (1,720 ÷ 3 = 573.3 night h) = 3,293; + employer on-costs 21.98% × contribution base (91,500 − sick days 3,645 + night 3,293 = 91,148) = 20,034; annual cost 114,099 ÷ 1,720 productive h = 66.34. Included: Fully-loaded hourly cost INCLUDES: gross total pay (Sedlak OBW \"wynagrodzenie całkowite\" = base + bonuses / variable pay, indexed to 2026 and adjusted to the four clusters), paid annual leave and public holidays (inside the 12 monthly salaries), sick pay at 80% for 10 days, the statutory night allowance on one third of hours worked (3 × 8 h, shop-floor roles), and employer ZUS + FP + FGŚP + PPK (21.98%); divided by 1,720 productive hours.. NOT included: NOT included (not sourced): 13th-month salary (no statutory 13th month in Polish private industry — any annual bonus is already inside OBW total pay), shift allowances above the statutory night allowance, ZFŚS social fund write-off (mandatory at ≥50 FTE), bridging-pension FEP 1.5%, PFRON, meal / transport / work-clothing / medical exams, training time, overtime and weekend premiums, agency-worker margins, severance and jubilee-award accruals.",
   "source": "https://wynagrodzenia.pl/moja-placa/ile-zarabia-operator-cnc",
   "confidence": "Medium"
  }
 },
 "materials": {
  "mat-dc01": {
   "gbpPerKg": 0.7425,
   "basis": "CR coil (DC01 / DC04): NW Europe CRC €850–880/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.78/kg at zł4.374/€; freight to a Polish plant not added; direct",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Medium"
  },
  "mat-dc04": {
   "gbpPerKg": 0.7425,
   "basis": "CR coil (DC01 / DC04): NW Europe CRC €850–880/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.78/kg at zł4.374/€; freight to a Polish plant not added; direct",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Medium"
  },
  "mat-dc05": {
   "gbpPerKg": 0.7425,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; the anchor grade itself",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dc06": {
   "gbpPerKg": 0.7514,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.012 (book £0.85 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-if-dx56": {
   "gbpPerKg": 0.884,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.190 (book £1 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-if-hs260": {
   "gbpPerKg": 0.9989,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.345 (book £1.13 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-bh260": {
   "gbpPerKg": 0.9724,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.310 (book £1.1 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-greensteel-dc01": {
   "gbpPerKg": 0.9724,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.310 (book £1.1 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-hsla340": {
   "gbpPerKg": 1.0519,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.417 (book £1.19 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-hsla420": {
   "gbpPerKg": 1.1403,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.536 (book £1.29 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-hsla550": {
   "gbpPerKg": 1.2287,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.655 (book £1.39 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dp600": {
   "gbpPerKg": 1.1492,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.548 (book £1.3 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dp780": {
   "gbpPerKg": 1.2111,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.631 (book £1.37 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dp980": {
   "gbpPerKg": 1.326,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.786 (book £1.5 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dp1000": {
   "gbpPerKg": 1.3878,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.869 (book £1.57 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-trip780": {
   "gbpPerKg": 1.2818,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.726 (book £1.45 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-cp800": {
   "gbpPerKg": 1.2641,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.702 (book £1.43 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-ms1200": {
   "gbpPerKg": 1.4144,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.905 (book £1.6 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-ms1300": {
   "gbpPerKg": 1.4762,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.988 (book £1.67 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-ms1500": {
   "gbpPerKg": 1.5646,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×2.107 (book £1.77 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-qp980": {
   "gbpPerKg": 1.5293,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×2.060 (book £1.73 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-medmn1180": {
   "gbpPerKg": 1.5912,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×2.143 (book £1.8 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-22mnb5": {
   "gbpPerKg": 1.5823,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×2.131 (book £1.79 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-usibor1500": {
   "gbpPerKg": 1.768,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×2.381 (book £2 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-usibor2000": {
   "gbpPerKg": 2.1216,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×2.857 (book £2.4 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-c67s-spring": {
   "gbpPerKg": 1.4144,
   "basis": "CR automotive grades: CR coil zł3.78 × the book's grade premium over its DC01/DC04 mean (£0.84); European AHSS / press-hardening extras not found; ladder ×1.905 (book £1.6 ÷ base £0.84)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-s355mc": {
   "gbpPerKg": 0.6644,
   "basis": "HR structural: NW Europe HRC €745/t ex-works (Fastmarkets via Eurometal, 6 Oct 2026) = zł3.26/kg (Polish distributor index PUDS St3S sheet zł3.43, w/e 28 Sep, agrees) × the book's premium over HRPO; S355MC / S420MC extras not found; ladder ×1.039 (book £0.8 ÷ base £0.77)",
   "source": "https://eurometal.net/european-hrc-prices-edge-higher-despite-sluggish-demand/ (2026-10-06) ; https://www.wnp.pl/rynki/gielda-i-notowania/indeks-cen-stali-puds/ (2026-09-28)",
   "confidence": "Low"
  },
  "mat-s420mc": {
   "gbpPerKg": 0.681,
   "basis": "HR structural: NW Europe HRC €745/t ex-works (Fastmarkets via Eurometal, 6 Oct 2026) = zł3.26/kg (Polish distributor index PUDS St3S sheet zł3.43, w/e 28 Sep, agrees) × the book's premium over HRPO; S355MC / S420MC extras not found; ladder ×1.065 (book £0.82 ÷ base £0.77)",
   "source": "https://eurometal.net/european-hrc-prices-edge-higher-despite-sluggish-demand/ (2026-10-06) ; https://www.wnp.pl/rynki/gielda-i-notowania/indeks-cen-stali-puds/ (2026-09-28)",
   "confidence": "Low"
  },
  "mat-dc01-gi": {
   "gbpPerKg": 0.7382,
   "basis": "Coated sheet: NW Europe HDG €850–870/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.76/kg × the book's premium over DC01 GI; the anchor grade itself",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dc03-ga": {
   "gbpPerKg": 0.7648,
   "basis": "Coated sheet: NW Europe HDG €850–870/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.76/kg × the book's premium over DC01 GI; ladder ×1.036 (book £1.15 ÷ base £1.11)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-dc01-ze": {
   "gbpPerKg": 0.7382,
   "basis": "Coated sheet: NW Europe HDG €850–870/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.76/kg × the book's premium over DC01 GI; the anchor grade itself",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-znni-eg": {
   "gbpPerKg": 0.818,
   "basis": "Coated sheet: NW Europe HDG €850–870/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.76/kg × the book's premium over DC01 GI; ladder ×1.108 (book £1.23 ÷ base £1.11)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-zm-coated": {
   "gbpPerKg": 0.7981,
   "basis": "Coated sheet: NW Europe HDG €850–870/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.76/kg × the book's premium over DC01 GI; ladder ×1.081 (book £1.2 ÷ base £1.11)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-tinplate-etp": {
   "gbpPerKg": 0.8978,
   "basis": "Coated sheet: NW Europe HDG €850–870/t ex-works (13 Sep 2026, as relayed by Tacto) = zł3.76/kg × the book's premium over DC01 GI; ladder ×1.216 (book £1.35 ÷ base £1.11)",
   "source": "https://www.tacto.ai/en/commodities/steel-price (2026-09-13)",
   "confidence": "Low"
  },
  "mat-hrpo": {
   "gbpPerKg": 0.7166,
   "basis": "HR pickled & oiled: HRC €745/t (Fastmarkets N. Europe, 6 Oct 2026) + a German service-centre pickling extra ~€90/t (undated) = €835/t = zł3.65/kg — DERIVED; direct",
   "source": "https://eurometal.net/pickled-hrc-benefits-most-from-northwest-europe-hike/ (undated extra; HRC 2026-10-06)",
   "confidence": "Low"
  },
  "mat-ss409l-sheet": {
   "gbpPerKg": 1.2724,
   "basis": "409L / 441 ferritic sheet: Aperam Jul 2026 1.4512 surcharge €919/t + an effective base equal to 304's (as the 430 line) = zł6.48/kg — DERIVED; 441 at the book's premium over 409L; the anchor grade itself",
   "source": "https://news.metal.com/en/newscontent/104001715-smm-stainless-steel-flash-aperam-adjusts-stainless-steel-flat-products-surcharges-for-july-2026 (2026-07-01)",
   "confidence": "Low"
  },
  "mat-ss441-sheet": {
   "gbpPerKg": 1.4108,
   "basis": "409L / 441 ferritic sheet: Aperam Jul 2026 1.4512 surcharge €919/t + an effective base equal to 304's (as the 430 line) = zł6.48/kg — DERIVED; 441 at the book's premium over 409L; ladder ×1.109 (book £3.16 ÷ base £2.85)",
   "source": "https://news.metal.com/en/newscontent/104001715-smm-stainless-steel-flash-aperam-adjusts-stainless-steel-flat-products-surcharges-for-july-2026 (2026-07-01)",
   "confidence": "Low"
  },
  "mat-steel1045": {
   "gbpPerKg": 0.6226,
   "basis": "C45 medium-carbon bar: C45 round bar zł3.17/kg net (24metal.com Polish stockholder list, read 10 Oct 2026; the page is undated); direct",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-c45": {
   "gbpPerKg": 0.6226,
   "basis": "C45 medium-carbon bar: C45 round bar zł3.17/kg net (24metal.com Polish stockholder list, read 10 Oct 2026; the page is undated); direct",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-en8": {
   "gbpPerKg": 0.6226,
   "basis": "C45 medium-carbon bar: C45 round bar zł3.17/kg net (24metal.com Polish stockholder list, read 10 Oct 2026; the page is undated); direct",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-c35": {
   "gbpPerKg": 0.6154,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×0.988 (book £0.85 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel1020": {
   "gbpPerKg": 0.5937,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×0.953 (book £0.82 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-a105": {
   "gbpPerKg": 0.6082,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×0.977 (book £0.84 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-c70s6": {
   "gbpPerKg": 0.6661,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×1.070 (book £0.92 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel1141": {
   "gbpPerKg": 0.7602,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×1.221 (book £1.05 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-en3-bar": {
   "gbpPerKg": 0.6806,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×1.093 (book £0.94 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-11smnpb30": {
   "gbpPerKg": 0.8471,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×1.360 (book £1.17 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-30mnvs6": {
   "gbpPerKg": 0.8326,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-steel-38mnvs6": {
   "gbpPerKg": 0.8326,
   "basis": "Carbon / micro-alloyed bar: C45 bar zł3.17 × the book's premium over C45; 38MnVS / 11SMnPb30 / A105 extras not found; ladder ×1.337 (book £1.15 ÷ base £0.86)",
   "source": "https://24metal.com/pl/prety-okragle-gladkie/419-pret-gladki-c45-fi-24-dlugosc-6000-paczka-2-tony.html (undated (read 2026-10-10))",
   "confidence": "Low"
  },
  "mat-ss304-sheet": {
   "gbpPerKg": 2.3776,
   "basis": "304 sheet: 304 CR 2B €2,770/t delivered N. Europe incl. alloy surcharge (Eurometal, 7 Sep 2026) = zł12.12/kg; the October 1.4301 surcharge is €2,188/t (legierungszuschlag.info); direct",
   "source": "https://eurometal.net/subdued-buying-weighs-on-european-stainless-cr-sheet-prices/ (2026-09-07) ; https://legierungszuschlag.info/en/ (2026-10-01)",
   "confidence": "Medium"
  },
  "mat-ss301-spring": {
   "gbpPerKg": 3.086,
   "basis": "301 spring strip: 304 sheet zł12.12 × the book's premium of 301 over 304L sheet; ladder ×1.298 (book £4.53 ÷ base £3.49)",
   "source": "https://eurometal.net/subdued-buying-weighs-on-european-stainless-cr-sheet-prices/ (2026-09-07)",
   "confidence": "Low"
  },
  "mat-ss316-sheet": {
   "gbpPerKg": 3.6264,
   "basis": "316L sheet: 316 CR €4,225/t delivered N. Europe (Eurometal, 7 Sep 2026) = zł18.48/kg; 316L bar not found (held); direct",
   "source": "https://eurometal.net/subdued-buying-weighs-on-european-stainless-cr-sheet-prices/ (2026-09-07)",
   "confidence": "Medium"
  },
  "mat-ss316l": {
   "gbpPerKg": 3.6264,
   "basis": "316L sheet: 316 CR €4,225/t delivered N. Europe (Eurometal, 7 Sep 2026) = zł18.48/kg; 316L bar not found (held); direct",
   "source": "https://eurometal.net/subdued-buying-weighs-on-european-stainless-cr-sheet-prices/ (2026-09-07)",
   "confidence": "Medium"
  },
  "mat-aisi430": {
   "gbpPerKg": 1.3291,
   "basis": "430 ferritic sheet: 430 CR zł6.77/kg — DERIVED: the October 1.4016 alloy surcharge €985/t + a base assumed equal to 304's (no 430 transaction price found); direct",
   "source": "https://legierungszuschlag.info/en/ (2026-10-01)",
   "confidence": "Low"
  },
  "mat-gjs500": {
   "gbpPerKg": 0.3395,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); the anchor grade itself",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjs400": {
   "gbpPerKg": 0.2995,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł-0.20/kg (the book's premium: £0.82 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjs450-ssf": {
   "gbpPerKg": 0.3095,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł-0.15/kg (the book's premium: £0.83 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjs500-14": {
   "gbpPerKg": 0.3195,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł-0.10/kg (the book's premium: £0.84 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjs600": {
   "gbpPerKg": 0.3795,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł0.20/kg (the book's premium: £0.9 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjs700": {
   "gbpPerKg": 0.4295,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł0.46/kg (the book's premium: £0.95 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjs350-lt": {
   "gbpPerKg": 0.3495,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł0.05/kg (the book's premium: £0.87 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-simo": {
   "gbpPerKg": 0.8295,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł2.50/kg (the book's premium: £1.35 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-adi": {
   "gbpPerKg": 1.0595,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł3.67/kg (the book's premium: £1.58 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjv450": {
   "gbpPerKg": 0.5995,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł1.32/kg (the book's premium: £1.12 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjv500": {
   "gbpPerKg": 0.6295,
   "basis": "Ductile / CGI / ADI / SiMo iron (charge): Treated ductile charge zł1.73/kg (45% merchant pig zł1.86 — Brazil→Italy Aug 2026 — + 30% heavy scrap zł1.20 + returns, FeSiMg and inoculant priced at FeSi75 zł5.51; the mix is an engineering assumption and the figure a FLOOR — arithmetic in research) + the book's grade premium in £/kg at zł5.096/£ (alloy content; ADI's austempering, which the casting engine does not add); ladder +zł1.48/kg (the book's premium: £1.15 - base £0.86)",
   "source": "https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16)) ; https://api.argusmedia.com/articles/2840817 (2026-06-16)",
   "confidence": "Low"
  },
  "mat-gjl250": {
   "gbpPerKg": 0.2983,
   "basis": "Grey / malleable iron (charge): Grey-iron charge zł1.52/kg (merchant pig + heavy scrap + returns; engineering-assumption mix, a FLOOR) × the book's grade premium over GJL-250; the anchor grade itself",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08)",
   "confidence": "Low"
  },
  "mat-gjl150": {
   "gbpPerKg": 0.261,
   "basis": "Grey / malleable iron (charge): Grey-iron charge zł1.52/kg (merchant pig + heavy scrap + returns; engineering-assumption mix, a FLOOR) × the book's grade premium over GJL-250; ladder ×0.875 (book £0.56 ÷ base £0.64)",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08)",
   "confidence": "Low"
  },
  "mat-gjl200": {
   "gbpPerKg": 0.2796,
   "basis": "Grey / malleable iron (charge): Grey-iron charge zł1.52/kg (merchant pig + heavy scrap + returns; engineering-assumption mix, a FLOOR) × the book's grade premium over GJL-250; ladder ×0.938 (book £0.6 ÷ base £0.64)",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08)",
   "confidence": "Low"
  },
  "mat-gjl300": {
   "gbpPerKg": 0.3262,
   "basis": "Grey / malleable iron (charge): Grey-iron charge zł1.52/kg (merchant pig + heavy scrap + returns; engineering-assumption mix, a FLOOR) × the book's grade premium over GJL-250; ladder ×1.094 (book £0.7 ÷ base £0.64)",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08)",
   "confidence": "Low"
  },
  "mat-gjl350": {
   "gbpPerKg": 0.3449,
   "basis": "Grey / malleable iron (charge): Grey-iron charge zł1.52/kg (merchant pig + heavy scrap + returns; engineering-assumption mix, a FLOOR) × the book's grade premium over GJL-250; ladder ×1.156 (book £0.74 ÷ base £0.64)",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08)",
   "confidence": "Low"
  },
  "mat-gjmb350": {
   "gbpPerKg": 0.3076,
   "basis": "Grey / malleable iron (charge): Grey-iron charge zł1.52/kg (merchant pig + heavy scrap + returns; engineering-assumption mix, a FLOOR) × the book's grade premium over GJL-250; ladder ×1.031 (book £0.66 ÷ base £0.64)",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/prices-for-brazilian-pig-iron-stabilised-at-475-per-tonne-in-august/ (2026-08)",
   "confidence": "Low"
  },
  "mat-gs-c25": {
   "gbpPerKg": 0.2512,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge zł1.28/kg (heavy melting scrap zł1.20 — German E3 / Polish scrap boards, Aug 2026 — + deoxidation and melt loss) + the book's premium in £/kg (Cr–Mo); the anchor grade itself",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16))",
   "confidence": "Low"
  },
  "mat-astm-a216-wcb": {
   "gbpPerKg": 0.2512,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge zł1.28/kg (heavy melting scrap zł1.20 — German E3 / Polish scrap boards, Aug 2026 — + deoxidation and melt loss) + the book's premium in £/kg (Cr–Mo); the anchor grade itself",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16))",
   "confidence": "Low"
  },
  "mat-g20mn5": {
   "gbpPerKg": 0.2512,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge zł1.28/kg (heavy melting scrap zł1.20 — German E3 / Polish scrap boards, Aug 2026 — + deoxidation and melt loss) + the book's premium in £/kg (Cr–Mo); the anchor grade itself",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16))",
   "confidence": "Low"
  },
  "mat-g42crmo4": {
   "gbpPerKg": 0.3912,
   "basis": "Cast carbon / low-alloy steel (charge): Steel-foundry charge zł1.28/kg (heavy melting scrap zł1.20 — German E3 / Polish scrap boards, Aug 2026 — + deoxidation and melt loss) + the book's premium in £/kg (Cr–Mo); ladder +zł0.71/kg (the book's premium: £2.24 - base £2.1)",
   "source": "https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08) ; https://gmk.center/en/news/the-fall-in-scrap-prices-on-regional-markets-slowed-in-august/ (2026-08 (published 2026-09-16))",
   "confidence": "Low"
  },
  "mat-ss304-cast": {
   "gbpPerKg": 1.1068,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap zł5.64/kg (304 scrap $1,420/t CIF Rotterdam, mid-Sep 2026, ÷ 0.97 melt loss) + the book's premium in £/kg (Mo / Ni / Cr); the anchor grade itself",
   "source": "https://news.metal.com/newscontent/104124933-smm-stainless-steel-flash-indias-stainless-scrap-prices-fall-as-mills-shift-to-npi-and-billet-alternatives (2026-09-18)",
   "confidence": "Low"
  },
  "mat-cf8m-cast": {
   "gbpPerKg": 2.1968,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap zł5.64/kg (304 scrap $1,420/t CIF Rotterdam, mid-Sep 2026, ÷ 0.97 melt loss) + the book's premium in £/kg (Mo / Ni / Cr); ladder +zł5.55/kg (the book's premium: £6.26 - base £5.17)",
   "source": "https://news.metal.com/newscontent/104124933-smm-stainless-steel-flash-indias-stainless-scrap-prices-fall-as-mills-shift-to-npi-and-billet-alternatives (2026-09-18)",
   "confidence": "Low"
  },
  "mat-ca6nm-cast": {
   "gbpPerKg": 0.9268,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap zł5.64/kg (304 scrap $1,420/t CIF Rotterdam, mid-Sep 2026, ÷ 0.97 melt loss) + the book's premium in £/kg (Mo / Ni / Cr); ladder +zł-0.92/kg (the book's premium: £4.99 - base £5.17)",
   "source": "https://news.metal.com/newscontent/104124933-smm-stainless-steel-flash-indias-stainless-scrap-prices-fall-as-mills-shift-to-npi-and-billet-alternatives (2026-09-18)",
   "confidence": "Low"
  },
  "mat-cd4mcun-cast": {
   "gbpPerKg": 2.4468,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap zł5.64/kg (304 scrap $1,420/t CIF Rotterdam, mid-Sep 2026, ÷ 0.97 melt loss) + the book's premium in £/kg (Mo / Ni / Cr); ladder +zł6.83/kg (the book's premium: £6.51 - base £5.17)",
   "source": "https://news.metal.com/newscontent/104124933-smm-stainless-steel-flash-indias-stainless-scrap-prices-fall-as-mills-shift-to-npi-and-billet-alternatives (2026-09-18)",
   "confidence": "Low"
  },
  "mat-gx40crnisi25-20": {
   "gbpPerKg": 2.5868,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap zł5.64/kg (304 scrap $1,420/t CIF Rotterdam, mid-Sep 2026, ÷ 0.97 melt loss) + the book's premium in £/kg (Mo / Ni / Cr); ladder +zł7.54/kg (the book's premium: £6.65 - base £5.17)",
   "source": "https://news.metal.com/newscontent/104124933-smm-stainless-steel-flash-indias-stainless-scrap-prices-fall-as-mills-shift-to-npi-and-billet-alternatives (2026-09-18)",
   "confidence": "Low"
  },
  "mat-17-4ph-cast": {
   "gbpPerKg": 5.5368,
   "basis": "Cast stainless (charge): CF8 charged as 304 scrap zł5.64/kg (304 scrap $1,420/t CIF Rotterdam, mid-Sep 2026, ÷ 0.97 melt loss) + the book's premium in £/kg (Mo / Ni / Cr); ladder +zł22.58/kg (the book's premium: £9.6 - base £5.17)",
   "source": "https://news.metal.com/newscontent/104124933-smm-stainless-steel-flash-indias-stainless-scrap-prices-fall-as-mills-shift-to-npi-and-billet-alternatives (2026-09-18)",
   "confidence": "Low"
  },
  "mat-ni-resist-d2": {
   "gbpPerKg": 2.8356,
   "basis": "Ni-Resist D-2 (charge): 0.20 × Ni zł64.18 (LME, 8 Sep) + 0.02 × Cr zł13.24 (HC FeCr) + 0.78 × ductile charge zł1.73; direct",
   "source": "https://www.westmetall.com/de/markdaten.php (2026-09-08) ; https://news.metal.com/en/newscontent/104046674-samchrome-sets-the-reference-point-156-us-centslb-for-q3-2026-european-ferrochrome (2026-Q3)",
   "confidence": "Low"
  },
  "mat-ni-resist-d5s": {
   "gbpPerKg": 4.7035,
   "basis": "Ni-Resist D-5S (charge): 0.35 × Ni + 0.02 × Cr + 0.04 kg FeSi75 zł5.511 + 0.59 × ductile charge; direct",
   "source": "https://www.westmetall.com/de/markdaten.php (2026-09-08)",
   "confidence": "Low"
  },
  "mat-hicr-white": {
   "gbpPerKg": 0.8271,
   "basis": "High-Cr white iron (charge): 0.23 × Cr zł13.24 + 0.77 × grey charge zł1.52; direct",
   "source": "https://news.metal.com/en/newscontent/104046674-samchrome-sets-the-reference-point-156-us-centslb-for-q3-2026-european-ferrochrome (2026-Q3)",
   "confidence": "Low"
  },
  "mat-adc12": {
   "gbpPerKg": 2.1291,
   "basis": "Secondary cast aluminium (ingot): Fastmarkets DIN226 / A380 pressure-diecasting ingot €2,430–2,530/t delivered Europe = zł10.85/kg — the latest public print is 23 Jan 2026 (STALE; the Rotterdam premium has risen since) × the book's premium over ADC12; the anchor grade itself",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-a380": {
   "gbpPerKg": 2.1678,
   "basis": "Secondary cast aluminium (ingot): Fastmarkets DIN226 / A380 pressure-diecasting ingot €2,430–2,530/t delivered Europe = zł10.85/kg — the latest public print is 23 Jan 2026 (STALE; the Rotterdam premium has risen since) × the book's premium over ADC12; ladder ×1.018 (book £2.8 ÷ base £2.75)",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-a413": {
   "gbpPerKg": 2.1291,
   "basis": "Secondary cast aluminium (ingot): Fastmarkets DIN226 / A380 pressure-diecasting ingot €2,430–2,530/t delivered Europe = zł10.85/kg — the latest public print is 23 Jan 2026 (STALE; the Rotterdam premium has risen since) × the book's premium over ADC12; the anchor grade itself",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-a319": {
   "gbpPerKg": 2.2995,
   "basis": "Secondary cast aluminium (ingot): Fastmarkets DIN226 / A380 pressure-diecasting ingot €2,430–2,530/t delivered Europe = zł10.85/kg — the latest public print is 23 Jan 2026 (STALE; the Rotterdam premium has risen since) × the book's premium over ADC12; ladder ×1.080 (book £2.97 ÷ base £2.75)",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-lm4": {
   "gbpPerKg": 2.253,
   "basis": "Secondary cast aluminium (ingot): Fastmarkets DIN226 / A380 pressure-diecasting ingot €2,430–2,530/t delivered Europe = zł10.85/kg — the latest public print is 23 Jan 2026 (STALE; the Rotterdam premium has risen since) × the book's premium over ADC12; ladder ×1.058 (book £2.91 ÷ base £2.75)",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-en-ac-46200": {
   "gbpPerKg": 2.2065,
   "basis": "Secondary cast aluminium (ingot): Fastmarkets DIN226 / A380 pressure-diecasting ingot €2,430–2,530/t delivered Europe = zł10.85/kg — the latest public print is 23 Jan 2026 (STALE; the Rotterdam premium has risen since) × the book's premium over ADC12; ladder ×1.036 (book £2.85 ÷ base £2.75)",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-adc12-secondary": {
   "gbpPerKg": 2.1291,
   "basis": "Secondary ADC12: DIN226 zł10.85 (Jan 2026, stale); direct",
   "source": "https://www.fastmarkets.com/insights/eu-secondary-aluminium-prices-firm-as-scrap-shortages-bite/ (2026-01-23)",
   "confidence": "Low"
  },
  "mat-lm25": {
   "gbpPerKg": 3.2084,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); the anchor grade itself",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-a365": {
   "gbpPerKg": 3.2084,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); the anchor grade itself",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-alsi10mg": {
   "gbpPerKg": 3.2084,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); the anchor grade itself",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-a390": {
   "gbpPerKg": 3.5529,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.107 (book £3.3 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-a357": {
   "gbpPerKg": 3.4453,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.074 (book £3.2 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-lm6": {
   "gbpPerKg": 3.2084,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); the anchor grade itself",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-almg5-cast": {
   "gbpPerKg": 3.3161,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.034 (book £3.08 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-a206": {
   "gbpPerKg": 3.919,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.221 (book £3.64 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-en-ac-45300": {
   "gbpPerKg": 3.3484,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.044 (book £3.11 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-lm13": {
   "gbpPerKg": 3.3161,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.034 (book £3.08 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-aural5": {
   "gbpPerKg": 3.3053,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.030 (book £3.07 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-silafont36": {
   "gbpPerKg": 3.3376,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.040 (book £3.1 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-castasil37": {
   "gbpPerKg": 3.2622,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.017 (book £3.03 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-magsimal59": {
   "gbpPerKg": 3.3914,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.057 (book £3.15 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-al-hpdc-lowco2": {
   "gbpPerKg": 3.2299,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.007 (book £3 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-htf-gigacast": {
   "gbpPerKg": 3.5529,
   "basis": "Primary-based cast aluminium: AlSi7Mg (A356) = LME $3,248 (28 Sep) + Fastmarkets primary-foundry-alloy Si7 premium ddp Eastern Europe $950–1,050/t (29 May 2026) = zł16.35/kg × the book's premium over LM25, never below A356 (round 2; round 1 floored at P1020 zł14.5); ladder ×1.107 (book £3.3 ÷ base £2.98)",
   "source": "https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 (2026-05-29 / 2026-09-28) ; https://www.fastmarkets.com/insights/correction-to-european-aluminium-pfa-prices-published-in-error-on-may-22/ (2026-05-29)",
   "confidence": "Low"
  },
  "mat-al6082-forge": {
   "gbpPerKg": 3.2869,
   "basis": "Aluminium forging stock (floor): Delivered 6063 billet zł16.75/kg (LME + DDP North Germany billet premium) — forging stock is never below the billet it is cut from (the book's 6082 / 6061 stock sat below it); floor (raised to metal content)",
   "source": "https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 ; https://www.fastmarkets.com/insights/final-decision-on-open-consultation-on-methodology-review-for-aluminium-extrusion-billet-premiums-ddp-italy-ddp-north-germany-ddp-spain-in-relation-to-cbam/ (2026-08-28 / 2026-09-28)",
   "confidence": "Low"
  },
  "mat-aa5182": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa5052": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa5083": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa6082-sheet": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa5754-sheet": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa6063-sheet": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa3003-sheet": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa6016-t4": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-aa1050-sheet": {
   "gbpPerKg": 3.5714,
   "basis": "Aluminium sheet and plate (floor): Novelis Europe average selling price, FY to Mar 2026: $5,272 M ÷ 1,115 kt = $4,728/t = zł18.2/kg (all rolled products, can stock included, at lower metal prices than today — a floor, not a price); a Polish stockholder's single-sheet 5754 price zł29.18 is a retail ceiling; floor (raised to metal content)",
   "source": "https://www.sec.gov/Archives/edgar/data/0001304280/000130428026000019/nvl-20260331.htm (2025-04-01 to 2026-03-31) ; https://www.atreon.pl/blacha-aluminiowa-6x1250x2500--5754-z-folia/ (page read via search Oct 2026 (price undated))",
   "confidence": "Low"
  },
  "mat-c101-bar": {
   "gbpPerKg": 11.3717,
   "basis": "ETP copper bar / sheet (floor): LME copper $14,740 (25 Sep 2026) + Aurubis 2026 cathode premium $315 = zł57.95/kg delivered — the book's bar and sheet zł56.86 were below the copper they contain; floor (raised to metal content)",
   "source": "https://www.tacto.ai/en/commodities/copper-price ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026-09-25) ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026 contract year (announced 2025-10-07))",
   "confidence": "Medium"
  },
  "mat-c110-copper": {
   "gbpPerKg": 11.3717,
   "basis": "ETP copper bar / sheet (floor): LME copper $14,740 (25 Sep 2026) + Aurubis 2026 cathode premium $315 = zł57.95/kg delivered — the book's bar and sheet zł56.86 were below the copper they contain; floor (raised to metal content)",
   "source": "https://www.tacto.ai/en/commodities/copper-price ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026-09-25) ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026 contract year (announced 2025-10-07))",
   "confidence": "Medium"
  },
  "mat-brass-cz121": {
   "gbpPerKg": 9.4329,
   "basis": "Free-machining / forging brass rod (floor): Westmetall MS 58 metal basis €10.99/kg (9 Sep 2026) = zł48.07/kg — metal value before fabrication; floor (raised to metal content)",
   "source": "https://www.westmetall.com/de/markdaten.php (2026-09-09)",
   "confidence": "Low"
  },
  "mat-brass-cz122-forge": {
   "gbpPerKg": 9.4329,
   "basis": "Free-machining / forging brass rod (floor): Westmetall MS 58 metal basis €10.99/kg (9 Sep 2026) = zł48.07/kg — metal value before fabrication; floor (raised to metal content)",
   "source": "https://www.westmetall.com/de/markdaten.php (2026-09-09)",
   "confidence": "Low"
  },
  "mat-cz108-brass": {
   "gbpPerKg": 9.8018,
   "basis": "70/30 and 63/37 brass sheet (floor): Westmetall MS 63/37 metal basis (9 Sep 2026) = zł49.95/kg — metal value before rolling; floor (raised to metal content)",
   "source": "https://www.westmetall.com/de/markdaten.php (2026-09-09)",
   "confidence": "Low"
  },
  "mat-bronze-pb1": {
   "gbpPerKg": 14.4747,
   "basis": "Phosphor / tin bronze (floor): Metal content 0.89 × Cu zł57.95 + 0.105 × Sn zł211.31 (LME, 8 Sep); floor (raised to metal content)",
   "source": "https://www.tacto.ai/en/commodities/copper-price ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026-09-25) ; https://www.westmetall.com/de/markdaten.php (2026-09-08)",
   "confidence": "Low"
  },
  "mat-bronze-c905": {
   "gbpPerKg": 14.4747,
   "basis": "Phosphor / tin bronze (floor): Metal content 0.89 × Cu zł57.95 + 0.105 × Sn zł211.31 (LME, 8 Sep); floor (raised to metal content)",
   "source": "https://www.tacto.ai/en/commodities/copper-price ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026-09-25) ; https://www.westmetall.com/de/markdaten.php (2026-09-08)",
   "confidence": "Low"
  },
  "mat-cusn12-cast": {
   "gbpPerKg": 14.4747,
   "basis": "Phosphor / tin bronze (floor): Metal content 0.89 × Cu zł57.95 + 0.105 × Sn zł211.31 (LME, 8 Sep); floor (raised to metal content)",
   "source": "https://www.tacto.ai/en/commodities/copper-price ; https://www.kitco.com/news/off-the-wire/2025-10-07/aurubis-hikes-2026-european-copper-premium-record (2026-09-25) ; https://www.westmetall.com/de/markdaten.php (2026-09-08)",
   "confidence": "Low"
  },
  "mat-zamak3": {
   "gbpPerKg": 3.2598,
   "basis": "Zamak 3 (floor): Metal content 0.96 × SHG zinc zł16.7 (LME $4,110, 8 Sep, + Argus Rotterdam premium) + 0.04 × Al zł14.5; a Zamak premium was not found; floor (raised to metal content)",
   "source": "https://www.westmetall.com/de/markdaten.php ; https://www.argusmedia.com/metals-platform/price/assessment/zinc-special-high-grade-in-warehouse-rotterdam-premium-prices-PA00191000000 (2026-09-08) ; https://www.alcircle.com/news/lme-aluminium-cash-bid-slips-to-3-248-as-live-warrants-fall-4-5-on-september-28-121346 ; https://www.fastmarkets.com/insights/correction-to-rationale-of-aluminium-p1020a-premium-in-whs-dp-rotterdam-index/ (2026-09-15 / 2026-09-28)",
   "confidence": "Low"
  },
  "mat-zamak5": {
   "gbpPerKg": 3.3407,
   "basis": "Zamak 5 (floor): Metal content 0.95 × zinc zł16.7 + 0.04 × Al + 0.01 × Cu zł57.95; floor (raised to metal content)",
   "source": "https://www.westmetall.com/de/markdaten.php ; https://www.argusmedia.com/metals-platform/price/assessment/zinc-special-high-grade-in-warehouse-rotterdam-premium-prices-PA00191000000 (2026-09-08)",
   "confidence": "Low"
  },
  "mat-pp-homo": {
   "gbpPerKg": 1.0027,
   "basis": "PP family: PP homo zł5.11/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026); PP copolymer zł5.68) × the book's premium over PP homopolymer; the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pp": {
   "gbpPerKg": 1.1648,
   "basis": "PP family: PP homo zł5.11/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026); PP copolymer zł5.68) × the book's premium over PP homopolymer; ladder ×1.162 (book £1.15 ÷ base £0.99)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pp-impact": {
   "gbpPerKg": 1.0534,
   "basis": "PP family: PP homo zł5.11/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026); PP copolymer zł5.68) × the book's premium over PP homopolymer; ladder ×1.051 (book £1.04 ÷ base £0.99)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pp-bm": {
   "gbpPerKg": 1.1243,
   "basis": "PP family: PP homo zł5.11/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026); PP copolymer zł5.68) × the book's premium over PP homopolymer; ladder ×1.121 (book £1.11 ÷ base £0.99)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-ppr-pipe": {
   "gbpPerKg": 1.1851,
   "basis": "PP family: PP homo zł5.11/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026); PP copolymer zł5.68) × the book's premium over PP homopolymer; ladder ×1.182 (book £1.17 ÷ base £0.99)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pp-roto": {
   "gbpPerKg": 1.4991,
   "basis": "PP family: PP homo zł5.11/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026); PP copolymer zł5.68) × the book's premium over PP homopolymer; ladder ×1.495 (book £1.48 ÷ base £0.99)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-hdpe": {
   "gbpPerKg": 1.0734,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-hdpe-bm": {
   "gbpPerKg": 1.1654,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×1.086 (book £1.14 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-hdpe-fuel-coex": {
   "gbpPerKg": 1.5743,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×1.467 (book £1.54 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-hdpe-profile": {
   "gbpPerKg": 1.0734,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-hdpe-roto": {
   "gbpPerKg": 1.3187,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×1.229 (book £1.29 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-xlpe-roto": {
   "gbpPerKg": 1.7788,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×1.657 (book £1.74 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-fr-pe-roto": {
   "gbpPerKg": 2.7397,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×2.552 (book £2.68 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-foam-pe-roto": {
   "gbpPerKg": 2.0343,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×1.895 (book £1.99 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-cond-pe-roto": {
   "gbpPerKg": 2.5455,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×2.371 (book £2.49 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pex-pipe": {
   "gbpPerKg": 1.6459,
   "basis": "PE family: HDPE film zł5.47/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over HDPE; ladder ×1.533 (book £1.61 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-ldpe": {
   "gbpPerKg": 1.095,
   "basis": "LDPE family: LDPE zł5.58/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over LDPE; the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-ldpe-bm": {
   "gbpPerKg": 1.2055,
   "basis": "LDPE family: LDPE zł5.58/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over LDPE; ladder ×1.101 (book £1.2 ÷ base £1.09)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-ldpe-tube": {
   "gbpPerKg": 1.095,
   "basis": "LDPE family: LDPE zł5.58/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over LDPE; the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-lldpe": {
   "gbpPerKg": 1.0695,
   "basis": "LLDPE family: LLDPE C6 zł5.45/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over LLDPE; the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-lldpe-bm": {
   "gbpPerKg": 1.1917,
   "basis": "LLDPE family: LLDPE C6 zł5.45/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over LLDPE; ladder ×1.114 (book £1.17 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-lldpe-roto": {
   "gbpPerKg": 1.4973,
   "basis": "LLDPE family: LLDPE C6 zł5.45/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium over LLDPE; ladder ×1.400 (book £1.47 ÷ base £1.05)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-upvc": {
   "gbpPerKg": 0.8516,
   "basis": "PVC family: S-PVC resin zł4.34/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium of each compound over uPVC, never below the resin (the book's pipe compound zł3.97 sat below it); the anchor grade itself",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-fpvc": {
   "gbpPerKg": 1.2439,
   "basis": "PVC family: S-PVC resin zł4.34/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium of each compound over uPVC, never below the resin (the book's pipe compound zł3.97 sat below it); ladder ×1.461 (book £1.11 ÷ base £0.76)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pvc-bm": {
   "gbpPerKg": 0.9525,
   "basis": "PVC family: S-PVC resin zł4.34/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium of each compound over uPVC, never below the resin (the book's pipe compound zł3.97 sat below it); ladder ×1.118 (book £0.85 ÷ base £0.76)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-upvc-window-profile": {
   "gbpPerKg": 1.4456,
   "basis": "PVC family: S-PVC resin zł4.34/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium of each compound over uPVC, never below the resin (the book's pipe compound zł3.97 sat below it); ladder ×1.697 (book £1.29 ÷ base £0.76)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pvcp-profile": {
   "gbpPerKg": 1.7257,
   "basis": "PVC family: S-PVC resin zł4.34/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) × the book's premium of each compound over uPVC, never below the resin (the book's pipe compound zł3.97 sat below it); ladder ×2.026 (book £1.54 ÷ base £0.76)",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-hips": {
   "gbpPerKg": 1.4384,
   "basis": "HIPS: HIPS zł7.33/kg ex-VAT (myCEPPI Central & Eastern Europe market price (plasticportal.eu / plasticker, wk 36–37 2026)) — the book had HIPS at the GPPS price; direct",
   "source": "https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Medium"
  },
  "mat-pc": {
   "gbpPerKg": 2.2665,
   "basis": "PC family: PC zł11.55/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026) × the book's premium over PC; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polycarbonate-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-pc-glazing": {
   "gbpPerKg": 3.7775,
   "basis": "PC family: PC zł11.55/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026) × the book's premium over PC; ladder ×1.667 (book £4.2 ÷ base £2.52)",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polycarbonate-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-pc-bm": {
   "gbpPerKg": 3.5077,
   "basis": "PC family: PC zł11.55/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026) × the book's premium over PC; ladder ×1.548 (book £3.9 ÷ base £2.52)",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polycarbonate-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-pa6": {
   "gbpPerKg": 2.0173,
   "basis": "PA6 family: PA6 zł10.28/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Aug 2026) × the book's premium over PA6; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/pa6-price-index/ (2026-08)",
   "confidence": "Medium"
  },
  "mat-pa6-bm": {
   "gbpPerKg": 3.7223,
   "basis": "PA6 family: PA6 zł10.28/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Aug 2026) × the book's premium over PA6; ladder ×1.845 (book £3.1 ÷ base £1.68)",
   "source": "https://businessanalytiq.com/procurementanalytics/index/pa6-price-index/ (2026-08)",
   "confidence": "Medium"
  },
  "mat-pa6-ext-tube": {
   "gbpPerKg": 2.0173,
   "basis": "PA6 family: PA6 zł10.28/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Aug 2026) × the book's premium over PA6; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/pa6-price-index/ (2026-08)",
   "confidence": "Medium"
  },
  "mat-pa66": {
   "gbpPerKg": 3.1947,
   "basis": "PA66: PA66 zł16.28/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Aug 2026); direct",
   "source": "https://businessanalytiq.com/procurementanalytics/index/pa66-price-index/ (2026-08)",
   "confidence": "Medium"
  },
  "mat-pbt": {
   "gbpPerKg": 2.7943,
   "basis": "PBT: PBT zł14.24/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026); direct",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polybutylene-terephthalate-pbt-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-pet-bg": {
   "gbpPerKg": 0.9753,
   "basis": "PET family: PET bottle grade zł4.97/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026) × the book's premium over PET bottle grade; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/pet-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-pet-preform": {
   "gbpPerKg": 1.0075,
   "basis": "PET family: PET bottle grade zł4.97/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026) × the book's premium over PET bottle grade; ladder ×1.033 (book £1.25 ÷ base £1.21)",
   "source": "https://businessanalytiq.com/procurementanalytics/index/pet-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-pmma": {
   "gbpPerKg": 2.7865,
   "basis": "PMMA family: PMMA zł14.20/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Sep 2026; Trinseo +€250/t from 1 Oct not added) × the book's premium over PMMA; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polymethylmethacrylate-pmma-price-index/ (2026-09)",
   "confidence": "Medium"
  },
  "mat-peek": {
   "gbpPerKg": 67.9945,
   "basis": "PEEK family: PEEK ≈ zł346.5/kg — Victrex FY2026 Q3 average selling price £68/kg (its whole mix incl. medical, so an upper bound for industrial resin); the anchor grade itself",
   "source": "https://www.investegate.co.uk/announcement/rns/victrex-plc--vct/trading-statement/9654844 (2026-06-30 (Q3 FY2026))",
   "confidence": "Low"
  },
  "mat-peek-ext": {
   "gbpPerKg": 67.9945,
   "basis": "PEEK family: PEEK ≈ zł346.5/kg — Victrex FY2026 Q3 average selling price £68/kg (its whole mix incl. medical, so an upper bound for industrial resin); the anchor grade itself",
   "source": "https://www.investegate.co.uk/announcement/rns/victrex-plc--vct/trading-statement/9654844 (2026-06-30 (Q3 FY2026))",
   "confidence": "Low"
  },
  "mat-pom": {
   "gbpPerKg": 2.2959,
   "basis": "POM: POM zł11.70/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Jul 2026; a Polish offer list zł11.65 agrees) × the book's premium over POM; the anchor grade itself",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polyoxymethylene-pom-price-index/ (2026-07)",
   "confidence": "Medium"
  },
  "mat-pom-rod": {
   "gbpPerKg": 2.5983,
   "basis": "POM: POM zł11.70/kg ex-VAT (businessanalytiq Europe price index (method not published — Medium at best), Jul 2026; a Polish offer list zł11.65 agrees) × the book's premium over POM; ladder ×1.132 (book £2.32 ÷ base £2.05)",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polyoxymethylene-pom-price-index/ (2026-07)",
   "confidence": "Medium"
  },
  "mat-pc-abs": {
   "gbpPerKg": 2.0593,
   "basis": "PC/ABS (floor): Resin content 0.7 × PC zł11.55 + 0.3 × ABS zł8.03 = zł10.49/kg — the book's PC/ABS zł9.49 sat below its own resins; floor (raised to metal content)",
   "source": "https://businessanalytiq.com/procurementanalytics/index/polycarbonate-price-index/ (2026-09) ; https://www.plasticportal.eu/price-reports (2026-W37 (page updated 2026-10-01))",
   "confidence": "Low"
  },
  "mat-cf-dry-3k": {
   "gbpPerKg": 25.6809,
   "basis": "Carbon fabric (floor): Carbon fibre (12K, generic) $34/kg (IMARC Germany, Mar 2026) = zł130.87/kg — a woven fabric is never below the fibre it is woven from; floor (raised to metal content)",
   "source": "https://www.imarcgroup.com/carbon-fibre-pricing-report (2026-03)",
   "confidence": "Low"
  },
  "mat-nr": {
   "gbpPerKg": 1.9564,
   "basis": "Natural rubber (raw): TSR20 benchmark zł9.97/kg (Trading Economics, 9 Oct 2026) — FOB Asia, freight to Poland NOT added; for the book's raw NR SMR20 line; compounds held; direct",
   "source": "https://tradingeconomics.com/commodity/rubber (2026-10-09)",
   "confidence": "Low"
  }
 },
 "machines": {
  "hoursPerYear": 6024,
  "shiftDepreciationFactor": 1,
  "lifeYears": 7.14,
  "financeRate": 0.0822,
  "ukFinanceRate": 0.04,
  "maintenancePctOfCapex": 0.035,
  "rentGbpPerM2Yr": 47.2135,
  "ukRentGbpPerM2Yr": 110,
  "ukElectricityGbpPerKwh": 0.182,
  "labourRatio": 0.4658,
  "capitalHeldFactor": 0.72,
  "basis": "3 × 8 h, Monday–Friday, 251 working days in 2026 = 6,024 h (the labour model's pattern); Polish straight-line tax depreciation — no shift uplift on held capital; SME machinery / investment loan WIBOR 3M 3.82% + 3.9–4.9 pp = 7.72–8.72%, midpoint 8.22% (cooperative bank tariff, Mar 2026); NBP reference rate 3.75% (7 Oct 2026) — a large Tier-1 borrows below this; the book's line build-ups use 4% on half the capex; rent zł20.05/m²/month (warehouse / light-industrial headline rent midpoints: Upper Silesia zł20.12, Wrocław zł18.92, Poznań zł21.10 per m²/month (€3.15–6.00 at zł4.374/€; ceo.com.pl, ~Apr 2026) — mean; CBRE Q2 2026 national €4.7 = zł20.56 agrees; Rzeszów listings only); maintenance the library's own line build-up rule (3.5% of capex); no Polish norm found",
  "heldBasis": "capex not sourced for Poland: the capital is the UK book's × 0.72; the Poland operating model (3 × 8 h, straight-line tax life, loan finance, rent, tariff, support at Polish wages) is applied",
  "groups": [
   {
    "id": "cnc-vmc-eu",
    "match": "^(mach-vmc3|mach-haas-vf2|mach-drill)$",
    "refId": "mach-vmc3",
    "refCapexGbp": 55786.5,
    "basis": "Haas VF-2SSYT-EU list €64,995 on Haas's Polish site = zł284,288 (machine only; delivery, installation and tooling not included); US list $70,995 = zł273,260 agrees — an imported machine costs Poland what it costs the EU",
    "source": "https://www.haascnc.com/pl/machines/Special-Series/eu-series/vf-2ssyt-eu.html",
    "confidence": "Medium"
   },
   {
    "id": "cnc-5axis-eu",
    "match": "^(mach-vmc5|mach-dmg-dmu50|mach-haas-umc500)$",
    "refId": "mach-vmc5",
    "refCapexGbp": 90632.06,
    "basis": "Haas UMC-500 \"from $119,995\" (US list, older article) = zł461,861 — no EU price found",
    "source": "https://www.haascnc.com/machines/vertical-mills/universal-machine/models/umc-500.html",
    "confidence": "Low"
   },
   {
    "id": "press-brake-eu",
    "match": "^brake-",
    "refId": "brake-trumpf-trubend3100",
    "refCapexGbp": 116731.55,
    "basis": "TRUMPF TruBend 3100 (100 t × 3 m) NEW, offered at €136,000 FCA ex-VAT (Jul 2026, advertiser at TRUMPF Ditzingen) = zł594,864; a 2021 purchase at €115k agrees — the UK book's build-up (a \"Target £/hr\" shop rate) implied ~4× this",
    "source": "https://www.machineseeker.com/trumpf-trubend+3100/i-22233802",
    "confidence": "Low"
   }
  ]
 }
};
