/**
 * China rate book (Oct 2026, docs/rates/china-rate-book-2026-10.md): China's own rates — NBS / recruiter labour loaded
 * for two 12-hour shifts, Mysteel / SMM / SunSirs material anchors, the 2 × 12 h operating model and Chinese capex for
 * CNC machining — in place of "UK × a factor". Generated by scripts/country-book.ts from scripts/rate-refresh/2026-10-china.json.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { DEFAULT_RATE_LIBRARY, recomputeMachineRates } from '../src/engine/rate-library.js';
import { REGIONAL_DATA, buildRegionalLibrary } from '../src/engine/regional-rates.js';
import { CHINA_BOOK } from '../src/engine/country-books/cn.js';
import { COUNTRY_BOOKS } from '../src/engine/country-books.js';
import { BILLET_PREMIUM_USD_PER_T } from '../src/engine/al-extrusion-data.js';

const UK = recomputeMachineRates(DEFAULT_RATE_LIBRARY);
const CN = buildRegionalLibrary(UK, 'CN');
const FX = REGIONAL_DATA.CN.fxToGBP;
const cny = (gbp: number) => Math.round(gbp * FX * 100) / 100;
const mat = (id: string) => CN.materials.find(m => m.id === id)!;
const mach = (id: string) => CN.machines.find(m => m.id === id)!;
const lab = (id: string) => CN.labour.find(l => l.id === id)!;

describe('materials: Chinese market anchors, not UK × a factor', () => {
  it('CR sheet at the Shanghai spot (Mysteel, Oct 2026), ex-VAT; the note says ¥', () => {
    expect(COUNTRY_BOOKS.CN).toBe(CHINA_BOOK);
    expect(cny(mat('mat-dc01').pricePerKg)).toBeCloseTo(3.24, 1);
    expect(mat('mat-dc01').sourceNote).toMatch(/China book .*¥3\.24\/kg/);
  });
  it('bars are the GB grades\' own spot: 45#, 40Cr, 42CrMo, 20CrMnTi', () => {
    expect(cny(mat('mat-steel-c45').pricePerKg)).toBeCloseTo(3.26, 1);
    expect(cny(mat('mat-steel-41cr4').pricePerKg)).toBeCloseTo(3.45, 1);
    expect(mat('mat-steel4140').pricePerKg).toBeCloseTo(mat('mat-steel-42crmo4').pricePerKg, 4);
  });
  it('a casting grade is the metal CHARGE; alloy premiums ride on it in £/kg', () => {
    expect(cny(mat('mat-gjs500').pricePerKg)).toBeCloseTo(2.69, 1);
    expect(mat('mat-gjs500').sourceNote).toMatch(/charge/i);
    expect(mat('mat-adi').pricePerKg - mat('mat-gjs500').pricePerKg).toBeCloseTo(1.58 - 0.86, 2);
  });
  it('aluminium: ADC12 at SMM, A356 at SMM, primary-based alloys never below A356', () => {
    expect(cny(mat('mat-adc12').pricePerKg)).toBeCloseTo(21.68, 1);
    expect(cny(mat('mat-lm25').pricePerKg)).toBeCloseTo(21.42, 1);
    for (const id of ['mat-a357', 'mat-silafont36', 'mat-alsi10mg']) expect(mat(id).pricePerKg, id).toBeGreaterThanOrEqual(mat('mat-lm25').pricePerKg - 1e-9);
  });
  it('no grade below the metal it contains (copper bar ≥ Changjiang cathode)', () => {
    expect(cny(mat('mat-c101-bar').pricePerKg)).toBeGreaterThanOrEqual(98.7);
  });
  it('PP at the East China spot; impact PP not below homopolymer', () => {
    expect(cny(mat('mat-pp-homo').pricePerKg)).toBeCloseTo(8.79, 1);
    expect(mat('mat-pp-impact').pricePerKg).toBeGreaterThanOrEqual(mat('mat-pp-homo').pricePerKg);
  });
  it('every book price says what it is, where it came from and how sure it is', () => {
    for (const [id, p] of Object.entries(CHINA_BOOK.materials)) {
      expect(p.basis.length, id).toBeGreaterThan(20);
      expect(p.source, id).toMatch(/https?:\/\//);
      expect(['High', 'Medium', 'Low']).toContain(p.confidence);
    }
  });
  it('the extrusion billet is A00 + the processing fee', () => {
    expect(BILLET_PREMIUM_USD_PER_T.CN.sourced).toBe(true);
    expect(cny(mat('mat-al-billet-6063').pricePerKg)).toBeGreaterThan(21.4);
  });
});

describe('labour and energy', () => {
  it('a skilled machinist is ~¥33/h fully loaded on two 12-h shifts (was ¥71.75); lab-cn agrees with the table', () => {
    expect(cny(lab('lab-uk-skilled').fullyLoadedRatePerHr)).toBeCloseTo(33.12, 0);
    expect(DEFAULT_RATE_LIBRARY.labour.find(l => l.id === 'lab-cn-skilled')!.fullyLoadedRatePerHr).toBeCloseTo(REGIONAL_DATA.CN.labour.skilled, 6);
    expect(lab('lab-uk-forge').sourceNote).toMatch(/China book/);
  });
  it('gas at the cluster tariff; electricity held (the evidence agrees)', () => {
    expect(cny(REGIONAL_DATA.CN.energy.gasPerKwh)).toBeCloseTo(0.356, 2);
    expect(REGIONAL_DATA.CN.energy.electricityPerKwh).toBe(0.071);
    const e = DEFAULT_RATE_LIBRARY.energy.find(x => x.id === 'energy-cn')!;
    expect(e.gasPerKwh).toBe(REGIONAL_DATA.CN.energy.gasPerKwh);
  });
});

describe('machines: the 2 × 12 h operating model; Chinese capex for CNC', () => {
  it('a 3-axis VMC is a ~¥288k Haitian Precision machine over 6,336 h, machine only', () => {
    const v = mach('mach-vmc3');
    expect(v.buildup.annualAvailableHours).toBe(6336);
    expect(v.sourceNote).toMatch(/Haitian/);
    expect(cny(v.computedRatePerHr)).toBeGreaterThan(15);
    expect(cny(v.computedRatePerHr)).toBeLessThan(40);
  });
  it('a machine without capex evidence says its capital is HELD', () => {
    expect(mach('press-400t').sourceNote).toMatch(/HELD/);
    expect(mach('press-400t').confidence).toBe('Low');
  });
});

describe('the register', () => {
  const reg = readFileSync('scripts/rate-refresh/china-2026-10/register.csv', 'utf8').trim().split('\n').slice(1);
  it('every library material and machine is in it once, with a decision', () => {
    const ids = reg.map(l => l.split('","')[1]);
    for (const m of DEFAULT_RATE_LIBRARY.materials) expect(ids.filter(i => i === m.id).length, m.id).toBe(1);
    for (const m of DEFAULT_RATE_LIBRARY.machines) expect(ids.filter(i => i === m.id).length, m.id).toBe(1);
  });
  it('the UK book is untouched', () => {
    const ukBook = buildRegionalLibrary(UK, 'UK');
    expect(ukBook.materials.find(m => m.id === 'mat-dc01')!.pricePerKg).toBe(DEFAULT_RATE_LIBRARY.materials.find(m => m.id === 'mat-dc01')!.pricePerKg);
  });
});
