/**
 * Gear cost inputs, derived deterministically from measured B-rep metrology.
 *
 * The fixture is the known-truth involute gear generated by
 * `scripts/gen-test-gear.py` (m=3, z=38, b=30, bore=40 → OD=120 exactly) and
 * measured by `cad-geometry-engine.py`: teeth counted from tip-circle patches,
 * module derived as OD/(z+2). These tests pin:
 *
 *   - what geometry decides (z, module, face width, weight, blank) vs what it
 *     refuses to decide (helix, ISO class, material class — drawing questions);
 *   - the blank arithmetic, reproduced by hand from library rates;
 *   - the full chain into `computeGearDrivers` → `computeUniversalStack`.
 */
import { describe, it, expect } from 'vitest';
import { runCostInputRules } from '../src/engine/cost-input-rules/engine.js';
import {
  GEAR_RULES, GEAR_HELIX_DECISION_ID, GEAR_QUALITY_DECISION_ID,
  GEAR_MATERIAL_DECISION_ID, GEAR_TEETH_DECISION_ID, GEAR_MODULE_DECISION_ID,
  GEAR_FACE_DECISION_ID,
} from '../src/engine/cost-input-rules/commodities/gear.js';
import { DEFAULT_RATE_LIBRARY } from '../src/engine/rate-library.js';
import { computeGearDrivers } from '../src/engine/modules/gear.js';
import { computeUniversalStack } from '../src/engine/core.js';
import type { RuleContext } from '../src/engine/cost-input-rules/types.js';
import type { OCCTGeometry } from '../src/engine/ai-analysis.js';

/** The measured output for cad-audit/parts/test-gear-m3-z38.step, verbatim. */
const TEST_GEAR = {
  status: 'success',
  partName: 'test gear m3 z38',
  boundingBox: { xMm: 120.0, yMm: 119.76, zMm: 30.0 },
  volume: { mm3: 265_959, cm3: 265.959 },
  surfaceArea: { mm2: 78_000, cm2: 780 },
  faces: { total: 160, byType: { CYLINDER: 78, PLANE: 2 } },
  features: { freeFormFaceCount: 76, planarFaceCount: 2, estimatedHoleCount: 1 },
  gear: {
    likelyGear: true,
    teeth: 38,
    tipDiameterMm: 120.0,
    faceWidthMm: 30.0,
    boreDiameterMm: 40.0,
    derivedNormalModuleMm: 3.0,
    moduleBasis: 'OD 120.0 mm / (z 38 + 2) — standard addendum, external, spur-equivalent',
    teethBasis: 'counted 38 tip-circle patch(es) at r≈60.0 mm clustered to 38 angular positions',
    helixAngleDeg: null,
    internal: false,
  },
} as unknown as OCCTGeometry;

/** The same solid with the gear metrology withheld — a shape the kernel could
 *  not read as a gear, which the engineer still wants costed as one. */
const NOT_RECOGNISED = { ...TEST_GEAR, gear: null } as unknown as OCCTGeometry;

const ANSWERED = {
  [GEAR_HELIX_DECISION_ID]: '0',
  [GEAR_QUALITY_DECISION_ID]: '7',
  [GEAR_MATERIAL_DECISION_ID]: 'case_hardening_steel',
};

const ctx = (
  answers: Record<string, unknown> = {},
  geo: OCCTGeometry = TEST_GEAR,
  over: Partial<RuleContext> = {},
): RuleContext => ({
  geo, geometryQuality: 'occt', commodity: 'gear', commoditySource: 'engineer',
  annualVolume: 200_000, filename: 'test-gear-m3-z38.step', answers, ...over,
});

describe('gear rules — what geometry decides vs what it asks', () => {
  it('unanswered: blocks on helix, ISO class and material class — never guesses them', () => {
    const r = runCostInputRules(GEAR_RULES, ctx());
    expect(r.status).toBe('needs_decision');
    const ids = r.decisions.map(d => d.id);
    expect(ids).toContain(GEAR_HELIX_DECISION_ID);
    expect(ids).toContain(GEAR_QUALITY_DECISION_ID);
    expect(ids).toContain(GEAR_MATERIAL_DECISION_ID);
    for (const d of r.decisions) expect(d.severity).toBe('blocking');
    // No option is preselected as an answer: leanings are displayed, not taken.
    expect((r.suggestions as { gear?: { qualityClass?: number } }).gear?.qualityClass).toBeUndefined();
  });

  it('teeth and face width come from geometry even while blocked', () => {
    const r = runCostInputRules(GEAR_RULES, ctx());
    const g = (r.suggestions as { gear: Record<string, unknown> }).gear;
    expect(g.teeth).toBe(38);
    expect(g.faceWidthMm).toBe(30.0);
    expect(r.byRule['gear.teeth'].source).toBe('geometry');
    expect(r.byRule['gear.faceWidthMm'].source).toBe('geometry');
  });

  it('answered spur: module = OD/(z+2) = 3.00 mm, complete, with provenance', () => {
    const r = runCostInputRules(GEAR_RULES, ctx(ANSWERED));
    expect(r.status).toBe('complete');
    const g = (r.suggestions as { gear: Record<string, unknown> }).gear;
    expect(g.normalModuleMm).toBe(3);
    expect(g.teeth).toBe(38);
    expect(g.helixAngleDeg).toBe(0);
    expect(g.qualityClass).toBe(7);
    expect(g.materialClass).toBe('case_hardening_steel');
    expect(g.caseHardened).toBe(true);
    expect(g.materialId).toBe('mat-steel-20mncr5');
    expect(r.byRule['gear.normalModuleMm'].source).toBe('geometry');
    expect(r.byRule['gear.normalModuleMm'].basis).toContain('120.0');
  });

  it('answered helical 20°: normal module re-derived with cos β', () => {
    const r = runCostInputRules(GEAR_RULES, ctx({ ...ANSWERED, [GEAR_HELIX_DECISION_ID]: '20' }));
    const g = (r.suggestions as { gear: Record<string, unknown> }).gear;
    // mn = 120 / (38/cos20° + 2) = 120 / 42.439 = 2.8276 → 2.83
    expect(g.normalModuleMm).toBe(2.83);
    expect(g.helixAngleDeg).toBe(20);
  });

  it('net weight = measured volume × the answered grade density', () => {
    const r = runCostInputRules(GEAR_RULES, ctx(ANSWERED));
    const g = (r.suggestions as { gear: Record<string, unknown> }).gear;
    // 265.959 cm³ × 7850 kg/m³ = 2.088 kg
    expect(g.netWeightKg).toBeCloseTo(2.088, 3);
    expect(r.byRule['gear.netWeightKg'].source).toBe('geometry');
  });

  it('blank cost reproduces by hand from library rates', () => {
    const r = runCostInputRules(GEAR_RULES, ctx(ANSWERED));
    const g = (r.suggestions as { gear: Record<string, unknown> }).gear;

    // Independent hand-calc, all literals: stock Ø124 × 36 mm of 20MnCr5.
    const mat = DEFAULT_RATE_LIBRARY.materials.find(m => m.id === 'mat-steel-20mncr5')!;
    const stockCm3 = Math.PI / 4 * 124 * 124 * 36 / 1000;             // 434.8 cm³
    const stockKg = stockCm3 * 7850 / 1e6;                            // 3.413 kg
    const netKg = 265.959 * 7850 / 1e6;                               // 2.088 kg
    const matCost = stockKg * mat.pricePerKg - (stockKg - netKg) * mat.scrapRecoveryPricePerKg;
    const blankCm3 = Math.PI / 4 * (120 * 120 - 40 * 40) * 30 / 1000; // 301.6 cm³
    const prepMin = 1.5 + (stockCm3 - blankCm3) / 40;
    const lathe = DEFAULT_RATE_LIBRARY.machines.find(m => m.id === 'mach-lathe-cnc')!.computedRatePerHr;
    const labour = DEFAULT_RATE_LIBRARY.labour.find(l => l.id === 'lab-uk-skilled')!.fullyLoadedRatePerHr;
    const prepCost = prepMin / 60 * (lathe / 0.85 + labour);
    const expected = Math.round((matCost + prepCost) * 100) / 100;

    expect(g.blankCostPerPart).toBeCloseTo(expected, 2);
    expect(r.byRule['gear.blankCostPerPart'].basis).toContain('20MnCr5');
    expect(r.byRule['gear.blankCostPerPart'].basis).toContain('Replace with the forged-blank quote');
  });

  it('no metrology: teeth/module/face become drawing entries, never bbox guesses', () => {
    const r = runCostInputRules(GEAR_RULES, ctx({}, NOT_RECOGNISED));
    expect(r.status).toBe('needs_decision');
    const ids = r.decisions.map(d => d.id);
    expect(ids).toContain(GEAR_TEETH_DECISION_ID);
    expect(ids).toContain(GEAR_FACE_DECISION_ID);
    // With teeth typed and helix answered, module entry is the remaining ask.
    const r2 = runCostInputRules(GEAR_RULES, ctx({
      ...ANSWERED, [GEAR_TEETH_DECISION_ID]: '38',
    }, NOT_RECOGNISED));
    expect(r2.decisions.map(d => d.id)).toContain(GEAR_MODULE_DECISION_ID);
    // Fully typed off the drawing: complete, and OD is back-derived for the blank.
    const r3 = runCostInputRules(GEAR_RULES, ctx({
      ...ANSWERED,
      [GEAR_TEETH_DECISION_ID]: '38',
      [GEAR_MODULE_DECISION_ID]: '3',
      [GEAR_FACE_DECISION_ID]: '30',
    }, NOT_RECOGNISED));
    expect(r3.status).toBe('complete');
    const g3 = (r3.suggestions as { gear: Record<string, unknown> }).gear;
    expect(g3.normalModuleMm).toBe(3);
    expect(g3.blankCostPerPart as number).toBeGreaterThan(0);
  });

  it('assumeLeanings (AI path): helix/class assumed visibly — material class NEVER assumed', () => {
    const r = runCostInputRules(GEAR_RULES, ctx({}, TEST_GEAR, { assumeLeanings: true }));
    // Helix and ISO class follow the tolerance-class precedent: stated
    // assumptions with a printed note. The material class is the documented
    // dominant failure mode — it stays a blocking question even here.
    expect(r.status).toBe('needs_decision');
    expect(r.decisions.map(d => d.id)).toEqual([GEAR_MATERIAL_DECISION_ID]);
    const g = (r.suggestions as { gear: Record<string, unknown> }).gear;
    expect(g.helixAngleDeg).toBe(0);
    expect(g.qualityClass).toBe(7);
    expect(g.materialClass).toBeUndefined();
    expect(g.blankCostPerPart).toBeUndefined();          // depends on the class
    expect(r.byRule['gear.qualityClass'].basis).toContain('assumed — confirm before quoting');
    expect(r.byRule['gear.qualityClass'].confidence).toBeLessThan(1);
  });

  it('the decided inputs drive computeGearDrivers → computeUniversalStack to a real cost', () => {
    const r = runCostInputRules(GEAR_RULES, ctx(ANSWERED));
    const g = (r.suggestions as { gear: Record<string, number | boolean | string> }).gear;
    const drivers = computeGearDrivers({
      normalModuleMm: g.normalModuleMm as number,
      teeth: g.teeth as number,
      helixAngleDeg: g.helixAngleDeg as number,
      faceWidthMm: g.faceWidthMm as number,
      internal: g.internal as boolean,
      qualityClass: g.qualityClass as number,
      materialClass: g.materialClass as 'case_hardening_steel',
      caseHardened: g.caseHardened as boolean,
      blankCostPerPart: g.blankCostPerPart as number,
      netWeightKg: 2.088,
      materialId: g.materialId as string,
      annualVolume: 200_000,
      amortizationVolume: 1_000_000,
      batchSize: g.batchSize as number,
    });
    const stack = computeUniversalStack({
      partName: 'test gear', rawMaterial: drivers.rawMaterial,
      operations: drivers.operations, tooling: drivers.tooling,
      packagingPerPart: 0.10, logisticsPerPart: 0.12,
      overheadPct: 0.12, marginPct: 0.08, annualVolume: 200_000,
    }, DEFAULT_RATE_LIBRARY);
    expect(stack.total).toBeGreaterThan(g.blankCostPerPart as number);
    expect(stack.total).toBeLessThan(60);
    for (const b of Object.values(stack.breakdown)) expect(Number.isFinite(b)).toBe(true);
  });
});
