/**
 * India rate book (Oct 2026, docs/rates/india-rate-book-2026-10.md): India's own rates — statutory-loaded labour,
 * Indian mill / producer / market material anchors, the 3-shift operating model and Indian capex for CNC machining —
 * in place of "UK × a factor". Generated by scripts/country-book.ts from scripts/rate-refresh/2026-10-india.json.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { DEFAULT_RATE_LIBRARY, recomputeMachineRates } from '../src/engine/rate-library.js';
import { REGIONAL_DATA, buildRegionalLibrary, EXTRUSION_COUNTRY_PRICES, THERMOFORMING_COUNTRY_PRICES } from '../src/engine/regional-rates.js';
import { INDIA_BOOK } from '../src/engine/country-books/in.js';

const UK = recomputeMachineRates(DEFAULT_RATE_LIBRARY);
const IN = buildRegionalLibrary(UK, 'IN');
const FX = REGIONAL_DATA.IN.fxToGBP;
const inr = (gbp: number) => Math.round(gbp * FX * 100) / 100;
const mat = (id: string) => IN.materials.find(m => m.id === id)!;
const mach = (id: string) => IN.machines.find(m => m.id === id)!;
const lab = (id: string) => IN.labour.find(l => l.id === id)!;

describe('materials: India anchors, not UK × a factor', () => {
  it('CR sheet at the JPC Sep 2026 CR coil price; DC01 no longer above DC04', () => {
    expect(inr(mat('mat-dc01').pricePerKg)).toBeCloseTo(72.01, 1);
    expect(mat('mat-dc01').pricePerKg).toBeLessThanOrEqual(mat('mat-dc04').pricePerKg + 1e-9);
  });
  it('a casting grade is the metal CHARGE (the engine adds melt, labour, line, overhead and margin)', () => {
    expect(inr(mat('mat-gjs500').pricePerKg)).toBeCloseTo(46.01, 1);
    expect(mat('mat-gjs500').sourceNote).toMatch(/charge/i);
  });
  it('ADC12 at the SMM Oct 2026 Mumbai / Delhi mean; secondary ADC12 is the same market', () => {
    expect(inr(mat('mat-adc12').pricePerKg)).toBeCloseTo(304.88, 1);
    expect(mat('mat-adc12-secondary').pricePerKg).toBeCloseTo(mat('mat-adc12').pricePerKg, 6);
  });
  it('PP and HDPE at the Sep 2026 Indian market', () => {
    expect(inr(mat('mat-pp-homo').pricePerKg)).toBeCloseTo(129.35, 1);
    expect(inr(mat('mat-hdpe').pricePerKg)).toBeCloseTo(136, 1);
  });
  it('the same grade is one price (4140 bar = 42CrMo4 billet)', () => {
    expect(mat('mat-steel4140').pricePerKg).toBeCloseTo(mat('mat-steel-42crmo4').pricePerKg, 4);
  });
  it('copper bar is never below the copper it contains', () => {
    expect(inr(mat('mat-c101-bar').pricePerKg)).toBeGreaterThanOrEqual(1385 - 0.01);
  });
  it('every book price says what it is, where it came from and how sure it is', () => {
    for (const [id, p] of Object.entries(INDIA_BOOK.materials)) {
      expect(p.basis.length, id).toBeGreaterThan(20);
      expect(p.source, id).toMatch(/https?:\/\//);
      expect(['High', 'Medium', 'Low']).toContain(p.confidence);
    }
  });
  it('an India-specific price already in the country tables is kept (it outranks a ladder)', () => {
    for (const id of Object.keys(INDIA_BOOK.materials)) {
      expect(EXTRUSION_COUNTRY_PRICES[id]?.IN ?? THERMOFORMING_COUNTRY_PRICES[id]?.IN, id).toBeUndefined();
    }
  });
});

describe('labour: statutory-loaded Indian wages', () => {
  it('a skilled machinist is ~₹162/h fully loaded (was ₹654), and the lab-in entry agrees with the table', () => {
    expect(inr(lab('lab-uk-skilled').fullyLoadedRatePerHr)).toBeCloseTo(161.54, 0);
    const own = DEFAULT_RATE_LIBRARY.labour.find(l => l.id === 'lab-in-skilled')!;
    expect(own.fullyLoadedRatePerHr).toBeCloseTo(REGIONAL_DATA.IN.labour.skilled, 6);
    expect(inr(lab('lab-uk-engineer').fullyLoadedRatePerHr)).toBeLessThan(300);
  });
  it('process grades come from the book (forge, furnace, plastics)', () => {
    expect(lab('lab-uk-forge').sourceNote).toMatch(/India book/);
    expect(inr(lab('lab-uk-blow').fullyLoadedRatePerHr)).toBeCloseTo(111, 0);
  });
});

describe('machines: the 3-shift operating model; Indian capex for CNC machining', () => {
  it('a 3-axis VMC (machine only) sits inside the Indian job-shop band that INCLUDES the operator (₹250–1,500/h)', () => {
    const v = inr(mach('mach-vmc3').computedRatePerHr);
    expect(v).toBeGreaterThan(250);
    expect(v).toBeLessThan(1500);
    expect(mach('mach-vmc3').buildup.annualAvailableHours).toBe(7200);
    expect(mach('mach-vmc3').sourceNote).toMatch(/Jyoti/);
  });
  it('no India machine rate went up, and a machine without capex evidence says its capital is HELD', () => {
    // the frozen India book before this change (UK × the regional factors)
    const snap = JSON.parse(readFileSync('scripts/rate-refresh/india-2026-10/current-india-book.json', 'utf8')) as { machines: Array<{ id: string; inrPerHr: number }> };
    for (const m of IN.machines) {
      const was = snap.machines.find(x => x.id === m.id)!;
      expect(inr(m.computedRatePerHr), m.id).toBeLessThanOrEqual(was.inrPerHr + 0.01);
    }
    expect(mach('press-400t').sourceNote).toMatch(/HELD/);
    expect(mach('press-400t').confidence).toBe('Low');
  });
});

describe('the register and the UK', () => {
  const reg = readFileSync('scripts/rate-refresh/india-2026-10/register.csv', 'utf8').trim().split('\n').slice(1);
  it('every library material and machine is in the register once, with a decision', () => {
    const ids = reg.map(l => l.split('","')[1]);
    for (const m of DEFAULT_RATE_LIBRARY.materials) expect(ids.filter(i => i === m.id).length, m.id).toBe(1);
    for (const m of DEFAULT_RATE_LIBRARY.machines) expect(ids.filter(i => i === m.id).length, m.id).toBe(1);
  });
  it('the UK book is untouched (a country book applies to its own country only)', () => {
    const ukBook = buildRegionalLibrary(UK, 'UK');
    expect(ukBook.materials.find(m => m.id === 'mat-gjs500')!.pricePerKg).toBe(DEFAULT_RATE_LIBRARY.materials.find(m => m.id === 'mat-gjs500')!.pricePerKg);
    expect(ukBook.machines.find(m => m.id === 'mach-vmc3')!.computedRatePerHr).toBeCloseTo(UK.machines.find(m => m.id === 'mach-vmc3')!.computedRatePerHr, 6);
  });
});
