/**
 * Poland rate book (Oct 2026, docs/rates/poland-rate-book-2026-10.md): Poland's own rates — Sedlak & Sedlak / GUS labour
 * loaded with ZUS for three 8-hour shifts, European market anchors (Eurometal / Fastmarkets / myCEPPI / LME) at the book's
 * FX, the 3 × 8 h operating model and Haas EU capex for CNC machining — in place of "UK × a factor". Generated by
 * scripts/country-book.ts from scripts/rate-refresh/2026-10-poland.json.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { DEFAULT_RATE_LIBRARY, recomputeMachineRates } from '../src/engine/rate-library.js';
import { REGIONAL_DATA, buildRegionalLibrary } from '../src/engine/regional-rates.js';
import { POLAND_BOOK } from '../src/engine/country-books/pl.js';
import { COUNTRY_BOOKS } from '../src/engine/country-books.js';
import { BILLET_PREMIUM_USD_PER_T } from '../src/engine/al-extrusion-data.js';

const UK = recomputeMachineRates(DEFAULT_RATE_LIBRARY);
const PL = buildRegionalLibrary(UK, 'PL');
const FX = REGIONAL_DATA.PL.fxToGBP;
const pln = (gbp: number) => Math.round(gbp * FX * 100) / 100;
const mat = (id: string) => PL.materials.find(m => m.id === id)!;
const mach = (id: string) => PL.machines.find(m => m.id === id)!;
const lab = (id: string) => PL.labour.find(l => l.id === id)!;

describe('materials: European market anchors at the book FX, not UK × a factor', () => {
  it('CR sheet at the NW Europe price; the note says zł', () => {
    expect(COUNTRY_BOOKS.PL).toBe(POLAND_BOOK);
    expect(pln(mat('mat-dc01').pricePerKg)).toBeCloseTo(3.78, 1);
    expect(mat('mat-dc01').sourceNote).toMatch(/Poland book .*zł3\.78\/kg/);
  });
  it('a casting grade is the metal CHARGE — never below the scrap it is melted from', () => {
    const scrap = 1.204;   // heavy melting scrap, zł/kg (research)
    expect(pln(mat('mat-gjs500').pricePerKg)).toBeCloseTo(1.73, 1);
    expect(pln(mat('mat-gjl250').pricePerKg)).toBeCloseTo(1.52, 1);
    for (const id of ['mat-gs-c25', 'mat-astm-a216-wcb', 'mat-g20mn5']) expect(pln(mat(id).pricePerKg), id).toBeGreaterThan(scrap);
    expect(mat('mat-gjs500').sourceNote).toMatch(/charge/i);
  });
  it('no grade below the metal it contains: copper bar ≥ LME + premium; Zamak ≥ its zinc', () => {
    expect(pln(mat('mat-c101-bar').pricePerKg)).toBeGreaterThanOrEqual(57.9);
    expect(pln(mat('mat-zamak3').pricePerKg)).toBeGreaterThanOrEqual(16.6);
    expect(pln(mat('mat-lm25').pricePerKg)).toBeGreaterThanOrEqual(14.5);   // primary foundry alloy ≥ P1020
  });
  it('resins at the Central & Eastern Europe market; HIPS is no longer the GPPS price', () => {
    expect(pln(mat('mat-pp-homo').pricePerKg)).toBeCloseTo(5.11, 1);
    expect(mat('mat-pp-impact').pricePerKg).toBeGreaterThanOrEqual(mat('mat-pp-homo').pricePerKg);
    expect(pln(mat('mat-pa66').pricePerKg)).toBeCloseTo(16.28, 1);
    expect(pln(mat('mat-hips').pricePerKg)).toBeCloseTo(7.33, 1);
    expect(mat('mat-hips').pricePerKg).toBeGreaterThan(mat('mat-gpps').pricePerKg);
  });
  it('every book price says what it is, where it came from and how sure it is', () => {
    for (const [id, p] of Object.entries(POLAND_BOOK.materials)) {
      expect(p.basis.length, id).toBeGreaterThan(20);
      expect(p.source, id).toMatch(/https?:\/\//);
      expect(['High', 'Medium', 'Low']).toContain(p.confidence);
    }
  });
  it('a grade with no Polish evidence says so, country first', () => {
    expect(mat('mat-pa66gf30').sourceNote).toMatch(/^Poland: no Poland price for this grade/);
  });
  it('the extrusion billet premium is sourced (LME + DDP North Germany premium)', () => {
    expect(BILLET_PREMIUM_USD_PER_T.PL.sourced).toBe(true);
    expect(BILLET_PREMIUM_USD_PER_T.PL.basis).toMatch(/\$1,070–1,135/);   // a '$1' in a replacement string once printed "false,070"
  });
});

describe('labour and energy', () => {
  it('a skilled machinist is ~zł66/h fully loaded on 3 × 8 h (was zł60.64); lab-pl agrees with the table', () => {
    expect(pln(lab('lab-uk-skilled').fullyLoadedRatePerHr)).toBeCloseTo(66.34, 0);
    expect(pln(lab('lab-uk-semiskilled').fullyLoadedRatePerHr)).toBeCloseTo(61.46, 0);
    expect(DEFAULT_RATE_LIBRARY.labour.find(l => l.id === 'lab-pl-skilled')!.fullyLoadedRatePerHr).toBeCloseTo(REGIONAL_DATA.PL.labour.skilled, 6);
    expect(DEFAULT_RATE_LIBRARY.labour.find(l => l.id === 'lab-pl-foundry')!.fullyLoadedRatePerHr).toBeCloseTo(REGIONAL_DATA.PL.labour.foundry, 6);
    expect(lab('lab-uk-forge').sourceNote).toMatch(/Poland book/);
  });
  it('gas at the exchange + distribution (zł0.249, was zł0.408); electricity at the 2026 build-up', () => {
    expect(pln(REGIONAL_DATA.PL.energy.gasPerKwh)).toBeCloseTo(0.249, 2);
    expect(pln(REGIONAL_DATA.PL.energy.electricityPerKwh)).toBeCloseTo(0.702, 2);
    const e = DEFAULT_RATE_LIBRARY.energy.find(x => x.id === 'energy-pl')!;
    expect(e.gasPerKwh).toBe(REGIONAL_DATA.PL.energy.gasPerKwh);
    expect(e.sourceNote).toMatch(/^Poland rate book/);
  });
});

describe('machines: the 3 × 8 h operating model; EU capex for CNC', () => {
  it('a 3-axis VMC is a ~zł284k Haas EU machine over 6,024 h, machine only', () => {
    const v = mach('mach-vmc3');
    expect(v.buildup.annualAvailableHours).toBe(6024);
    expect(v.sourceNote).toMatch(/Haas/);
    expect(pln(v.computedRatePerHr)).toBeGreaterThan(20);
    expect(pln(v.computedRatePerHr)).toBeLessThan(45);
  });
  it('a machine without capex evidence says its capital is HELD', () => {
    expect(mach('press-400t').sourceNote).toMatch(/HELD/);
    expect(mach('press-400t').confidence).toBe('Low');
  });
});

describe('round 2 (10 Oct 2026): what round 1 left held', () => {
  it('primary cast aluminium follows AlSi7Mg (LME + the foundry-alloy premium), never below it', () => {
    expect(pln(mat('mat-lm25').pricePerKg)).toBeCloseTo(16.35, 1);
    for (const id of ['mat-a357', 'mat-alsi10mg', 'mat-silafont36']) expect(pln(mat(id).pricePerKg), id).toBeGreaterThanOrEqual(16.34);
  });
  it('no forging stock below its billet, no rolled sheet below the European average, no blend below its resins', () => {
    expect(pln(mat('mat-al6082-forge').pricePerKg)).toBeGreaterThanOrEqual(16.74);
    expect(pln(mat('mat-aa5754-sheet').pricePerKg)).toBeGreaterThanOrEqual(18.19);
    expect(pln(mat('mat-pc-abs').pricePerKg)).toBeGreaterThanOrEqual(10.48);
    expect(pln(mat('mat-cf-dry-3k').pricePerKg)).toBeGreaterThanOrEqual(130.8);
  });
  it('POM at the European index; HRPO and 409L derived and labelled', () => {
    expect(pln(mat('mat-pom').pricePerKg)).toBeCloseTo(11.70, 1);
    expect(mat('mat-hrpo').sourceNote).toMatch(/DERIVED/);
    expect(pln(mat('mat-ss409l-sheet').pricePerKg)).toBeCloseTo(6.48, 1);
  });
  it('press brakes on the TruBend 3100 EU price, not the UK build-up (~4× higher)', () => {
    const b = mach('brake-trumpf-trubend3100');
    expect(b.sourceNote).toMatch(/TruBend 3100/);
    expect(b.sourceNote).not.toMatch(/HELD/);
    expect(mach('brake-amada-hfe100').sourceNote).toMatch(/press-brake-eu/);
  });
  it('the overhead / packaging / logistics multipliers stay held — no source supported a change', () => {
    expect(REGIONAL_DATA.PL.overheadMultiplier).toBe(0.85);
    expect(REGIONAL_DATA.PL.logisticsMultiplier).toBe(1.20);
  });
});

describe('the register', () => {
  const reg = readFileSync('scripts/rate-refresh/poland-2026-10/register.csv', 'utf8').trim().split('\n').slice(1);
  it('every library material and machine is in it once, with a decision', () => {
    const ids = reg.map(l => l.split('","')[1]);
    for (const m of DEFAULT_RATE_LIBRARY.materials) expect(ids.filter(i => i === m.id).length, m.id).toBe(1);
    for (const m of DEFAULT_RATE_LIBRARY.machines) expect(ids.filter(i => i === m.id).length, m.id).toBe(1);
  });
  it('the UK book is untouched', () => {
    const ukBook = buildRegionalLibrary(UK, 'UK');
    expect(ukBook.materials.find(m => m.id === 'mat-dc01')!.pricePerKg).toBe(DEFAULT_RATE_LIBRARY.materials.find(m => m.id === 'mat-dc01')!.pricePerKg);
  });
});
